// Code generated by Kitex v0.13.1. DO NOT EDIT.

package user

import (
	"context"

	"github.com/cloudwego/prutal"
)

type SendCodeReq struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (x *SendCodeReq) Reset() { *x = SendCodeReq{} }

func (x *SendCodeReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendCodeReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendCodeResp struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *SendCodeResp) Reset() { *x = SendCodeResp{} }

func (x *SendCodeResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendCodeResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendCodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Code     string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (x *RegisterReq) Reset() { *x = RegisterReq{} }

func (x *RegisterReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	UserId       string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Username     string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email        string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Avatar       string `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
	Bio          string `protobuf:"bytes,5,opt,name=bio" json:"bio,omitempty"`
	RegisterDate string `protobuf:"bytes,6,opt,name=register_date" json:"register_date,omitempty"`
	Theme        string `protobuf:"bytes,7,opt,name=theme" json:"theme,omitempty"`
	AccessToken  string `protobuf:"bytes,8,opt,name=access_token" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,9,opt,name=refresh_token" json:"refresh_token,omitempty"`
}

func (x *RegisterResp) Reset() { *x = RegisterResp{} }

func (x *RegisterResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RegisterResp) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *RegisterResp) GetRegisterDate() string {
	if x != nil {
		return x.RegisterDate
	}
	return ""
}

func (x *RegisterResp) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *RegisterResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (x *LoginReq) Reset() { *x = LoginReq{} }

func (x *LoginReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	UserId       string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Username     string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email        string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Avatar       string `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
	Bio          string `protobuf:"bytes,5,opt,name=bio" json:"bio,omitempty"`
	RegisterDate string `protobuf:"bytes,6,opt,name=register_date" json:"register_date,omitempty"`
	Theme        string `protobuf:"bytes,7,opt,name=theme" json:"theme,omitempty"`
	AccessToken  string `protobuf:"bytes,8,opt,name=access_token" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,9,opt,name=refresh_token" json:"refresh_token,omitempty"`
}

func (x *LoginResp) Reset() { *x = LoginResp{} }

func (x *LoginResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LoginResp) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *LoginResp) GetRegisterDate() string {
	if x != nil {
		return x.RegisterDate
	}
	return ""
}

func (x *LoginResp) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 新增请求和响应消息
type UpdateUserInfoReq struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Theme    string `protobuf:"bytes,4,opt,name=theme" json:"theme,omitempty"`
	Bio      string `protobuf:"bytes,5,opt,name=bio" json:"bio,omitempty"`
}

func (x *UpdateUserInfoReq) Reset() { *x = UpdateUserInfoReq{} }

func (x *UpdateUserInfoReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateUserInfoReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserInfoReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserInfoReq) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UpdateUserInfoReq) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type ChangePasswordReq struct {
	UserId      string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	OldPassword string `protobuf:"bytes,2,opt,name=old_password" json:"old_password,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=new_password" json:"new_password,omitempty"`
}

func (x *ChangePasswordReq) Reset() { *x = ChangePasswordReq{} }

func (x *ChangePasswordReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChangePasswordReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChangePasswordReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdateUserInfoResp struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *UpdateUserInfoResp) Reset() { *x = UpdateUserInfoResp{} }

func (x *UpdateUserInfoResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateUserInfoResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateUserInfoResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserInfoResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChangePasswordResp struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *ChangePasswordResp) Reset() { *x = ChangePasswordResp{} }

func (x *ChangePasswordResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChangePasswordResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChangePasswordResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChangePasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserInfoReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetUserInfoReq) Reset() { *x = GetUserInfoReq{} }

func (x *GetUserInfoReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserInfoReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoResp struct {
	UserId       string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Username     string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email        string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Avatar       string `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
	Bio          string `protobuf:"bytes,5,opt,name=bio" json:"bio,omitempty"`
	RegisterDate string `protobuf:"bytes,6,opt,name=register_date" json:"register_date,omitempty"`
	Theme        string `protobuf:"bytes,7,opt,name=theme" json:"theme,omitempty"`
}

func (x *GetUserInfoResp) Reset() { *x = GetUserInfoResp{} }

func (x *GetUserInfoResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserInfoResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserInfoResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserInfoResp) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetUserInfoResp) GetRegisterDate() string {
	if x != nil {
		return x.RegisterDate
	}
	return ""
}

func (x *GetUserInfoResp) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type DeleteUserReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *DeleteUserReq) Reset() { *x = DeleteUserReq{} }

func (x *DeleteUserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResp struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *DeleteUserResp) Reset() { *x = DeleteUserResp{} }

func (x *DeleteUserResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteUserResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteUserResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserService interface {
	SendCode(ctx context.Context, req *SendCodeReq) (res *SendCodeResp, err error)
	Register(ctx context.Context, req *RegisterReq) (res *RegisterResp, err error)
	Login(ctx context.Context, req *LoginReq) (res *LoginResp, err error)
	ChangePassword(ctx context.Context, req *ChangePasswordReq) (res *ChangePasswordResp, err error)
	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq) (res *UpdateUserInfoResp, err error)
	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (res *GetUserInfoResp, err error)
	DeleteUser(ctx context.Context, req *DeleteUserReq) (res *DeleteUserResp, err error)
}
