// Code generated by Kitex v0.13.1. DO NOT EDIT.

package item

import (
	"context"
	"github.com/linkbox-group/linkbox-server/rpc-gen/common/cError"
	"github.com/linkbox-group/linkbox-server/rpc-gen/common/pagination"
	"github.com/linkbox-group/linkbox-server/rpc-gen/model"

	"github.com/cloudwego/prutal"
)

// 获取组织内容项请求
type GetItemsByOrganizationRequest struct {
	UserId         string                        `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	OrganizationId string                        `protobuf:"bytes,2,opt,name=organization_id" json:"organization_id,omitempty"`
	Pagination     *pagination.PaginationRequest `protobuf:"bytes,3,opt,name=pagination" json:"pagination,omitempty"`
	Sort           *pagination.SortRequest       `protobuf:"bytes,4,opt,name=sort" json:"sort,omitempty"`
}

func (x *GetItemsByOrganizationRequest) Reset() { *x = GetItemsByOrganizationRequest{} }

func (x *GetItemsByOrganizationRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetItemsByOrganizationRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemsByOrganizationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetItemsByOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetItemsByOrganizationRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetItemsByOrganizationRequest) GetSort() *pagination.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

// 获取组织内容项响应
type GetItemsByOrganizationResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetItemsByOrganizationResponse_ItemsPage
	//	*GetItemsByOrganizationResponse_Error
	Result isGetItemsByOrganizationResponse_Result `protobuf_oneof:"result"`
}

func (x *GetItemsByOrganizationResponse) Reset() { *x = GetItemsByOrganizationResponse{} }

func (x *GetItemsByOrganizationResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetItemsByOrganizationResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemsByOrganizationResponse) GetResult() isGetItemsByOrganizationResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetItemsByOrganizationResponse) GetItemsPage() *ItemsPage {
	if p, ok := x.GetResult().(*GetItemsByOrganizationResponse_ItemsPage); ok {
		return p.ItemsPage
	}
	return nil
}

func (x *GetItemsByOrganizationResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetItemsByOrganizationResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetItemsByOrganizationResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetItemsByOrganizationResponse_ItemsPage)(nil),
		(*GetItemsByOrganizationResponse_Error)(nil),
	}
}

type isGetItemsByOrganizationResponse_Result interface {
	isGetItemsByOrganizationResponse_Result()
}

type GetItemsByOrganizationResponse_ItemsPage struct {
	ItemsPage *ItemsPage `protobuf:"bytes,1,opt,name=items_page" json:"items_page,omitempty"`
}

func (*GetItemsByOrganizationResponse_ItemsPage) isGetItemsByOrganizationResponse_Result() {}

type GetItemsByOrganizationResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetItemsByOrganizationResponse_Error) isGetItemsByOrganizationResponse_Result() {}

// 创建内容项请求
type CreateItemRequest struct {
	UserId         string         `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Type           model.ItemType `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Url            string         `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Title          string         `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Description    string         `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	ThumbnailUrl   string         `protobuf:"bytes,6,opt,name=thumbnail_url" json:"thumbnail_url,omitempty"`
	Tags           []string       `protobuf:"bytes,8,rep,name=tags" json:"tags,omitempty"`
	OrganizationId string         `protobuf:"bytes,9,opt,name=organization_id" json:"organization_id,omitempty"`
	Note           string         `protobuf:"bytes,12,opt,name=note" json:"note,omitempty"`
}

func (x *CreateItemRequest) Reset() { *x = CreateItemRequest{} }

func (x *CreateItemRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateItemRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateItemRequest) GetType() model.ItemType {
	if x != nil {
		return x.Type
	}
	return model.ItemType_UNKNOWN_TYPE
}

func (x *CreateItemRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateItemRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *CreateItemRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateItemRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateItemRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// 创建内容项响应
type CreateItemResponse struct {
	// Types that are assignable to Result:
	//
	//	*CreateItemResponse_Item
	//	*CreateItemResponse_Error
	Result isCreateItemResponse_Result `protobuf_oneof:"result"`
}

func (x *CreateItemResponse) Reset() { *x = CreateItemResponse{} }

func (x *CreateItemResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateItemResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateItemResponse) GetResult() isCreateItemResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *CreateItemResponse) GetItem() *model.Item {
	if p, ok := x.GetResult().(*CreateItemResponse_Item); ok {
		return p.Item
	}
	return nil
}

func (x *CreateItemResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*CreateItemResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*CreateItemResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateItemResponse_Item)(nil),
		(*CreateItemResponse_Error)(nil),
	}
}

type isCreateItemResponse_Result interface {
	isCreateItemResponse_Result()
}

type CreateItemResponse_Item struct {
	Item *model.Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (*CreateItemResponse_Item) isCreateItemResponse_Result() {}

type CreateItemResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*CreateItemResponse_Error) isCreateItemResponse_Result() {}

// 获取内容项请求
type GetItemRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetItemRequest) Reset() { *x = GetItemRequest{} }

func (x *GetItemRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取内容项响应
type GetItemResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetItemResponse_Item
	//	*GetItemResponse_Error
	Result isGetItemResponse_Result `protobuf_oneof:"result"`
}

func (x *GetItemResponse) Reset() { *x = GetItemResponse{} }

func (x *GetItemResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemResponse) GetResult() isGetItemResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetItemResponse) GetItem() *model.Item {
	if p, ok := x.GetResult().(*GetItemResponse_Item); ok {
		return p.Item
	}
	return nil
}

func (x *GetItemResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetItemResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetItemResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetItemResponse_Item)(nil),
		(*GetItemResponse_Error)(nil),
	}
}

type isGetItemResponse_Result interface {
	isGetItemResponse_Result()
}

type GetItemResponse_Item struct {
	Item *model.Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (*GetItemResponse_Item) isGetItemResponse_Result() {}

type GetItemResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetItemResponse_Error) isGetItemResponse_Result() {}

// 更新内容项请求
type UpdateItemRequest struct {
	Id             string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId         string   `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	Title          string   `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Description    string   `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	ThumbnailUrl   string   `protobuf:"bytes,5,opt,name=thumbnail_url" json:"thumbnail_url,omitempty"`
	Tags           []string `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	OrganizationId string   `protobuf:"bytes,8,opt,name=organization_id" json:"organization_id,omitempty"`
	Url            string   `protobuf:"bytes,9,opt,name=url" json:"url,omitempty"`
	Note           string   `protobuf:"bytes,10,opt,name=note" json:"note,omitempty"`
}

func (x *UpdateItemRequest) Reset() { *x = UpdateItemRequest{} }

func (x *UpdateItemRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateItemRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateItemRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *UpdateItemRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateItemRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateItemRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateItemRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// 更新内容项响应
type UpdateItemResponse struct {
	// Types that are assignable to Result:
	//
	//	*UpdateItemResponse_Item
	//	*UpdateItemResponse_Error
	Result isUpdateItemResponse_Result `protobuf_oneof:"result"`
}

func (x *UpdateItemResponse) Reset() { *x = UpdateItemResponse{} }

func (x *UpdateItemResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateItemResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateItemResponse) GetResult() isUpdateItemResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *UpdateItemResponse) GetItem() *model.Item {
	if p, ok := x.GetResult().(*UpdateItemResponse_Item); ok {
		return p.Item
	}
	return nil
}

func (x *UpdateItemResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*UpdateItemResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*UpdateItemResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UpdateItemResponse_Item)(nil),
		(*UpdateItemResponse_Error)(nil),
	}
}

type isUpdateItemResponse_Result interface {
	isUpdateItemResponse_Result()
}

type UpdateItemResponse_Item struct {
	Item *model.Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (*UpdateItemResponse_Item) isUpdateItemResponse_Result() {}

type UpdateItemResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*UpdateItemResponse_Error) isUpdateItemResponse_Result() {}

// 删除内容项请求
type DeleteItemRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *DeleteItemRequest) Reset() { *x = DeleteItemRequest{} }

func (x *DeleteItemRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteItemRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 删除内容项响应
type DeleteItemResponse struct {
	// Types that are assignable to Result:
	//
	//	*DeleteItemResponse_Success
	//	*DeleteItemResponse_Error
	Result isDeleteItemResponse_Result `protobuf_oneof:"result"`
}

func (x *DeleteItemResponse) Reset() { *x = DeleteItemResponse{} }

func (x *DeleteItemResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteItemResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteItemResponse) GetResult() isDeleteItemResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *DeleteItemResponse) GetSuccess() bool {
	if p, ok := x.GetResult().(*DeleteItemResponse_Success); ok {
		return p.Success
	}
	return false
}

func (x *DeleteItemResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*DeleteItemResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*DeleteItemResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteItemResponse_Success)(nil),
		(*DeleteItemResponse_Error)(nil),
	}
}

type isDeleteItemResponse_Result interface {
	isDeleteItemResponse_Result()
}

type DeleteItemResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (*DeleteItemResponse_Success) isDeleteItemResponse_Result() {}

type DeleteItemResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*DeleteItemResponse_Error) isDeleteItemResponse_Result() {}

// 批量获取内容项请求
type GetItemsRequest struct {
	UserId string   `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Ids    []string `protobuf:"bytes,2,rep,name=ids" json:"ids,omitempty"`
}

func (x *GetItemsRequest) Reset() { *x = GetItemsRequest{} }

func (x *GetItemsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetItemsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 批量获取内容项响应
type GetItemsResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetItemsResponse_Items
	//	*GetItemsResponse_Error
	Result isGetItemsResponse_Result `protobuf_oneof:"result"`
}

func (x *GetItemsResponse) Reset() { *x = GetItemsResponse{} }

func (x *GetItemsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemsResponse) GetResult() isGetItemsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetItemsResponse) GetItems() *ItemsData {
	if p, ok := x.GetResult().(*GetItemsResponse_Items); ok {
		return p.Items
	}
	return nil
}

func (x *GetItemsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetItemsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetItemsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetItemsResponse_Items)(nil),
		(*GetItemsResponse_Error)(nil),
	}
}

type isGetItemsResponse_Result interface {
	isGetItemsResponse_Result()
}

type GetItemsResponse_Items struct {
	Items *ItemsData `protobuf:"bytes,1,opt,name=items" json:"items,omitempty"`
}

func (*GetItemsResponse_Items) isGetItemsResponse_Result() {}

type GetItemsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetItemsResponse_Error) isGetItemsResponse_Result() {}

// 内容项列表数据
type ItemsData struct {
	Items []*model.Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (x *ItemsData) Reset() { *x = ItemsData{} }

func (x *ItemsData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ItemsData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ItemsData) GetItems() []*model.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 按标签获取内容项请求
type GetItemsByTagsRequest struct {
	UserId     string                        `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Tags       []string                      `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	Pagination *pagination.PaginationRequest `protobuf:"bytes,3,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *GetItemsByTagsRequest) Reset() { *x = GetItemsByTagsRequest{} }

func (x *GetItemsByTagsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetItemsByTagsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemsByTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetItemsByTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetItemsByTagsRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 按标签获取内容项响应
type GetItemsByTagsResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetItemsByTagsResponse_ItemsPage
	//	*GetItemsByTagsResponse_Error
	Result isGetItemsByTagsResponse_Result `protobuf_oneof:"result"`
}

func (x *GetItemsByTagsResponse) Reset() { *x = GetItemsByTagsResponse{} }

func (x *GetItemsByTagsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetItemsByTagsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemsByTagsResponse) GetResult() isGetItemsByTagsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetItemsByTagsResponse) GetItemsPage() *ItemsPage {
	if p, ok := x.GetResult().(*GetItemsByTagsResponse_ItemsPage); ok {
		return p.ItemsPage
	}
	return nil
}

func (x *GetItemsByTagsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetItemsByTagsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetItemsByTagsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetItemsByTagsResponse_ItemsPage)(nil),
		(*GetItemsByTagsResponse_Error)(nil),
	}
}

type isGetItemsByTagsResponse_Result interface {
	isGetItemsByTagsResponse_Result()
}

type GetItemsByTagsResponse_ItemsPage struct {
	ItemsPage *ItemsPage `protobuf:"bytes,1,opt,name=items_page" json:"items_page,omitempty"`
}

func (*GetItemsByTagsResponse_ItemsPage) isGetItemsByTagsResponse_Result() {}

type GetItemsByTagsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetItemsByTagsResponse_Error) isGetItemsByTagsResponse_Result() {}

// 内容项分页数据
type ItemsPage struct {
	Items      []*model.Item              `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Pagination *pagination.PaginationMeta `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *ItemsPage) Reset() { *x = ItemsPage{} }

func (x *ItemsPage) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ItemsPage) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ItemsPage) GetItems() []*model.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemsPage) GetPagination() *pagination.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 获取最近内容项请求
type GetRecentItemsRequest struct {
	UserId          string         `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Limit           int32          `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Type            model.ItemType `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	ExcludeArchived bool           `protobuf:"varint,4,opt,name=exclude_archived" json:"exclude_archived,omitempty"`
}

func (x *GetRecentItemsRequest) Reset() { *x = GetRecentItemsRequest{} }

func (x *GetRecentItemsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetRecentItemsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetRecentItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecentItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRecentItemsRequest) GetType() model.ItemType {
	if x != nil {
		return x.Type
	}
	return model.ItemType_UNKNOWN_TYPE
}

func (x *GetRecentItemsRequest) GetExcludeArchived() bool {
	if x != nil {
		return x.ExcludeArchived
	}
	return false
}

// 获取最近内容项响应
type GetRecentItemsResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetRecentItemsResponse_Items
	//	*GetRecentItemsResponse_Error
	Result isGetRecentItemsResponse_Result `protobuf_oneof:"result"`
}

func (x *GetRecentItemsResponse) Reset() { *x = GetRecentItemsResponse{} }

func (x *GetRecentItemsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetRecentItemsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetRecentItemsResponse) GetResult() isGetRecentItemsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetRecentItemsResponse) GetItems() *ItemsData {
	if p, ok := x.GetResult().(*GetRecentItemsResponse_Items); ok {
		return p.Items
	}
	return nil
}

func (x *GetRecentItemsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetRecentItemsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetRecentItemsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetRecentItemsResponse_Items)(nil),
		(*GetRecentItemsResponse_Error)(nil),
	}
}

type isGetRecentItemsResponse_Result interface {
	isGetRecentItemsResponse_Result()
}

type GetRecentItemsResponse_Items struct {
	Items *ItemsData `protobuf:"bytes,1,opt,name=items" json:"items,omitempty"`
}

func (*GetRecentItemsResponse_Items) isGetRecentItemsResponse_Result() {}

type GetRecentItemsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetRecentItemsResponse_Error) isGetRecentItemsResponse_Result() {}

// 从文件导入内容请求
type ImportFromFileRequest struct {
	UserId      string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	FileContent string `protobuf:"bytes,2,opt,name=file_content" json:"file_content,omitempty"` // Base64编码的文件内容
	FileFormat  string `protobuf:"bytes,3,opt,name=file_format" json:"file_format,omitempty"`   // "html", "json", "csv"
}

func (x *ImportFromFileRequest) Reset() { *x = ImportFromFileRequest{} }

func (x *ImportFromFileRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ImportFromFileRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ImportFromFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImportFromFileRequest) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

func (x *ImportFromFileRequest) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

// 从文件导入内容响应
type ImportFromFileResponse struct {
	// Types that are assignable to Result:
	//
	//	*ImportFromFileResponse_Data
	//	*ImportFromFileResponse_Error
	Result isImportFromFileResponse_Result `protobuf_oneof:"result"`
}

func (x *ImportFromFileResponse) Reset() { *x = ImportFromFileResponse{} }

func (x *ImportFromFileResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ImportFromFileResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ImportFromFileResponse) GetResult() isImportFromFileResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *ImportFromFileResponse) GetData() *ImportResult {
	if p, ok := x.GetResult().(*ImportFromFileResponse_Data); ok {
		return p.Data
	}
	return nil
}

func (x *ImportFromFileResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*ImportFromFileResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*ImportFromFileResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ImportFromFileResponse_Data)(nil),
		(*ImportFromFileResponse_Error)(nil),
	}
}

type isImportFromFileResponse_Result interface {
	isImportFromFileResponse_Result()
}

type ImportFromFileResponse_Data struct {
	Data *ImportResult `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (*ImportFromFileResponse_Data) isImportFromFileResponse_Result() {}

type ImportFromFileResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*ImportFromFileResponse_Error) isImportFromFileResponse_Result() {}

// 导入结果
type ImportResult struct {
	TotalProcessed int32    `protobuf:"varint,1,opt,name=total_processed" json:"total_processed,omitempty"`
	SuccessCount   int32    `protobuf:"varint,2,opt,name=success_count" json:"success_count,omitempty"`
	FailureCount   int32    `protobuf:"varint,3,opt,name=failure_count" json:"failure_count,omitempty"`
	FailedUrls     []string `protobuf:"bytes,4,rep,name=failed_urls" json:"failed_urls,omitempty"`
}

func (x *ImportResult) Reset() { *x = ImportResult{} }

func (x *ImportResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ImportResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ImportResult) GetTotalProcessed() int32 {
	if x != nil {
		return x.TotalProcessed
	}
	return 0
}

func (x *ImportResult) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ImportResult) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *ImportResult) GetFailedUrls() []string {
	if x != nil {
		return x.FailedUrls
	}
	return nil
}

// 导出内容到文件请求
type ExportToFileRequest struct {
	UserId          string   `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	OrganizationId  string   `protobuf:"bytes,2,opt,name=organization_id" json:"organization_id,omitempty"`
	Tags            []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	FileFormat      string   `protobuf:"bytes,4,opt,name=file_format" json:"file_format,omitempty"` // "html", "json", "csv"
	IncludeArchived bool     `protobuf:"varint,5,opt,name=include_archived" json:"include_archived,omitempty"`
}

func (x *ExportToFileRequest) Reset() { *x = ExportToFileRequest{} }

func (x *ExportToFileRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ExportToFileRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ExportToFileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExportToFileRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ExportToFileRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ExportToFileRequest) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

func (x *ExportToFileRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

// 导出内容到文件响应
type ExportToFileResponse struct {
	// Types that are assignable to Result:
	//
	//	*ExportToFileResponse_Data
	//	*ExportToFileResponse_Error
	Result isExportToFileResponse_Result `protobuf_oneof:"result"`
}

func (x *ExportToFileResponse) Reset() { *x = ExportToFileResponse{} }

func (x *ExportToFileResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ExportToFileResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ExportToFileResponse) GetResult() isExportToFileResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *ExportToFileResponse) GetData() *ExportResult {
	if p, ok := x.GetResult().(*ExportToFileResponse_Data); ok {
		return p.Data
	}
	return nil
}

func (x *ExportToFileResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*ExportToFileResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*ExportToFileResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExportToFileResponse_Data)(nil),
		(*ExportToFileResponse_Error)(nil),
	}
}

type isExportToFileResponse_Result interface {
	isExportToFileResponse_Result()
}

type ExportToFileResponse_Data struct {
	Data *ExportResult `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (*ExportToFileResponse_Data) isExportToFileResponse_Result() {}

type ExportToFileResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*ExportToFileResponse_Error) isExportToFileResponse_Result() {}

// 导出结果
type ExportResult struct {
	FileContent string `protobuf:"bytes,1,opt,name=file_content" json:"file_content,omitempty"` // Base64编码的文件内容
	FileName    string `protobuf:"bytes,2,opt,name=file_name" json:"file_name,omitempty"`
	MimeType    string `protobuf:"bytes,3,opt,name=mime_type" json:"mime_type,omitempty"`
	ItemCount   int32  `protobuf:"varint,4,opt,name=item_count" json:"item_count,omitempty"`
}

func (x *ExportResult) Reset() { *x = ExportResult{} }

func (x *ExportResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ExportResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ExportResult) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

func (x *ExportResult) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExportResult) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ExportResult) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

// 内容项全文搜索请求
type SearchItemsRequest struct {
	UserId     string                        `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Query      string                        `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	Pagination *pagination.PaginationRequest `protobuf:"bytes,3,opt,name=pagination" json:"pagination,omitempty"`
	Type       model.ItemType                `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
}

func (x *SearchItemsRequest) Reset() { *x = SearchItemsRequest{} }

func (x *SearchItemsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchItemsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchItemsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchItemsRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchItemsRequest) GetType() model.ItemType {
	if x != nil {
		return x.Type
	}
	return model.ItemType_UNKNOWN_TYPE
}

// 内容项全文搜索响应
type SearchItemsResponse struct {
	// Types that are assignable to Result:
	//
	//	*SearchItemsResponse_Data
	//	*SearchItemsResponse_Error
	Result isSearchItemsResponse_Result `protobuf_oneof:"result"`
}

func (x *SearchItemsResponse) Reset() { *x = SearchItemsResponse{} }

func (x *SearchItemsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchItemsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchItemsResponse) GetResult() isSearchItemsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *SearchItemsResponse) GetData() *SearchResult {
	if p, ok := x.GetResult().(*SearchItemsResponse_Data); ok {
		return p.Data
	}
	return nil
}

func (x *SearchItemsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*SearchItemsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*SearchItemsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SearchItemsResponse_Data)(nil),
		(*SearchItemsResponse_Error)(nil),
	}
}

type isSearchItemsResponse_Result interface {
	isSearchItemsResponse_Result()
}

type SearchItemsResponse_Data struct {
	Data *SearchResult `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (*SearchItemsResponse_Data) isSearchItemsResponse_Result() {}

type SearchItemsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*SearchItemsResponse_Error) isSearchItemsResponse_Result() {}

// 搜索结果
type SearchResult struct {
	Items      []*model.Item              `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Pagination *pagination.PaginationMeta `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *SearchResult) Reset() { *x = SearchResult{} }

func (x *SearchResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchResult) GetItems() []*model.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResult) GetPagination() *pagination.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 标签计数
type TagCount struct {
	Tag   string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (x *TagCount) Reset() { *x = TagCount{} }

func (x *TagCount) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TagCount) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TagCount) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RecoverItemRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *RecoverItemRequest) Reset() { *x = RecoverItemRequest{} }

func (x *RecoverItemRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RecoverItemRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RecoverItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecoverItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RecoverItemREsponse struct {
	// Types that are assignable to Result:
	//
	//	*RecoverItemREsponse_Success
	//	*RecoverItemREsponse_Error
	Result isRecoverItemREsponse_Result `protobuf_oneof:"result"`
}

func (x *RecoverItemREsponse) Reset() { *x = RecoverItemREsponse{} }

func (x *RecoverItemREsponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RecoverItemREsponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RecoverItemREsponse) GetResult() isRecoverItemREsponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *RecoverItemREsponse) GetSuccess() bool {
	if p, ok := x.GetResult().(*RecoverItemREsponse_Success); ok {
		return p.Success
	}
	return false
}

func (x *RecoverItemREsponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*RecoverItemREsponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*RecoverItemREsponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RecoverItemREsponse_Success)(nil),
		(*RecoverItemREsponse_Error)(nil),
	}
}

type isRecoverItemREsponse_Result interface {
	isRecoverItemREsponse_Result()
}

type RecoverItemREsponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (*RecoverItemREsponse_Success) isRecoverItemREsponse_Result() {}

type RecoverItemREsponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*RecoverItemREsponse_Error) isRecoverItemREsponse_Result() {}

type GetDeletedItemsRequest struct {
	UserId     string                        `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Pagination *pagination.PaginationRequest `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *GetDeletedItemsRequest) Reset() { *x = GetDeletedItemsRequest{} }

func (x *GetDeletedItemsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetDeletedItemsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetDeletedItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDeletedItemsRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetDeletedItemsResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetDeletedItemsResponse_ItemsPage
	//	*GetDeletedItemsResponse_Error
	Result isGetDeletedItemsResponse_Result `protobuf_oneof:"result"`
}

func (x *GetDeletedItemsResponse) Reset() { *x = GetDeletedItemsResponse{} }

func (x *GetDeletedItemsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetDeletedItemsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetDeletedItemsResponse) GetResult() isGetDeletedItemsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetDeletedItemsResponse) GetItemsPage() *ItemsPage {
	if p, ok := x.GetResult().(*GetDeletedItemsResponse_ItemsPage); ok {
		return p.ItemsPage
	}
	return nil
}

func (x *GetDeletedItemsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetDeletedItemsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetDeletedItemsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetDeletedItemsResponse_ItemsPage)(nil),
		(*GetDeletedItemsResponse_Error)(nil),
	}
}

type isGetDeletedItemsResponse_Result interface {
	isGetDeletedItemsResponse_Result()
}

type GetDeletedItemsResponse_ItemsPage struct {
	ItemsPage *ItemsPage `protobuf:"bytes,1,opt,name=items_page" json:"items_page,omitempty"`
}

func (*GetDeletedItemsResponse_ItemsPage) isGetDeletedItemsResponse_Result() {}

type GetDeletedItemsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetDeletedItemsResponse_Error) isGetDeletedItemsResponse_Result() {}

type RecoverItemsBatchRequest struct {
	UserId string   `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Ids    []string `protobuf:"bytes,2,rep,name=ids" json:"ids,omitempty"`
}

func (x *RecoverItemsBatchRequest) Reset() { *x = RecoverItemsBatchRequest{} }

func (x *RecoverItemsBatchRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RecoverItemsBatchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RecoverItemsBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecoverItemsBatchRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RecoverItemsBatchResponse struct {
	// Types that are assignable to Result:
	//
	//	*RecoverItemsBatchResponse_Success
	//	*RecoverItemsBatchResponse_Error
	Result isRecoverItemsBatchResponse_Result `protobuf_oneof:"result"`
}

func (x *RecoverItemsBatchResponse) Reset() { *x = RecoverItemsBatchResponse{} }

func (x *RecoverItemsBatchResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RecoverItemsBatchResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RecoverItemsBatchResponse) GetResult() isRecoverItemsBatchResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *RecoverItemsBatchResponse) GetSuccess() bool {
	if p, ok := x.GetResult().(*RecoverItemsBatchResponse_Success); ok {
		return p.Success
	}
	return false
}

func (x *RecoverItemsBatchResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*RecoverItemsBatchResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*RecoverItemsBatchResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RecoverItemsBatchResponse_Success)(nil),
		(*RecoverItemsBatchResponse_Error)(nil),
	}
}

type isRecoverItemsBatchResponse_Result interface {
	isRecoverItemsBatchResponse_Result()
}

type RecoverItemsBatchResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (*RecoverItemsBatchResponse_Success) isRecoverItemsBatchResponse_Result() {}

type RecoverItemsBatchResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*RecoverItemsBatchResponse_Error) isRecoverItemsBatchResponse_Result() {}

type DeleteItemsBatchRequest struct {
	UserId string   `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Ids    []string `protobuf:"bytes,2,rep,name=ids" json:"ids,omitempty"`
}

func (x *DeleteItemsBatchRequest) Reset() { *x = DeleteItemsBatchRequest{} }

func (x *DeleteItemsBatchRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeleteItemsBatchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteItemsBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteItemsBatchRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteItemsBatchResponse struct {
	// Types that are assignable to Result:
	//
	//	*DeleteItemsBatchResponse_Success
	//	*DeleteItemsBatchResponse_Error
	Result isDeleteItemsBatchResponse_Result `protobuf_oneof:"result"`
}

func (x *DeleteItemsBatchResponse) Reset() { *x = DeleteItemsBatchResponse{} }

func (x *DeleteItemsBatchResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeleteItemsBatchResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteItemsBatchResponse) GetResult() isDeleteItemsBatchResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *DeleteItemsBatchResponse) GetSuccess() bool {
	if p, ok := x.GetResult().(*DeleteItemsBatchResponse_Success); ok {
		return p.Success
	}
	return false
}

func (x *DeleteItemsBatchResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*DeleteItemsBatchResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*DeleteItemsBatchResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteItemsBatchResponse_Success)(nil),
		(*DeleteItemsBatchResponse_Error)(nil),
	}
}

type isDeleteItemsBatchResponse_Result interface {
	isDeleteItemsBatchResponse_Result()
}

type DeleteItemsBatchResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (*DeleteItemsBatchResponse_Success) isDeleteItemsBatchResponse_Result() {}

type DeleteItemsBatchResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*DeleteItemsBatchResponse_Error) isDeleteItemsBatchResponse_Result() {}

type ItemService interface {
	CreateItem(ctx context.Context, req *CreateItemRequest) (res *CreateItemResponse, err error)
	GetItem(ctx context.Context, req *GetItemRequest) (res *GetItemResponse, err error)
	UpdateItem(ctx context.Context, req *UpdateItemRequest) (res *UpdateItemResponse, err error)
	GetItems(ctx context.Context, req *GetItemsRequest) (res *GetItemsResponse, err error)
	GetItemsByTags(ctx context.Context, req *GetItemsByTagsRequest) (res *GetItemsByTagsResponse, err error)
	GetItemsByOrganization(ctx context.Context, req *GetItemsByOrganizationRequest) (res *GetItemsByOrganizationResponse, err error)
	GetRecentItems(ctx context.Context, req *GetRecentItemsRequest) (res *GetRecentItemsResponse, err error)
	ImportFromFile(ctx context.Context, req *ImportFromFileRequest) (res *ImportFromFileResponse, err error)
	ExportToFile(ctx context.Context, req *ExportToFileRequest) (res *ExportToFileResponse, err error)
	SearchItems(ctx context.Context, req *SearchItemsRequest) (res *SearchItemsResponse, err error)
	DeleteItem(ctx context.Context, req *DeleteItemRequest) (res *DeleteItemResponse, err error)
	RecoverItem(ctx context.Context, req *RecoverItemRequest) (res *RecoverItemREsponse, err error)
	GetDeletedItems(ctx context.Context, req *GetDeletedItemsRequest) (res *GetDeletedItemsResponse, err error)
	RecoverItemsBatch(ctx context.Context, req *RecoverItemsBatchRequest) (res *RecoverItemsBatchResponse, err error)
	DeleteItemsBatch(ctx context.Context, req *DeleteItemsBatchRequest) (res *DeleteItemsBatchResponse, err error)
}
