// Code generated by Kitex v0.13.1. DO NOT EDIT.

package contentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	content "github.com/linkbox-group/linkbox-server/rpc-gen/content"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateItem(ctx context.Context, Req *content.CreateItemRequest, callOptions ...callopt.Option) (r *content.CreateItemResponse, err error)
	GetItem(ctx context.Context, Req *content.GetItemRequest, callOptions ...callopt.Option) (r *content.GetItemResponse, err error)
	UpdateItem(ctx context.Context, Req *content.UpdateItemRequest, callOptions ...callopt.Option) (r *content.UpdateItemResponse, err error)
	DeleteItem(ctx context.Context, Req *content.DeleteItemRequest, callOptions ...callopt.Option) (r *content.DeleteItemResponse, err error)
	GetItems(ctx context.Context, Req *content.GetItemsRequest, callOptions ...callopt.Option) (r *content.GetItemsResponse, err error)
	BatchDeleteItems(ctx context.Context, Req *content.BatchDeleteItemsRequest, callOptions ...callopt.Option) (r *content.BatchDeleteItemsResponse, err error)
	GetItemsByTags(ctx context.Context, Req *content.GetItemsByTagsRequest, callOptions ...callopt.Option) (r *content.GetItemsByTagsResponse, err error)
	ExtractMetadata(ctx context.Context, Req *content.ExtractMetadataRequest, callOptions ...callopt.Option) (r *content.ExtractMetadataResponse, err error)
	GetRecentItems(ctx context.Context, Req *content.GetRecentItemsRequest, callOptions ...callopt.Option) (r *content.GetRecentItemsResponse, err error)
	BatchUpdateItems(ctx context.Context, Req *content.BatchUpdateItemsRequest, callOptions ...callopt.Option) (r *content.BatchUpdateItemsResponse, err error)
	ImportFromFile(ctx context.Context, Req *content.ImportFromFileRequest, callOptions ...callopt.Option) (r *content.ImportFromFileResponse, err error)
	ExportToFile(ctx context.Context, Req *content.ExportToFileRequest, callOptions ...callopt.Option) (r *content.ExportToFileResponse, err error)
	SearchItems(ctx context.Context, Req *content.SearchItemsRequest, callOptions ...callopt.Option) (r *content.SearchItemsResponse, err error)
	AddItemNote(ctx context.Context, Req *content.AddItemNoteRequest, callOptions ...callopt.Option) (r *content.AddItemNoteResponse, err error)
	UpdateItemNote(ctx context.Context, Req *content.UpdateItemNoteRequest, callOptions ...callopt.Option) (r *content.UpdateItemNoteResponse, err error)
	GetItemNote(ctx context.Context, Req *content.GetItemNoteRequest, callOptions ...callopt.Option) (r *content.GetItemNoteResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kContentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kContentServiceClient struct {
	*kClient
}

func (p *kContentServiceClient) CreateItem(ctx context.Context, Req *content.CreateItemRequest, callOptions ...callopt.Option) (r *content.CreateItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateItem(ctx, Req)
}

func (p *kContentServiceClient) GetItem(ctx context.Context, Req *content.GetItemRequest, callOptions ...callopt.Option) (r *content.GetItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItem(ctx, Req)
}

func (p *kContentServiceClient) UpdateItem(ctx context.Context, Req *content.UpdateItemRequest, callOptions ...callopt.Option) (r *content.UpdateItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateItem(ctx, Req)
}

func (p *kContentServiceClient) DeleteItem(ctx context.Context, Req *content.DeleteItemRequest, callOptions ...callopt.Option) (r *content.DeleteItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteItem(ctx, Req)
}

func (p *kContentServiceClient) GetItems(ctx context.Context, Req *content.GetItemsRequest, callOptions ...callopt.Option) (r *content.GetItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItems(ctx, Req)
}

func (p *kContentServiceClient) BatchDeleteItems(ctx context.Context, Req *content.BatchDeleteItemsRequest, callOptions ...callopt.Option) (r *content.BatchDeleteItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchDeleteItems(ctx, Req)
}

func (p *kContentServiceClient) GetItemsByTags(ctx context.Context, Req *content.GetItemsByTagsRequest, callOptions ...callopt.Option) (r *content.GetItemsByTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItemsByTags(ctx, Req)
}

func (p *kContentServiceClient) ExtractMetadata(ctx context.Context, Req *content.ExtractMetadataRequest, callOptions ...callopt.Option) (r *content.ExtractMetadataResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ExtractMetadata(ctx, Req)
}

func (p *kContentServiceClient) GetRecentItems(ctx context.Context, Req *content.GetRecentItemsRequest, callOptions ...callopt.Option) (r *content.GetRecentItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecentItems(ctx, Req)
}

func (p *kContentServiceClient) BatchUpdateItems(ctx context.Context, Req *content.BatchUpdateItemsRequest, callOptions ...callopt.Option) (r *content.BatchUpdateItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchUpdateItems(ctx, Req)
}

func (p *kContentServiceClient) ImportFromFile(ctx context.Context, Req *content.ImportFromFileRequest, callOptions ...callopt.Option) (r *content.ImportFromFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ImportFromFile(ctx, Req)
}

func (p *kContentServiceClient) ExportToFile(ctx context.Context, Req *content.ExportToFileRequest, callOptions ...callopt.Option) (r *content.ExportToFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ExportToFile(ctx, Req)
}

func (p *kContentServiceClient) SearchItems(ctx context.Context, Req *content.SearchItemsRequest, callOptions ...callopt.Option) (r *content.SearchItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchItems(ctx, Req)
}

func (p *kContentServiceClient) AddItemNote(ctx context.Context, Req *content.AddItemNoteRequest, callOptions ...callopt.Option) (r *content.AddItemNoteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddItemNote(ctx, Req)
}

func (p *kContentServiceClient) UpdateItemNote(ctx context.Context, Req *content.UpdateItemNoteRequest, callOptions ...callopt.Option) (r *content.UpdateItemNoteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateItemNote(ctx, Req)
}

func (p *kContentServiceClient) GetItemNote(ctx context.Context, Req *content.GetItemNoteRequest, callOptions ...callopt.Option) (r *content.GetItemNoteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItemNote(ctx, Req)
}
