// Code generated by Kitex v0.13.1. DO NOT EDIT.

package contentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	content "github.com/linkbox-group/linkbox-server/rpc-gen/content"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateItem": kitex.NewMethodInfo(
		createItemHandler,
		newCreateItemArgs,
		newCreateItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetItem": kitex.NewMethodInfo(
		getItemHandler,
		newGetItemArgs,
		newGetItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateItem": kitex.NewMethodInfo(
		updateItemHandler,
		newUpdateItemArgs,
		newUpdateItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteItem": kitex.NewMethodInfo(
		deleteItemHandler,
		newDeleteItemArgs,
		newDeleteItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetItems": kitex.NewMethodInfo(
		getItemsHandler,
		newGetItemsArgs,
		newGetItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchDeleteItems": kitex.NewMethodInfo(
		batchDeleteItemsHandler,
		newBatchDeleteItemsArgs,
		newBatchDeleteItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetItemsByTags": kitex.NewMethodInfo(
		getItemsByTagsHandler,
		newGetItemsByTagsArgs,
		newGetItemsByTagsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ExtractMetadata": kitex.NewMethodInfo(
		extractMetadataHandler,
		newExtractMetadataArgs,
		newExtractMetadataResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetRecentItems": kitex.NewMethodInfo(
		getRecentItemsHandler,
		newGetRecentItemsArgs,
		newGetRecentItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchUpdateItems": kitex.NewMethodInfo(
		batchUpdateItemsHandler,
		newBatchUpdateItemsArgs,
		newBatchUpdateItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ImportFromFile": kitex.NewMethodInfo(
		importFromFileHandler,
		newImportFromFileArgs,
		newImportFromFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ExportToFile": kitex.NewMethodInfo(
		exportToFileHandler,
		newExportToFileArgs,
		newExportToFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchItems": kitex.NewMethodInfo(
		searchItemsHandler,
		newSearchItemsArgs,
		newSearchItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddItemNote": kitex.NewMethodInfo(
		addItemNoteHandler,
		newAddItemNoteArgs,
		newAddItemNoteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateItemNote": kitex.NewMethodInfo(
		updateItemNoteHandler,
		newUpdateItemNoteArgs,
		newUpdateItemNoteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetItemNote": kitex.NewMethodInfo(
		getItemNoteHandler,
		newGetItemNoteArgs,
		newGetItemNoteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	contentServiceServiceInfo                = NewServiceInfo()
	contentServiceServiceInfoForClient       = NewServiceInfoForClient()
	contentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return contentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return contentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return contentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ContentService"
	handlerType := (*content.ContentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "content",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func createItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.CreateItemRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).CreateItem(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateItemArgs:
		success, err := handler.(content.ContentService).CreateItem(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateItemResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateItemArgs() interface{} {
	return &CreateItemArgs{}
}

func newCreateItemResult() interface{} {
	return &CreateItemResult{}
}

type CreateItemArgs struct {
	Req *content.CreateItemRequest
}

func (p *CreateItemArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateItemArgs) Unmarshal(in []byte) error {
	msg := new(content.CreateItemRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateItemArgs_Req_DEFAULT *content.CreateItemRequest

func (p *CreateItemArgs) GetReq() *content.CreateItemRequest {
	if !p.IsSetReq() {
		return CreateItemArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateItemArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateItemResult struct {
	Success *content.CreateItemResponse
}

var CreateItemResult_Success_DEFAULT *content.CreateItemResponse

func (p *CreateItemResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateItemResult) Unmarshal(in []byte) error {
	msg := new(content.CreateItemResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateItemResult) GetSuccess() *content.CreateItemResponse {
	if !p.IsSetSuccess() {
		return CreateItemResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.CreateItemResponse)
}

func (p *CreateItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateItemResult) GetResult() interface{} {
	return p.Success
}

func getItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetItemRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetItem(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetItemArgs:
		success, err := handler.(content.ContentService).GetItem(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetItemResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetItemArgs() interface{} {
	return &GetItemArgs{}
}

func newGetItemResult() interface{} {
	return &GetItemResult{}
}

type GetItemArgs struct {
	Req *content.GetItemRequest
}

func (p *GetItemArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetItemArgs) Unmarshal(in []byte) error {
	msg := new(content.GetItemRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetItemArgs_Req_DEFAULT *content.GetItemRequest

func (p *GetItemArgs) GetReq() *content.GetItemRequest {
	if !p.IsSetReq() {
		return GetItemArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetItemArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetItemResult struct {
	Success *content.GetItemResponse
}

var GetItemResult_Success_DEFAULT *content.GetItemResponse

func (p *GetItemResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetItemResult) Unmarshal(in []byte) error {
	msg := new(content.GetItemResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetItemResult) GetSuccess() *content.GetItemResponse {
	if !p.IsSetSuccess() {
		return GetItemResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetItemResponse)
}

func (p *GetItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetItemResult) GetResult() interface{} {
	return p.Success
}

func updateItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.UpdateItemRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).UpdateItem(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateItemArgs:
		success, err := handler.(content.ContentService).UpdateItem(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateItemResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateItemArgs() interface{} {
	return &UpdateItemArgs{}
}

func newUpdateItemResult() interface{} {
	return &UpdateItemResult{}
}

type UpdateItemArgs struct {
	Req *content.UpdateItemRequest
}

func (p *UpdateItemArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateItemArgs) Unmarshal(in []byte) error {
	msg := new(content.UpdateItemRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateItemArgs_Req_DEFAULT *content.UpdateItemRequest

func (p *UpdateItemArgs) GetReq() *content.UpdateItemRequest {
	if !p.IsSetReq() {
		return UpdateItemArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateItemArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateItemResult struct {
	Success *content.UpdateItemResponse
}

var UpdateItemResult_Success_DEFAULT *content.UpdateItemResponse

func (p *UpdateItemResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateItemResult) Unmarshal(in []byte) error {
	msg := new(content.UpdateItemResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateItemResult) GetSuccess() *content.UpdateItemResponse {
	if !p.IsSetSuccess() {
		return UpdateItemResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.UpdateItemResponse)
}

func (p *UpdateItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateItemResult) GetResult() interface{} {
	return p.Success
}

func deleteItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.DeleteItemRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).DeleteItem(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteItemArgs:
		success, err := handler.(content.ContentService).DeleteItem(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteItemResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteItemArgs() interface{} {
	return &DeleteItemArgs{}
}

func newDeleteItemResult() interface{} {
	return &DeleteItemResult{}
}

type DeleteItemArgs struct {
	Req *content.DeleteItemRequest
}

func (p *DeleteItemArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteItemArgs) Unmarshal(in []byte) error {
	msg := new(content.DeleteItemRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteItemArgs_Req_DEFAULT *content.DeleteItemRequest

func (p *DeleteItemArgs) GetReq() *content.DeleteItemRequest {
	if !p.IsSetReq() {
		return DeleteItemArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteItemArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteItemResult struct {
	Success *content.DeleteItemResponse
}

var DeleteItemResult_Success_DEFAULT *content.DeleteItemResponse

func (p *DeleteItemResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteItemResult) Unmarshal(in []byte) error {
	msg := new(content.DeleteItemResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteItemResult) GetSuccess() *content.DeleteItemResponse {
	if !p.IsSetSuccess() {
		return DeleteItemResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.DeleteItemResponse)
}

func (p *DeleteItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteItemResult) GetResult() interface{} {
	return p.Success
}

func getItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetItemsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetItems(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetItemsArgs:
		success, err := handler.(content.ContentService).GetItems(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetItemsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetItemsArgs() interface{} {
	return &GetItemsArgs{}
}

func newGetItemsResult() interface{} {
	return &GetItemsResult{}
}

type GetItemsArgs struct {
	Req *content.GetItemsRequest
}

func (p *GetItemsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetItemsArgs) Unmarshal(in []byte) error {
	msg := new(content.GetItemsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetItemsArgs_Req_DEFAULT *content.GetItemsRequest

func (p *GetItemsArgs) GetReq() *content.GetItemsRequest {
	if !p.IsSetReq() {
		return GetItemsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetItemsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetItemsResult struct {
	Success *content.GetItemsResponse
}

var GetItemsResult_Success_DEFAULT *content.GetItemsResponse

func (p *GetItemsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetItemsResult) Unmarshal(in []byte) error {
	msg := new(content.GetItemsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetItemsResult) GetSuccess() *content.GetItemsResponse {
	if !p.IsSetSuccess() {
		return GetItemsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetItemsResponse)
}

func (p *GetItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetItemsResult) GetResult() interface{} {
	return p.Success
}

func batchDeleteItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.BatchDeleteItemsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).BatchDeleteItems(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchDeleteItemsArgs:
		success, err := handler.(content.ContentService).BatchDeleteItems(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchDeleteItemsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchDeleteItemsArgs() interface{} {
	return &BatchDeleteItemsArgs{}
}

func newBatchDeleteItemsResult() interface{} {
	return &BatchDeleteItemsResult{}
}

type BatchDeleteItemsArgs struct {
	Req *content.BatchDeleteItemsRequest
}

func (p *BatchDeleteItemsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchDeleteItemsArgs) Unmarshal(in []byte) error {
	msg := new(content.BatchDeleteItemsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchDeleteItemsArgs_Req_DEFAULT *content.BatchDeleteItemsRequest

func (p *BatchDeleteItemsArgs) GetReq() *content.BatchDeleteItemsRequest {
	if !p.IsSetReq() {
		return BatchDeleteItemsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchDeleteItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchDeleteItemsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchDeleteItemsResult struct {
	Success *content.BatchDeleteItemsResponse
}

var BatchDeleteItemsResult_Success_DEFAULT *content.BatchDeleteItemsResponse

func (p *BatchDeleteItemsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchDeleteItemsResult) Unmarshal(in []byte) error {
	msg := new(content.BatchDeleteItemsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchDeleteItemsResult) GetSuccess() *content.BatchDeleteItemsResponse {
	if !p.IsSetSuccess() {
		return BatchDeleteItemsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchDeleteItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.BatchDeleteItemsResponse)
}

func (p *BatchDeleteItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchDeleteItemsResult) GetResult() interface{} {
	return p.Success
}

func getItemsByTagsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetItemsByTagsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetItemsByTags(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetItemsByTagsArgs:
		success, err := handler.(content.ContentService).GetItemsByTags(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetItemsByTagsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetItemsByTagsArgs() interface{} {
	return &GetItemsByTagsArgs{}
}

func newGetItemsByTagsResult() interface{} {
	return &GetItemsByTagsResult{}
}

type GetItemsByTagsArgs struct {
	Req *content.GetItemsByTagsRequest
}

func (p *GetItemsByTagsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetItemsByTagsArgs) Unmarshal(in []byte) error {
	msg := new(content.GetItemsByTagsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetItemsByTagsArgs_Req_DEFAULT *content.GetItemsByTagsRequest

func (p *GetItemsByTagsArgs) GetReq() *content.GetItemsByTagsRequest {
	if !p.IsSetReq() {
		return GetItemsByTagsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetItemsByTagsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetItemsByTagsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetItemsByTagsResult struct {
	Success *content.GetItemsByTagsResponse
}

var GetItemsByTagsResult_Success_DEFAULT *content.GetItemsByTagsResponse

func (p *GetItemsByTagsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetItemsByTagsResult) Unmarshal(in []byte) error {
	msg := new(content.GetItemsByTagsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetItemsByTagsResult) GetSuccess() *content.GetItemsByTagsResponse {
	if !p.IsSetSuccess() {
		return GetItemsByTagsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetItemsByTagsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetItemsByTagsResponse)
}

func (p *GetItemsByTagsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetItemsByTagsResult) GetResult() interface{} {
	return p.Success
}

func extractMetadataHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.ExtractMetadataRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).ExtractMetadata(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ExtractMetadataArgs:
		success, err := handler.(content.ContentService).ExtractMetadata(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ExtractMetadataResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newExtractMetadataArgs() interface{} {
	return &ExtractMetadataArgs{}
}

func newExtractMetadataResult() interface{} {
	return &ExtractMetadataResult{}
}

type ExtractMetadataArgs struct {
	Req *content.ExtractMetadataRequest
}

func (p *ExtractMetadataArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ExtractMetadataArgs) Unmarshal(in []byte) error {
	msg := new(content.ExtractMetadataRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ExtractMetadataArgs_Req_DEFAULT *content.ExtractMetadataRequest

func (p *ExtractMetadataArgs) GetReq() *content.ExtractMetadataRequest {
	if !p.IsSetReq() {
		return ExtractMetadataArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ExtractMetadataArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ExtractMetadataArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ExtractMetadataResult struct {
	Success *content.ExtractMetadataResponse
}

var ExtractMetadataResult_Success_DEFAULT *content.ExtractMetadataResponse

func (p *ExtractMetadataResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ExtractMetadataResult) Unmarshal(in []byte) error {
	msg := new(content.ExtractMetadataResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ExtractMetadataResult) GetSuccess() *content.ExtractMetadataResponse {
	if !p.IsSetSuccess() {
		return ExtractMetadataResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ExtractMetadataResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.ExtractMetadataResponse)
}

func (p *ExtractMetadataResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ExtractMetadataResult) GetResult() interface{} {
	return p.Success
}

func getRecentItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetRecentItemsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetRecentItems(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetRecentItemsArgs:
		success, err := handler.(content.ContentService).GetRecentItems(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetRecentItemsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetRecentItemsArgs() interface{} {
	return &GetRecentItemsArgs{}
}

func newGetRecentItemsResult() interface{} {
	return &GetRecentItemsResult{}
}

type GetRecentItemsArgs struct {
	Req *content.GetRecentItemsRequest
}

func (p *GetRecentItemsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetRecentItemsArgs) Unmarshal(in []byte) error {
	msg := new(content.GetRecentItemsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetRecentItemsArgs_Req_DEFAULT *content.GetRecentItemsRequest

func (p *GetRecentItemsArgs) GetReq() *content.GetRecentItemsRequest {
	if !p.IsSetReq() {
		return GetRecentItemsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetRecentItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetRecentItemsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetRecentItemsResult struct {
	Success *content.GetRecentItemsResponse
}

var GetRecentItemsResult_Success_DEFAULT *content.GetRecentItemsResponse

func (p *GetRecentItemsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetRecentItemsResult) Unmarshal(in []byte) error {
	msg := new(content.GetRecentItemsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetRecentItemsResult) GetSuccess() *content.GetRecentItemsResponse {
	if !p.IsSetSuccess() {
		return GetRecentItemsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetRecentItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetRecentItemsResponse)
}

func (p *GetRecentItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetRecentItemsResult) GetResult() interface{} {
	return p.Success
}

func batchUpdateItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.BatchUpdateItemsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).BatchUpdateItems(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchUpdateItemsArgs:
		success, err := handler.(content.ContentService).BatchUpdateItems(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchUpdateItemsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchUpdateItemsArgs() interface{} {
	return &BatchUpdateItemsArgs{}
}

func newBatchUpdateItemsResult() interface{} {
	return &BatchUpdateItemsResult{}
}

type BatchUpdateItemsArgs struct {
	Req *content.BatchUpdateItemsRequest
}

func (p *BatchUpdateItemsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchUpdateItemsArgs) Unmarshal(in []byte) error {
	msg := new(content.BatchUpdateItemsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchUpdateItemsArgs_Req_DEFAULT *content.BatchUpdateItemsRequest

func (p *BatchUpdateItemsArgs) GetReq() *content.BatchUpdateItemsRequest {
	if !p.IsSetReq() {
		return BatchUpdateItemsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchUpdateItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchUpdateItemsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchUpdateItemsResult struct {
	Success *content.BatchUpdateItemsResponse
}

var BatchUpdateItemsResult_Success_DEFAULT *content.BatchUpdateItemsResponse

func (p *BatchUpdateItemsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchUpdateItemsResult) Unmarshal(in []byte) error {
	msg := new(content.BatchUpdateItemsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchUpdateItemsResult) GetSuccess() *content.BatchUpdateItemsResponse {
	if !p.IsSetSuccess() {
		return BatchUpdateItemsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchUpdateItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.BatchUpdateItemsResponse)
}

func (p *BatchUpdateItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchUpdateItemsResult) GetResult() interface{} {
	return p.Success
}

func importFromFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.ImportFromFileRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).ImportFromFile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ImportFromFileArgs:
		success, err := handler.(content.ContentService).ImportFromFile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ImportFromFileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newImportFromFileArgs() interface{} {
	return &ImportFromFileArgs{}
}

func newImportFromFileResult() interface{} {
	return &ImportFromFileResult{}
}

type ImportFromFileArgs struct {
	Req *content.ImportFromFileRequest
}

func (p *ImportFromFileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ImportFromFileArgs) Unmarshal(in []byte) error {
	msg := new(content.ImportFromFileRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ImportFromFileArgs_Req_DEFAULT *content.ImportFromFileRequest

func (p *ImportFromFileArgs) GetReq() *content.ImportFromFileRequest {
	if !p.IsSetReq() {
		return ImportFromFileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ImportFromFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ImportFromFileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ImportFromFileResult struct {
	Success *content.ImportFromFileResponse
}

var ImportFromFileResult_Success_DEFAULT *content.ImportFromFileResponse

func (p *ImportFromFileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ImportFromFileResult) Unmarshal(in []byte) error {
	msg := new(content.ImportFromFileResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ImportFromFileResult) GetSuccess() *content.ImportFromFileResponse {
	if !p.IsSetSuccess() {
		return ImportFromFileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ImportFromFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.ImportFromFileResponse)
}

func (p *ImportFromFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ImportFromFileResult) GetResult() interface{} {
	return p.Success
}

func exportToFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.ExportToFileRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).ExportToFile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ExportToFileArgs:
		success, err := handler.(content.ContentService).ExportToFile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ExportToFileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newExportToFileArgs() interface{} {
	return &ExportToFileArgs{}
}

func newExportToFileResult() interface{} {
	return &ExportToFileResult{}
}

type ExportToFileArgs struct {
	Req *content.ExportToFileRequest
}

func (p *ExportToFileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ExportToFileArgs) Unmarshal(in []byte) error {
	msg := new(content.ExportToFileRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ExportToFileArgs_Req_DEFAULT *content.ExportToFileRequest

func (p *ExportToFileArgs) GetReq() *content.ExportToFileRequest {
	if !p.IsSetReq() {
		return ExportToFileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ExportToFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ExportToFileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ExportToFileResult struct {
	Success *content.ExportToFileResponse
}

var ExportToFileResult_Success_DEFAULT *content.ExportToFileResponse

func (p *ExportToFileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ExportToFileResult) Unmarshal(in []byte) error {
	msg := new(content.ExportToFileResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ExportToFileResult) GetSuccess() *content.ExportToFileResponse {
	if !p.IsSetSuccess() {
		return ExportToFileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ExportToFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.ExportToFileResponse)
}

func (p *ExportToFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ExportToFileResult) GetResult() interface{} {
	return p.Success
}

func searchItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.SearchItemsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).SearchItems(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchItemsArgs:
		success, err := handler.(content.ContentService).SearchItems(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchItemsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchItemsArgs() interface{} {
	return &SearchItemsArgs{}
}

func newSearchItemsResult() interface{} {
	return &SearchItemsResult{}
}

type SearchItemsArgs struct {
	Req *content.SearchItemsRequest
}

func (p *SearchItemsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchItemsArgs) Unmarshal(in []byte) error {
	msg := new(content.SearchItemsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchItemsArgs_Req_DEFAULT *content.SearchItemsRequest

func (p *SearchItemsArgs) GetReq() *content.SearchItemsRequest {
	if !p.IsSetReq() {
		return SearchItemsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchItemsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchItemsResult struct {
	Success *content.SearchItemsResponse
}

var SearchItemsResult_Success_DEFAULT *content.SearchItemsResponse

func (p *SearchItemsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchItemsResult) Unmarshal(in []byte) error {
	msg := new(content.SearchItemsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchItemsResult) GetSuccess() *content.SearchItemsResponse {
	if !p.IsSetSuccess() {
		return SearchItemsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.SearchItemsResponse)
}

func (p *SearchItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchItemsResult) GetResult() interface{} {
	return p.Success
}

func addItemNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.AddItemNoteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).AddItemNote(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddItemNoteArgs:
		success, err := handler.(content.ContentService).AddItemNote(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddItemNoteResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddItemNoteArgs() interface{} {
	return &AddItemNoteArgs{}
}

func newAddItemNoteResult() interface{} {
	return &AddItemNoteResult{}
}

type AddItemNoteArgs struct {
	Req *content.AddItemNoteRequest
}

func (p *AddItemNoteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddItemNoteArgs) Unmarshal(in []byte) error {
	msg := new(content.AddItemNoteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddItemNoteArgs_Req_DEFAULT *content.AddItemNoteRequest

func (p *AddItemNoteArgs) GetReq() *content.AddItemNoteRequest {
	if !p.IsSetReq() {
		return AddItemNoteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddItemNoteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddItemNoteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddItemNoteResult struct {
	Success *content.AddItemNoteResponse
}

var AddItemNoteResult_Success_DEFAULT *content.AddItemNoteResponse

func (p *AddItemNoteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddItemNoteResult) Unmarshal(in []byte) error {
	msg := new(content.AddItemNoteResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddItemNoteResult) GetSuccess() *content.AddItemNoteResponse {
	if !p.IsSetSuccess() {
		return AddItemNoteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddItemNoteResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.AddItemNoteResponse)
}

func (p *AddItemNoteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddItemNoteResult) GetResult() interface{} {
	return p.Success
}

func updateItemNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.UpdateItemNoteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).UpdateItemNote(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateItemNoteArgs:
		success, err := handler.(content.ContentService).UpdateItemNote(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateItemNoteResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateItemNoteArgs() interface{} {
	return &UpdateItemNoteArgs{}
}

func newUpdateItemNoteResult() interface{} {
	return &UpdateItemNoteResult{}
}

type UpdateItemNoteArgs struct {
	Req *content.UpdateItemNoteRequest
}

func (p *UpdateItemNoteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateItemNoteArgs) Unmarshal(in []byte) error {
	msg := new(content.UpdateItemNoteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateItemNoteArgs_Req_DEFAULT *content.UpdateItemNoteRequest

func (p *UpdateItemNoteArgs) GetReq() *content.UpdateItemNoteRequest {
	if !p.IsSetReq() {
		return UpdateItemNoteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateItemNoteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateItemNoteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateItemNoteResult struct {
	Success *content.UpdateItemNoteResponse
}

var UpdateItemNoteResult_Success_DEFAULT *content.UpdateItemNoteResponse

func (p *UpdateItemNoteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateItemNoteResult) Unmarshal(in []byte) error {
	msg := new(content.UpdateItemNoteResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateItemNoteResult) GetSuccess() *content.UpdateItemNoteResponse {
	if !p.IsSetSuccess() {
		return UpdateItemNoteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateItemNoteResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.UpdateItemNoteResponse)
}

func (p *UpdateItemNoteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateItemNoteResult) GetResult() interface{} {
	return p.Success
}

func getItemNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetItemNoteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetItemNote(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetItemNoteArgs:
		success, err := handler.(content.ContentService).GetItemNote(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetItemNoteResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetItemNoteArgs() interface{} {
	return &GetItemNoteArgs{}
}

func newGetItemNoteResult() interface{} {
	return &GetItemNoteResult{}
}

type GetItemNoteArgs struct {
	Req *content.GetItemNoteRequest
}

func (p *GetItemNoteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetItemNoteArgs) Unmarshal(in []byte) error {
	msg := new(content.GetItemNoteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetItemNoteArgs_Req_DEFAULT *content.GetItemNoteRequest

func (p *GetItemNoteArgs) GetReq() *content.GetItemNoteRequest {
	if !p.IsSetReq() {
		return GetItemNoteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetItemNoteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetItemNoteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetItemNoteResult struct {
	Success *content.GetItemNoteResponse
}

var GetItemNoteResult_Success_DEFAULT *content.GetItemNoteResponse

func (p *GetItemNoteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetItemNoteResult) Unmarshal(in []byte) error {
	msg := new(content.GetItemNoteResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetItemNoteResult) GetSuccess() *content.GetItemNoteResponse {
	if !p.IsSetSuccess() {
		return GetItemNoteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetItemNoteResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetItemNoteResponse)
}

func (p *GetItemNoteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetItemNoteResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateItem(ctx context.Context, Req *content.CreateItemRequest) (r *content.CreateItemResponse, err error) {
	var _args CreateItemArgs
	_args.Req = Req
	var _result CreateItemResult
	if err = p.c.Call(ctx, "CreateItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetItem(ctx context.Context, Req *content.GetItemRequest) (r *content.GetItemResponse, err error) {
	var _args GetItemArgs
	_args.Req = Req
	var _result GetItemResult
	if err = p.c.Call(ctx, "GetItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateItem(ctx context.Context, Req *content.UpdateItemRequest) (r *content.UpdateItemResponse, err error) {
	var _args UpdateItemArgs
	_args.Req = Req
	var _result UpdateItemResult
	if err = p.c.Call(ctx, "UpdateItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteItem(ctx context.Context, Req *content.DeleteItemRequest) (r *content.DeleteItemResponse, err error) {
	var _args DeleteItemArgs
	_args.Req = Req
	var _result DeleteItemResult
	if err = p.c.Call(ctx, "DeleteItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetItems(ctx context.Context, Req *content.GetItemsRequest) (r *content.GetItemsResponse, err error) {
	var _args GetItemsArgs
	_args.Req = Req
	var _result GetItemsResult
	if err = p.c.Call(ctx, "GetItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchDeleteItems(ctx context.Context, Req *content.BatchDeleteItemsRequest) (r *content.BatchDeleteItemsResponse, err error) {
	var _args BatchDeleteItemsArgs
	_args.Req = Req
	var _result BatchDeleteItemsResult
	if err = p.c.Call(ctx, "BatchDeleteItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetItemsByTags(ctx context.Context, Req *content.GetItemsByTagsRequest) (r *content.GetItemsByTagsResponse, err error) {
	var _args GetItemsByTagsArgs
	_args.Req = Req
	var _result GetItemsByTagsResult
	if err = p.c.Call(ctx, "GetItemsByTags", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ExtractMetadata(ctx context.Context, Req *content.ExtractMetadataRequest) (r *content.ExtractMetadataResponse, err error) {
	var _args ExtractMetadataArgs
	_args.Req = Req
	var _result ExtractMetadataResult
	if err = p.c.Call(ctx, "ExtractMetadata", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRecentItems(ctx context.Context, Req *content.GetRecentItemsRequest) (r *content.GetRecentItemsResponse, err error) {
	var _args GetRecentItemsArgs
	_args.Req = Req
	var _result GetRecentItemsResult
	if err = p.c.Call(ctx, "GetRecentItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchUpdateItems(ctx context.Context, Req *content.BatchUpdateItemsRequest) (r *content.BatchUpdateItemsResponse, err error) {
	var _args BatchUpdateItemsArgs
	_args.Req = Req
	var _result BatchUpdateItemsResult
	if err = p.c.Call(ctx, "BatchUpdateItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ImportFromFile(ctx context.Context, Req *content.ImportFromFileRequest) (r *content.ImportFromFileResponse, err error) {
	var _args ImportFromFileArgs
	_args.Req = Req
	var _result ImportFromFileResult
	if err = p.c.Call(ctx, "ImportFromFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ExportToFile(ctx context.Context, Req *content.ExportToFileRequest) (r *content.ExportToFileResponse, err error) {
	var _args ExportToFileArgs
	_args.Req = Req
	var _result ExportToFileResult
	if err = p.c.Call(ctx, "ExportToFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchItems(ctx context.Context, Req *content.SearchItemsRequest) (r *content.SearchItemsResponse, err error) {
	var _args SearchItemsArgs
	_args.Req = Req
	var _result SearchItemsResult
	if err = p.c.Call(ctx, "SearchItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddItemNote(ctx context.Context, Req *content.AddItemNoteRequest) (r *content.AddItemNoteResponse, err error) {
	var _args AddItemNoteArgs
	_args.Req = Req
	var _result AddItemNoteResult
	if err = p.c.Call(ctx, "AddItemNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateItemNote(ctx context.Context, Req *content.UpdateItemNoteRequest) (r *content.UpdateItemNoteResponse, err error) {
	var _args UpdateItemNoteArgs
	_args.Req = Req
	var _result UpdateItemNoteResult
	if err = p.c.Call(ctx, "UpdateItemNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetItemNote(ctx context.Context, Req *content.GetItemNoteRequest) (r *content.GetItemNoteResponse, err error) {
	var _args GetItemNoteArgs
	_args.Req = Req
	var _result GetItemNoteResult
	if err = p.c.Call(ctx, "GetItemNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
