// Code generated by Kitex v0.13.1. DO NOT EDIT.

package tagservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	tag "github.com/linkbox-group/linkbox-server/rpc-gen/tag"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateTag(ctx context.Context, Req *tag.CreateTagRequest, callOptions ...callopt.Option) (r *tag.CreateTagResponse, err error)
	GetTag(ctx context.Context, Req *tag.GetTagRequest, callOptions ...callopt.Option) (r *tag.GetTagResponse, err error)
	UpdateTag(ctx context.Context, Req *tag.UpdateTagRequest, callOptions ...callopt.Option) (r *tag.UpdateTagResponse, err error)
	DeleteTag(ctx context.Context, Req *tag.DeleteTagRequest, callOptions ...callopt.Option) (r *tag.DeleteTagResponse, err error)
	GetUserTags(ctx context.Context, Req *tag.GetUserTagsRequest, callOptions ...callopt.Option) (r *tag.GetUserTagsResponse, err error)
	AddTagsToItems(ctx context.Context, Req *tag.AddTagsToItemsRequest, callOptions ...callopt.Option) (r *tag.AddTagsToItemsResponse, err error)
	RemoveTagsFromItems(ctx context.Context, Req *tag.RemoveTagsFromItemsRequest, callOptions ...callopt.Option) (r *tag.RemoveTagsFromItemsResponse, err error)
	GetItemTags(ctx context.Context, Req *tag.GetItemTagsRequest, callOptions ...callopt.Option) (r *tag.GetItemTagsResponse, err error)
	MergeTags(ctx context.Context, Req *tag.MergeTagsRequest, callOptions ...callopt.Option) (r *tag.MergeTagsResponse, err error)
	GetTagStats(ctx context.Context, Req *tag.GetTagStatsRequest, callOptions ...callopt.Option) (r *tag.GetTagStatsResponse, err error)
	GetRelatedTags(ctx context.Context, Req *tag.GetRelatedTagsRequest, callOptions ...callopt.Option) (r *tag.GetRelatedTagsResponse, err error)
	SuggestTags(ctx context.Context, Req *tag.SuggestTagsRequest, callOptions ...callopt.Option) (r *tag.SuggestTagsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTagServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTagServiceClient struct {
	*kClient
}

func (p *kTagServiceClient) CreateTag(ctx context.Context, Req *tag.CreateTagRequest, callOptions ...callopt.Option) (r *tag.CreateTagResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTag(ctx, Req)
}

func (p *kTagServiceClient) GetTag(ctx context.Context, Req *tag.GetTagRequest, callOptions ...callopt.Option) (r *tag.GetTagResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTag(ctx, Req)
}

func (p *kTagServiceClient) UpdateTag(ctx context.Context, Req *tag.UpdateTagRequest, callOptions ...callopt.Option) (r *tag.UpdateTagResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateTag(ctx, Req)
}

func (p *kTagServiceClient) DeleteTag(ctx context.Context, Req *tag.DeleteTagRequest, callOptions ...callopt.Option) (r *tag.DeleteTagResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteTag(ctx, Req)
}

func (p *kTagServiceClient) GetUserTags(ctx context.Context, Req *tag.GetUserTagsRequest, callOptions ...callopt.Option) (r *tag.GetUserTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserTags(ctx, Req)
}

func (p *kTagServiceClient) AddTagsToItems(ctx context.Context, Req *tag.AddTagsToItemsRequest, callOptions ...callopt.Option) (r *tag.AddTagsToItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddTagsToItems(ctx, Req)
}

func (p *kTagServiceClient) RemoveTagsFromItems(ctx context.Context, Req *tag.RemoveTagsFromItemsRequest, callOptions ...callopt.Option) (r *tag.RemoveTagsFromItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveTagsFromItems(ctx, Req)
}

func (p *kTagServiceClient) GetItemTags(ctx context.Context, Req *tag.GetItemTagsRequest, callOptions ...callopt.Option) (r *tag.GetItemTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItemTags(ctx, Req)
}

func (p *kTagServiceClient) MergeTags(ctx context.Context, Req *tag.MergeTagsRequest, callOptions ...callopt.Option) (r *tag.MergeTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MergeTags(ctx, Req)
}

func (p *kTagServiceClient) GetTagStats(ctx context.Context, Req *tag.GetTagStatsRequest, callOptions ...callopt.Option) (r *tag.GetTagStatsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTagStats(ctx, Req)
}

func (p *kTagServiceClient) GetRelatedTags(ctx context.Context, Req *tag.GetRelatedTagsRequest, callOptions ...callopt.Option) (r *tag.GetRelatedTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRelatedTags(ctx, Req)
}

func (p *kTagServiceClient) SuggestTags(ctx context.Context, Req *tag.SuggestTagsRequest, callOptions ...callopt.Option) (r *tag.SuggestTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SuggestTags(ctx, Req)
}
