// Code generated by Kitex v0.13.1. DO NOT EDIT.

package tagservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	tag "github.com/linkbox-group/linkbox-server/rpc-gen/tag"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateTag": kitex.NewMethodInfo(
		createTagHandler,
		newCreateTagArgs,
		newCreateTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetTag": kitex.NewMethodInfo(
		getTagHandler,
		newGetTagArgs,
		newGetTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateTag": kitex.NewMethodInfo(
		updateTagHandler,
		newUpdateTagArgs,
		newUpdateTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteTag": kitex.NewMethodInfo(
		deleteTagHandler,
		newDeleteTagArgs,
		newDeleteTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserTags": kitex.NewMethodInfo(
		getUserTagsHandler,
		newGetUserTagsArgs,
		newGetUserTagsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddTagsToItems": kitex.NewMethodInfo(
		addTagsToItemsHandler,
		newAddTagsToItemsArgs,
		newAddTagsToItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RemoveTagsFromItems": kitex.NewMethodInfo(
		removeTagsFromItemsHandler,
		newRemoveTagsFromItemsArgs,
		newRemoveTagsFromItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetItemTags": kitex.NewMethodInfo(
		getItemTagsHandler,
		newGetItemTagsArgs,
		newGetItemTagsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	tagServiceServiceInfo                = NewServiceInfo()
	tagServiceServiceInfoForClient       = NewServiceInfoForClient()
	tagServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return tagServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return tagServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return tagServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TagService"
	handlerType := (*tag.TagService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "tag",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func createTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tag.CreateTagRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tag.TagService).CreateTag(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateTagArgs:
		success, err := handler.(tag.TagService).CreateTag(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateTagResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateTagArgs() interface{} {
	return &CreateTagArgs{}
}

func newCreateTagResult() interface{} {
	return &CreateTagResult{}
}

type CreateTagArgs struct {
	Req *tag.CreateTagRequest
}

func (p *CreateTagArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateTagArgs) Unmarshal(in []byte) error {
	msg := new(tag.CreateTagRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateTagArgs_Req_DEFAULT *tag.CreateTagRequest

func (p *CreateTagArgs) GetReq() *tag.CreateTagRequest {
	if !p.IsSetReq() {
		return CreateTagArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateTagArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateTagArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateTagResult struct {
	Success *tag.CreateTagResponse
}

var CreateTagResult_Success_DEFAULT *tag.CreateTagResponse

func (p *CreateTagResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateTagResult) Unmarshal(in []byte) error {
	msg := new(tag.CreateTagResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateTagResult) GetSuccess() *tag.CreateTagResponse {
	if !p.IsSetSuccess() {
		return CreateTagResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateTagResult) SetSuccess(x interface{}) {
	p.Success = x.(*tag.CreateTagResponse)
}

func (p *CreateTagResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateTagResult) GetResult() interface{} {
	return p.Success
}

func getTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tag.GetTagRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tag.TagService).GetTag(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetTagArgs:
		success, err := handler.(tag.TagService).GetTag(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetTagResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetTagArgs() interface{} {
	return &GetTagArgs{}
}

func newGetTagResult() interface{} {
	return &GetTagResult{}
}

type GetTagArgs struct {
	Req *tag.GetTagRequest
}

func (p *GetTagArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetTagArgs) Unmarshal(in []byte) error {
	msg := new(tag.GetTagRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetTagArgs_Req_DEFAULT *tag.GetTagRequest

func (p *GetTagArgs) GetReq() *tag.GetTagRequest {
	if !p.IsSetReq() {
		return GetTagArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetTagArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetTagArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetTagResult struct {
	Success *tag.GetTagResponse
}

var GetTagResult_Success_DEFAULT *tag.GetTagResponse

func (p *GetTagResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetTagResult) Unmarshal(in []byte) error {
	msg := new(tag.GetTagResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetTagResult) GetSuccess() *tag.GetTagResponse {
	if !p.IsSetSuccess() {
		return GetTagResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetTagResult) SetSuccess(x interface{}) {
	p.Success = x.(*tag.GetTagResponse)
}

func (p *GetTagResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetTagResult) GetResult() interface{} {
	return p.Success
}

func updateTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tag.UpdateTagRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tag.TagService).UpdateTag(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateTagArgs:
		success, err := handler.(tag.TagService).UpdateTag(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateTagResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateTagArgs() interface{} {
	return &UpdateTagArgs{}
}

func newUpdateTagResult() interface{} {
	return &UpdateTagResult{}
}

type UpdateTagArgs struct {
	Req *tag.UpdateTagRequest
}

func (p *UpdateTagArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateTagArgs) Unmarshal(in []byte) error {
	msg := new(tag.UpdateTagRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateTagArgs_Req_DEFAULT *tag.UpdateTagRequest

func (p *UpdateTagArgs) GetReq() *tag.UpdateTagRequest {
	if !p.IsSetReq() {
		return UpdateTagArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateTagArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateTagArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateTagResult struct {
	Success *tag.UpdateTagResponse
}

var UpdateTagResult_Success_DEFAULT *tag.UpdateTagResponse

func (p *UpdateTagResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateTagResult) Unmarshal(in []byte) error {
	msg := new(tag.UpdateTagResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateTagResult) GetSuccess() *tag.UpdateTagResponse {
	if !p.IsSetSuccess() {
		return UpdateTagResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateTagResult) SetSuccess(x interface{}) {
	p.Success = x.(*tag.UpdateTagResponse)
}

func (p *UpdateTagResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateTagResult) GetResult() interface{} {
	return p.Success
}

func deleteTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tag.DeleteTagRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tag.TagService).DeleteTag(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteTagArgs:
		success, err := handler.(tag.TagService).DeleteTag(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteTagResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteTagArgs() interface{} {
	return &DeleteTagArgs{}
}

func newDeleteTagResult() interface{} {
	return &DeleteTagResult{}
}

type DeleteTagArgs struct {
	Req *tag.DeleteTagRequest
}

func (p *DeleteTagArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteTagArgs) Unmarshal(in []byte) error {
	msg := new(tag.DeleteTagRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteTagArgs_Req_DEFAULT *tag.DeleteTagRequest

func (p *DeleteTagArgs) GetReq() *tag.DeleteTagRequest {
	if !p.IsSetReq() {
		return DeleteTagArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteTagArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteTagArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteTagResult struct {
	Success *tag.DeleteTagResponse
}

var DeleteTagResult_Success_DEFAULT *tag.DeleteTagResponse

func (p *DeleteTagResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteTagResult) Unmarshal(in []byte) error {
	msg := new(tag.DeleteTagResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteTagResult) GetSuccess() *tag.DeleteTagResponse {
	if !p.IsSetSuccess() {
		return DeleteTagResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteTagResult) SetSuccess(x interface{}) {
	p.Success = x.(*tag.DeleteTagResponse)
}

func (p *DeleteTagResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteTagResult) GetResult() interface{} {
	return p.Success
}

func getUserTagsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tag.GetUserTagsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tag.TagService).GetUserTags(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserTagsArgs:
		success, err := handler.(tag.TagService).GetUserTags(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserTagsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserTagsArgs() interface{} {
	return &GetUserTagsArgs{}
}

func newGetUserTagsResult() interface{} {
	return &GetUserTagsResult{}
}

type GetUserTagsArgs struct {
	Req *tag.GetUserTagsRequest
}

func (p *GetUserTagsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserTagsArgs) Unmarshal(in []byte) error {
	msg := new(tag.GetUserTagsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserTagsArgs_Req_DEFAULT *tag.GetUserTagsRequest

func (p *GetUserTagsArgs) GetReq() *tag.GetUserTagsRequest {
	if !p.IsSetReq() {
		return GetUserTagsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserTagsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserTagsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserTagsResult struct {
	Success *tag.GetUserTagsResponse
}

var GetUserTagsResult_Success_DEFAULT *tag.GetUserTagsResponse

func (p *GetUserTagsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserTagsResult) Unmarshal(in []byte) error {
	msg := new(tag.GetUserTagsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserTagsResult) GetSuccess() *tag.GetUserTagsResponse {
	if !p.IsSetSuccess() {
		return GetUserTagsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserTagsResult) SetSuccess(x interface{}) {
	p.Success = x.(*tag.GetUserTagsResponse)
}

func (p *GetUserTagsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserTagsResult) GetResult() interface{} {
	return p.Success
}

func addTagsToItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tag.AddTagsToItemsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tag.TagService).AddTagsToItems(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddTagsToItemsArgs:
		success, err := handler.(tag.TagService).AddTagsToItems(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddTagsToItemsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddTagsToItemsArgs() interface{} {
	return &AddTagsToItemsArgs{}
}

func newAddTagsToItemsResult() interface{} {
	return &AddTagsToItemsResult{}
}

type AddTagsToItemsArgs struct {
	Req *tag.AddTagsToItemsRequest
}

func (p *AddTagsToItemsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddTagsToItemsArgs) Unmarshal(in []byte) error {
	msg := new(tag.AddTagsToItemsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddTagsToItemsArgs_Req_DEFAULT *tag.AddTagsToItemsRequest

func (p *AddTagsToItemsArgs) GetReq() *tag.AddTagsToItemsRequest {
	if !p.IsSetReq() {
		return AddTagsToItemsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddTagsToItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddTagsToItemsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddTagsToItemsResult struct {
	Success *tag.AddTagsToItemsResponse
}

var AddTagsToItemsResult_Success_DEFAULT *tag.AddTagsToItemsResponse

func (p *AddTagsToItemsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddTagsToItemsResult) Unmarshal(in []byte) error {
	msg := new(tag.AddTagsToItemsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddTagsToItemsResult) GetSuccess() *tag.AddTagsToItemsResponse {
	if !p.IsSetSuccess() {
		return AddTagsToItemsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddTagsToItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*tag.AddTagsToItemsResponse)
}

func (p *AddTagsToItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddTagsToItemsResult) GetResult() interface{} {
	return p.Success
}

func removeTagsFromItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tag.RemoveTagsFromItemsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tag.TagService).RemoveTagsFromItems(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RemoveTagsFromItemsArgs:
		success, err := handler.(tag.TagService).RemoveTagsFromItems(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RemoveTagsFromItemsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRemoveTagsFromItemsArgs() interface{} {
	return &RemoveTagsFromItemsArgs{}
}

func newRemoveTagsFromItemsResult() interface{} {
	return &RemoveTagsFromItemsResult{}
}

type RemoveTagsFromItemsArgs struct {
	Req *tag.RemoveTagsFromItemsRequest
}

func (p *RemoveTagsFromItemsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RemoveTagsFromItemsArgs) Unmarshal(in []byte) error {
	msg := new(tag.RemoveTagsFromItemsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RemoveTagsFromItemsArgs_Req_DEFAULT *tag.RemoveTagsFromItemsRequest

func (p *RemoveTagsFromItemsArgs) GetReq() *tag.RemoveTagsFromItemsRequest {
	if !p.IsSetReq() {
		return RemoveTagsFromItemsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RemoveTagsFromItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RemoveTagsFromItemsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RemoveTagsFromItemsResult struct {
	Success *tag.RemoveTagsFromItemsResponse
}

var RemoveTagsFromItemsResult_Success_DEFAULT *tag.RemoveTagsFromItemsResponse

func (p *RemoveTagsFromItemsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RemoveTagsFromItemsResult) Unmarshal(in []byte) error {
	msg := new(tag.RemoveTagsFromItemsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RemoveTagsFromItemsResult) GetSuccess() *tag.RemoveTagsFromItemsResponse {
	if !p.IsSetSuccess() {
		return RemoveTagsFromItemsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RemoveTagsFromItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*tag.RemoveTagsFromItemsResponse)
}

func (p *RemoveTagsFromItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RemoveTagsFromItemsResult) GetResult() interface{} {
	return p.Success
}

func getItemTagsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(tag.GetItemTagsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(tag.TagService).GetItemTags(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetItemTagsArgs:
		success, err := handler.(tag.TagService).GetItemTags(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetItemTagsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetItemTagsArgs() interface{} {
	return &GetItemTagsArgs{}
}

func newGetItemTagsResult() interface{} {
	return &GetItemTagsResult{}
}

type GetItemTagsArgs struct {
	Req *tag.GetItemTagsRequest
}

func (p *GetItemTagsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetItemTagsArgs) Unmarshal(in []byte) error {
	msg := new(tag.GetItemTagsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetItemTagsArgs_Req_DEFAULT *tag.GetItemTagsRequest

func (p *GetItemTagsArgs) GetReq() *tag.GetItemTagsRequest {
	if !p.IsSetReq() {
		return GetItemTagsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetItemTagsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetItemTagsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetItemTagsResult struct {
	Success *tag.GetItemTagsResponse
}

var GetItemTagsResult_Success_DEFAULT *tag.GetItemTagsResponse

func (p *GetItemTagsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetItemTagsResult) Unmarshal(in []byte) error {
	msg := new(tag.GetItemTagsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetItemTagsResult) GetSuccess() *tag.GetItemTagsResponse {
	if !p.IsSetSuccess() {
		return GetItemTagsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetItemTagsResult) SetSuccess(x interface{}) {
	p.Success = x.(*tag.GetItemTagsResponse)
}

func (p *GetItemTagsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetItemTagsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateTag(ctx context.Context, Req *tag.CreateTagRequest) (r *tag.CreateTagResponse, err error) {
	var _args CreateTagArgs
	_args.Req = Req
	var _result CreateTagResult
	if err = p.c.Call(ctx, "CreateTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTag(ctx context.Context, Req *tag.GetTagRequest) (r *tag.GetTagResponse, err error) {
	var _args GetTagArgs
	_args.Req = Req
	var _result GetTagResult
	if err = p.c.Call(ctx, "GetTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateTag(ctx context.Context, Req *tag.UpdateTagRequest) (r *tag.UpdateTagResponse, err error) {
	var _args UpdateTagArgs
	_args.Req = Req
	var _result UpdateTagResult
	if err = p.c.Call(ctx, "UpdateTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteTag(ctx context.Context, Req *tag.DeleteTagRequest) (r *tag.DeleteTagResponse, err error) {
	var _args DeleteTagArgs
	_args.Req = Req
	var _result DeleteTagResult
	if err = p.c.Call(ctx, "DeleteTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserTags(ctx context.Context, Req *tag.GetUserTagsRequest) (r *tag.GetUserTagsResponse, err error) {
	var _args GetUserTagsArgs
	_args.Req = Req
	var _result GetUserTagsResult
	if err = p.c.Call(ctx, "GetUserTags", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddTagsToItems(ctx context.Context, Req *tag.AddTagsToItemsRequest) (r *tag.AddTagsToItemsResponse, err error) {
	var _args AddTagsToItemsArgs
	_args.Req = Req
	var _result AddTagsToItemsResult
	if err = p.c.Call(ctx, "AddTagsToItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveTagsFromItems(ctx context.Context, Req *tag.RemoveTagsFromItemsRequest) (r *tag.RemoveTagsFromItemsResponse, err error) {
	var _args RemoveTagsFromItemsArgs
	_args.Req = Req
	var _result RemoveTagsFromItemsResult
	if err = p.c.Call(ctx, "RemoveTagsFromItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetItemTags(ctx context.Context, Req *tag.GetItemTagsRequest) (r *tag.GetItemTagsResponse, err error) {
	var _args GetItemTagsArgs
	_args.Req = Req
	var _result GetItemTagsResult
	if err = p.c.Call(ctx, "GetItemTags", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
