// Code generated by Kitex v0.13.1. DO NOT EDIT.

package organizationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	organization "github.com/linkbox-group/linkbox-server/rpc-gen/organization"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateCollection(ctx context.Context, Req *organization.CreateCollectionRequest, callOptions ...callopt.Option) (r *organization.CreateCollectionResponse, err error)
	GetCollection(ctx context.Context, Req *organization.GetCollectionRequest, callOptions ...callopt.Option) (r *organization.GetCollectionResponse, err error)
	UpdateCollection(ctx context.Context, Req *organization.UpdateCollectionRequest, callOptions ...callopt.Option) (r *organization.UpdateCollectionResponse, err error)
	DeleteCollection(ctx context.Context, Req *organization.DeleteCollectionRequest, callOptions ...callopt.Option) (r *organization.DeleteCollectionResponse, err error)
	GetUserCollections(ctx context.Context, Req *organization.GetUserCollectionsRequest, callOptions ...callopt.Option) (r *organization.GetUserCollectionsResponse, err error)
	MoveCollection(ctx context.Context, Req *organization.MoveCollectionRequest, callOptions ...callopt.Option) (r *organization.MoveCollectionResponse, err error)
	AddItemsToCollection(ctx context.Context, Req *organization.AddItemsToCollectionRequest, callOptions ...callopt.Option) (r *organization.AddItemsToCollectionResponse, err error)
	RemoveItemsFromCollection(ctx context.Context, Req *organization.RemoveItemsFromCollectionRequest, callOptions ...callopt.Option) (r *organization.RemoveItemsFromCollectionResponse, err error)
	GetCollectionItems(ctx context.Context, Req *organization.GetCollectionItemsRequest, callOptions ...callopt.Option) (r *organization.GetCollectionItemsResponse, err error)
	ReorderCollectionItems(ctx context.Context, Req *organization.ReorderCollectionItemsRequest, callOptions ...callopt.Option) (r *organization.ReorderCollectionItemsResponse, err error)
	ReorderCollections(ctx context.Context, Req *organization.ReorderCollectionsRequest, callOptions ...callopt.Option) (r *organization.ReorderCollectionsResponse, err error)
	GetCollectionActivity(ctx context.Context, Req *organization.GetCollectionActivityRequest, callOptions ...callopt.Option) (r *organization.GetCollectionActivityResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrganizationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrganizationServiceClient struct {
	*kClient
}

func (p *kOrganizationServiceClient) CreateCollection(ctx context.Context, Req *organization.CreateCollectionRequest, callOptions ...callopt.Option) (r *organization.CreateCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCollection(ctx, Req)
}

func (p *kOrganizationServiceClient) GetCollection(ctx context.Context, Req *organization.GetCollectionRequest, callOptions ...callopt.Option) (r *organization.GetCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCollection(ctx, Req)
}

func (p *kOrganizationServiceClient) UpdateCollection(ctx context.Context, Req *organization.UpdateCollectionRequest, callOptions ...callopt.Option) (r *organization.UpdateCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCollection(ctx, Req)
}

func (p *kOrganizationServiceClient) DeleteCollection(ctx context.Context, Req *organization.DeleteCollectionRequest, callOptions ...callopt.Option) (r *organization.DeleteCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCollection(ctx, Req)
}

func (p *kOrganizationServiceClient) GetUserCollections(ctx context.Context, Req *organization.GetUserCollectionsRequest, callOptions ...callopt.Option) (r *organization.GetUserCollectionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserCollections(ctx, Req)
}

func (p *kOrganizationServiceClient) MoveCollection(ctx context.Context, Req *organization.MoveCollectionRequest, callOptions ...callopt.Option) (r *organization.MoveCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MoveCollection(ctx, Req)
}

func (p *kOrganizationServiceClient) AddItemsToCollection(ctx context.Context, Req *organization.AddItemsToCollectionRequest, callOptions ...callopt.Option) (r *organization.AddItemsToCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddItemsToCollection(ctx, Req)
}

func (p *kOrganizationServiceClient) RemoveItemsFromCollection(ctx context.Context, Req *organization.RemoveItemsFromCollectionRequest, callOptions ...callopt.Option) (r *organization.RemoveItemsFromCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveItemsFromCollection(ctx, Req)
}

func (p *kOrganizationServiceClient) GetCollectionItems(ctx context.Context, Req *organization.GetCollectionItemsRequest, callOptions ...callopt.Option) (r *organization.GetCollectionItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCollectionItems(ctx, Req)
}

func (p *kOrganizationServiceClient) ReorderCollectionItems(ctx context.Context, Req *organization.ReorderCollectionItemsRequest, callOptions ...callopt.Option) (r *organization.ReorderCollectionItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReorderCollectionItems(ctx, Req)
}

func (p *kOrganizationServiceClient) ReorderCollections(ctx context.Context, Req *organization.ReorderCollectionsRequest, callOptions ...callopt.Option) (r *organization.ReorderCollectionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReorderCollections(ctx, Req)
}

func (p *kOrganizationServiceClient) GetCollectionActivity(ctx context.Context, Req *organization.GetCollectionActivityRequest, callOptions ...callopt.Option) (r *organization.GetCollectionActivityResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCollectionActivity(ctx, Req)
}
