// Code generated by Kitex v0.13.1. DO NOT EDIT.

package organizationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	organization "github.com/linkbox-group/linkbox-server/rpc-gen/organization"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOrganization(ctx context.Context, Req *organization.CreateOrganizationRequest, callOptions ...callopt.Option) (r *organization.CreateOrganizationResponse, err error)
	GetOrganization(ctx context.Context, Req *organization.GetOrganizationRequest, callOptions ...callopt.Option) (r *organization.GetOrganizationResponse, err error)
	UpdateOrganization(ctx context.Context, Req *organization.UpdateOrganizationRequest, callOptions ...callopt.Option) (r *organization.UpdateOrganizationResponse, err error)
	DeleteOrganization(ctx context.Context, Req *organization.DeleteOrganizationRequest, callOptions ...callopt.Option) (r *organization.DeleteOrganizationResponse, err error)
	GetUserOrganizations(ctx context.Context, Req *organization.GetUserOrganizationsRequest, callOptions ...callopt.Option) (r *organization.GetUserOrganizationsResponse, err error)
	MoveOrganization(ctx context.Context, Req *organization.MoveOrganizationRequest, callOptions ...callopt.Option) (r *organization.MoveOrganizationResponse, err error)
	AddItemsToOrganization(ctx context.Context, Req *organization.AddItemsToOrganizationRequest, callOptions ...callopt.Option) (r *organization.AddItemsToOrganizationResponse, err error)
	RemoveItemsFromOrganization(ctx context.Context, Req *organization.RemoveItemsFromOrganizationRequest, callOptions ...callopt.Option) (r *organization.RemoveItemsFromOrganizationResponse, err error)
	ReorderOrganizationItems(ctx context.Context, Req *organization.ReorderOrganizationItemsRequest, callOptions ...callopt.Option) (r *organization.ReorderOrganizationItemsResponse, err error)
	ReorderOrganizations(ctx context.Context, Req *organization.ReorderOrganizationsRequest, callOptions ...callopt.Option) (r *organization.ReorderOrganizationsResponse, err error)
	GetOrganizationActivity(ctx context.Context, Req *organization.GetOrganizationActivityRequest, callOptions ...callopt.Option) (r *organization.GetOrganizationActivityResponse, err error)
	GetOrganizationTree(ctx context.Context, Req *organization.GetOrganizationTreeRequest, callOptions ...callopt.Option) (r *organization.GetOrganizationTreeResponse, err error)
	GetOrganizationChildren(ctx context.Context, Req *organization.GetOrganizationChildrenRequest, callOptions ...callopt.Option) (r *organization.GetOrganizationChildrenResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrganizationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrganizationServiceClient struct {
	*kClient
}

func (p *kOrganizationServiceClient) CreateOrganization(ctx context.Context, Req *organization.CreateOrganizationRequest, callOptions ...callopt.Option) (r *organization.CreateOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrganization(ctx, Req)
}

func (p *kOrganizationServiceClient) GetOrganization(ctx context.Context, Req *organization.GetOrganizationRequest, callOptions ...callopt.Option) (r *organization.GetOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganization(ctx, Req)
}

func (p *kOrganizationServiceClient) UpdateOrganization(ctx context.Context, Req *organization.UpdateOrganizationRequest, callOptions ...callopt.Option) (r *organization.UpdateOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrganization(ctx, Req)
}

func (p *kOrganizationServiceClient) DeleteOrganization(ctx context.Context, Req *organization.DeleteOrganizationRequest, callOptions ...callopt.Option) (r *organization.DeleteOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOrganization(ctx, Req)
}

func (p *kOrganizationServiceClient) GetUserOrganizations(ctx context.Context, Req *organization.GetUserOrganizationsRequest, callOptions ...callopt.Option) (r *organization.GetUserOrganizationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserOrganizations(ctx, Req)
}

func (p *kOrganizationServiceClient) MoveOrganization(ctx context.Context, Req *organization.MoveOrganizationRequest, callOptions ...callopt.Option) (r *organization.MoveOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MoveOrganization(ctx, Req)
}

func (p *kOrganizationServiceClient) AddItemsToOrganization(ctx context.Context, Req *organization.AddItemsToOrganizationRequest, callOptions ...callopt.Option) (r *organization.AddItemsToOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddItemsToOrganization(ctx, Req)
}

func (p *kOrganizationServiceClient) RemoveItemsFromOrganization(ctx context.Context, Req *organization.RemoveItemsFromOrganizationRequest, callOptions ...callopt.Option) (r *organization.RemoveItemsFromOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveItemsFromOrganization(ctx, Req)
}

func (p *kOrganizationServiceClient) ReorderOrganizationItems(ctx context.Context, Req *organization.ReorderOrganizationItemsRequest, callOptions ...callopt.Option) (r *organization.ReorderOrganizationItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReorderOrganizationItems(ctx, Req)
}

func (p *kOrganizationServiceClient) ReorderOrganizations(ctx context.Context, Req *organization.ReorderOrganizationsRequest, callOptions ...callopt.Option) (r *organization.ReorderOrganizationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReorderOrganizations(ctx, Req)
}

func (p *kOrganizationServiceClient) GetOrganizationActivity(ctx context.Context, Req *organization.GetOrganizationActivityRequest, callOptions ...callopt.Option) (r *organization.GetOrganizationActivityResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganizationActivity(ctx, Req)
}

func (p *kOrganizationServiceClient) GetOrganizationTree(ctx context.Context, Req *organization.GetOrganizationTreeRequest, callOptions ...callopt.Option) (r *organization.GetOrganizationTreeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganizationTree(ctx, Req)
}

func (p *kOrganizationServiceClient) GetOrganizationChildren(ctx context.Context, Req *organization.GetOrganizationChildrenRequest, callOptions ...callopt.Option) (r *organization.GetOrganizationChildrenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganizationChildren(ctx, Req)
}
