// Code generated by Kitex v0.13.1. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	user "github.com/linkbox-group/linkbox-server/rpc-gen/user"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newRegisterArgs,
		newRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newLoginArgs,
		newLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"OAuthLogin": kitex.NewMethodInfo(
		oAuthLoginHandler,
		newOAuthLoginArgs,
		newOAuthLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserProfile": kitex.NewMethodInfo(
		getUserProfileHandler,
		newGetUserProfileArgs,
		newGetUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateUserProfile": kitex.NewMethodInfo(
		updateUserProfileHandler,
		newUpdateUserProfileArgs,
		newUpdateUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ChangePassword": kitex.NewMethodInfo(
		changePasswordHandler,
		newChangePasswordArgs,
		newChangePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ForgotPassword": kitex.NewMethodInfo(
		forgotPasswordHandler,
		newForgotPasswordArgs,
		newForgotPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ResetPassword": kitex.NewMethodInfo(
		resetPasswordHandler,
		newResetPasswordArgs,
		newResetPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteAccount": kitex.NewMethodInfo(
		deleteAccountHandler,
		newDeleteAccountArgs,
		newDeleteAccountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListUsers": kitex.NewMethodInfo(
		listUsersHandler,
		newListUsersArgs,
		newListUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newLogoutArgs,
		newLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newRefreshTokenArgs,
		newRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserSubscription": kitex.NewMethodInfo(
		getUserSubscriptionHandler,
		newGetUserSubscriptionArgs,
		newGetUserSubscriptionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateUserSubscription": kitex.NewMethodInfo(
		updateUserSubscriptionHandler,
		newUpdateUserSubscriptionArgs,
		newUpdateUserSubscriptionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.RegisterRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).Register(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RegisterArgs:
		success, err := handler.(user.UserService).Register(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RegisterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRegisterArgs() interface{} {
	return &RegisterArgs{}
}

func newRegisterResult() interface{} {
	return &RegisterResult{}
}

type RegisterArgs struct {
	Req *user.RegisterRequest
}

func (p *RegisterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RegisterArgs) Unmarshal(in []byte) error {
	msg := new(user.RegisterRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RegisterArgs_Req_DEFAULT *user.RegisterRequest

func (p *RegisterArgs) GetReq() *user.RegisterRequest {
	if !p.IsSetReq() {
		return RegisterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RegisterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RegisterResult struct {
	Success *user.RegisterResponse
}

var RegisterResult_Success_DEFAULT *user.RegisterResponse

func (p *RegisterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RegisterResult) Unmarshal(in []byte) error {
	msg := new(user.RegisterResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RegisterResult) GetSuccess() *user.RegisterResponse {
	if !p.IsSetSuccess() {
		return RegisterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.RegisterResponse)
}

func (p *RegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RegisterResult) GetResult() interface{} {
	return p.Success
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.LoginRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).Login(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LoginArgs:
		success, err := handler.(user.UserService).Login(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLoginArgs() interface{} {
	return &LoginArgs{}
}

func newLoginResult() interface{} {
	return &LoginResult{}
}

type LoginArgs struct {
	Req *user.LoginRequest
}

func (p *LoginArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoginArgs) Unmarshal(in []byte) error {
	msg := new(user.LoginRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginArgs_Req_DEFAULT *user.LoginRequest

func (p *LoginArgs) GetReq() *user.LoginRequest {
	if !p.IsSetReq() {
		return LoginArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoginResult struct {
	Success *user.LoginResponse
}

var LoginResult_Success_DEFAULT *user.LoginResponse

func (p *LoginResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoginResult) Unmarshal(in []byte) error {
	msg := new(user.LoginResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginResult) GetSuccess() *user.LoginResponse {
	if !p.IsSetSuccess() {
		return LoginResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.LoginResponse)
}

func (p *LoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginResult) GetResult() interface{} {
	return p.Success
}

func oAuthLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.OAuthLoginRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).OAuthLogin(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *OAuthLoginArgs:
		success, err := handler.(user.UserService).OAuthLogin(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*OAuthLoginResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newOAuthLoginArgs() interface{} {
	return &OAuthLoginArgs{}
}

func newOAuthLoginResult() interface{} {
	return &OAuthLoginResult{}
}

type OAuthLoginArgs struct {
	Req *user.OAuthLoginRequest
}

func (p *OAuthLoginArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *OAuthLoginArgs) Unmarshal(in []byte) error {
	msg := new(user.OAuthLoginRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var OAuthLoginArgs_Req_DEFAULT *user.OAuthLoginRequest

func (p *OAuthLoginArgs) GetReq() *user.OAuthLoginRequest {
	if !p.IsSetReq() {
		return OAuthLoginArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *OAuthLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OAuthLoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type OAuthLoginResult struct {
	Success *user.LoginResponse
}

var OAuthLoginResult_Success_DEFAULT *user.LoginResponse

func (p *OAuthLoginResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *OAuthLoginResult) Unmarshal(in []byte) error {
	msg := new(user.LoginResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *OAuthLoginResult) GetSuccess() *user.LoginResponse {
	if !p.IsSetSuccess() {
		return OAuthLoginResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OAuthLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.LoginResponse)
}

func (p *OAuthLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OAuthLoginResult) GetResult() interface{} {
	return p.Success
}

func getUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.UserIdRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).GetUserProfile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserProfileArgs:
		success, err := handler.(user.UserService).GetUserProfile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserProfileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserProfileArgs() interface{} {
	return &GetUserProfileArgs{}
}

func newGetUserProfileResult() interface{} {
	return &GetUserProfileResult{}
}

type GetUserProfileArgs struct {
	Req *user.UserIdRequest
}

func (p *GetUserProfileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserProfileArgs) Unmarshal(in []byte) error {
	msg := new(user.UserIdRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserProfileArgs_Req_DEFAULT *user.UserIdRequest

func (p *GetUserProfileArgs) GetReq() *user.UserIdRequest {
	if !p.IsSetReq() {
		return GetUserProfileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserProfileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserProfileResult struct {
	Success *user.GetUserProfileResponse
}

var GetUserProfileResult_Success_DEFAULT *user.GetUserProfileResponse

func (p *GetUserProfileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserProfileResult) Unmarshal(in []byte) error {
	msg := new(user.GetUserProfileResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserProfileResult) GetSuccess() *user.GetUserProfileResponse {
	if !p.IsSetSuccess() {
		return GetUserProfileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.GetUserProfileResponse)
}

func (p *GetUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserProfileResult) GetResult() interface{} {
	return p.Success
}

func updateUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.UpdateUserProfileRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).UpdateUserProfile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateUserProfileArgs:
		success, err := handler.(user.UserService).UpdateUserProfile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateUserProfileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateUserProfileArgs() interface{} {
	return &UpdateUserProfileArgs{}
}

func newUpdateUserProfileResult() interface{} {
	return &UpdateUserProfileResult{}
}

type UpdateUserProfileArgs struct {
	Req *user.UpdateUserProfileRequest
}

func (p *UpdateUserProfileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateUserProfileArgs) Unmarshal(in []byte) error {
	msg := new(user.UpdateUserProfileRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateUserProfileArgs_Req_DEFAULT *user.UpdateUserProfileRequest

func (p *UpdateUserProfileArgs) GetReq() *user.UpdateUserProfileRequest {
	if !p.IsSetReq() {
		return UpdateUserProfileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateUserProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateUserProfileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateUserProfileResult struct {
	Success *user.UpdateUserProfileResponse
}

var UpdateUserProfileResult_Success_DEFAULT *user.UpdateUserProfileResponse

func (p *UpdateUserProfileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateUserProfileResult) Unmarshal(in []byte) error {
	msg := new(user.UpdateUserProfileResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateUserProfileResult) GetSuccess() *user.UpdateUserProfileResponse {
	if !p.IsSetSuccess() {
		return UpdateUserProfileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.UpdateUserProfileResponse)
}

func (p *UpdateUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateUserProfileResult) GetResult() interface{} {
	return p.Success
}

func changePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.ChangePasswordRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).ChangePassword(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ChangePasswordArgs:
		success, err := handler.(user.UserService).ChangePassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ChangePasswordResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newChangePasswordArgs() interface{} {
	return &ChangePasswordArgs{}
}

func newChangePasswordResult() interface{} {
	return &ChangePasswordResult{}
}

type ChangePasswordArgs struct {
	Req *user.ChangePasswordRequest
}

func (p *ChangePasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ChangePasswordArgs) Unmarshal(in []byte) error {
	msg := new(user.ChangePasswordRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ChangePasswordArgs_Req_DEFAULT *user.ChangePasswordRequest

func (p *ChangePasswordArgs) GetReq() *user.ChangePasswordRequest {
	if !p.IsSetReq() {
		return ChangePasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ChangePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChangePasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ChangePasswordResult struct {
	Success *user.ChangePasswordResponse
}

var ChangePasswordResult_Success_DEFAULT *user.ChangePasswordResponse

func (p *ChangePasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ChangePasswordResult) Unmarshal(in []byte) error {
	msg := new(user.ChangePasswordResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ChangePasswordResult) GetSuccess() *user.ChangePasswordResponse {
	if !p.IsSetSuccess() {
		return ChangePasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ChangePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.ChangePasswordResponse)
}

func (p *ChangePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChangePasswordResult) GetResult() interface{} {
	return p.Success
}

func forgotPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.ForgotPasswordRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).ForgotPassword(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ForgotPasswordArgs:
		success, err := handler.(user.UserService).ForgotPassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ForgotPasswordResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newForgotPasswordArgs() interface{} {
	return &ForgotPasswordArgs{}
}

func newForgotPasswordResult() interface{} {
	return &ForgotPasswordResult{}
}

type ForgotPasswordArgs struct {
	Req *user.ForgotPasswordRequest
}

func (p *ForgotPasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ForgotPasswordArgs) Unmarshal(in []byte) error {
	msg := new(user.ForgotPasswordRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ForgotPasswordArgs_Req_DEFAULT *user.ForgotPasswordRequest

func (p *ForgotPasswordArgs) GetReq() *user.ForgotPasswordRequest {
	if !p.IsSetReq() {
		return ForgotPasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ForgotPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ForgotPasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ForgotPasswordResult struct {
	Success *user.ForgotPasswordResponse
}

var ForgotPasswordResult_Success_DEFAULT *user.ForgotPasswordResponse

func (p *ForgotPasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ForgotPasswordResult) Unmarshal(in []byte) error {
	msg := new(user.ForgotPasswordResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ForgotPasswordResult) GetSuccess() *user.ForgotPasswordResponse {
	if !p.IsSetSuccess() {
		return ForgotPasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ForgotPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.ForgotPasswordResponse)
}

func (p *ForgotPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ForgotPasswordResult) GetResult() interface{} {
	return p.Success
}

func resetPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.ResetPasswordRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).ResetPassword(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ResetPasswordArgs:
		success, err := handler.(user.UserService).ResetPassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ResetPasswordResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newResetPasswordArgs() interface{} {
	return &ResetPasswordArgs{}
}

func newResetPasswordResult() interface{} {
	return &ResetPasswordResult{}
}

type ResetPasswordArgs struct {
	Req *user.ResetPasswordRequest
}

func (p *ResetPasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ResetPasswordArgs) Unmarshal(in []byte) error {
	msg := new(user.ResetPasswordRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ResetPasswordArgs_Req_DEFAULT *user.ResetPasswordRequest

func (p *ResetPasswordArgs) GetReq() *user.ResetPasswordRequest {
	if !p.IsSetReq() {
		return ResetPasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ResetPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ResetPasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ResetPasswordResult struct {
	Success *user.ResetPasswordResponse
}

var ResetPasswordResult_Success_DEFAULT *user.ResetPasswordResponse

func (p *ResetPasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ResetPasswordResult) Unmarshal(in []byte) error {
	msg := new(user.ResetPasswordResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ResetPasswordResult) GetSuccess() *user.ResetPasswordResponse {
	if !p.IsSetSuccess() {
		return ResetPasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ResetPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.ResetPasswordResponse)
}

func (p *ResetPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ResetPasswordResult) GetResult() interface{} {
	return p.Success
}

func deleteAccountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.DeleteAccountRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).DeleteAccount(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteAccountArgs:
		success, err := handler.(user.UserService).DeleteAccount(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteAccountResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteAccountArgs() interface{} {
	return &DeleteAccountArgs{}
}

func newDeleteAccountResult() interface{} {
	return &DeleteAccountResult{}
}

type DeleteAccountArgs struct {
	Req *user.DeleteAccountRequest
}

func (p *DeleteAccountArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteAccountArgs) Unmarshal(in []byte) error {
	msg := new(user.DeleteAccountRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteAccountArgs_Req_DEFAULT *user.DeleteAccountRequest

func (p *DeleteAccountArgs) GetReq() *user.DeleteAccountRequest {
	if !p.IsSetReq() {
		return DeleteAccountArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteAccountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteAccountArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteAccountResult struct {
	Success *user.DeleteAccountResponse
}

var DeleteAccountResult_Success_DEFAULT *user.DeleteAccountResponse

func (p *DeleteAccountResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteAccountResult) Unmarshal(in []byte) error {
	msg := new(user.DeleteAccountResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteAccountResult) GetSuccess() *user.DeleteAccountResponse {
	if !p.IsSetSuccess() {
		return DeleteAccountResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteAccountResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.DeleteAccountResponse)
}

func (p *DeleteAccountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteAccountResult) GetResult() interface{} {
	return p.Success
}

func listUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.ListUsersRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).ListUsers(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListUsersArgs:
		success, err := handler.(user.UserService).ListUsers(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListUsersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListUsersArgs() interface{} {
	return &ListUsersArgs{}
}

func newListUsersResult() interface{} {
	return &ListUsersResult{}
}

type ListUsersArgs struct {
	Req *user.ListUsersRequest
}

func (p *ListUsersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListUsersArgs) Unmarshal(in []byte) error {
	msg := new(user.ListUsersRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListUsersArgs_Req_DEFAULT *user.ListUsersRequest

func (p *ListUsersArgs) GetReq() *user.ListUsersRequest {
	if !p.IsSetReq() {
		return ListUsersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListUsersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListUsersResult struct {
	Success *user.ListUsersResponse
}

var ListUsersResult_Success_DEFAULT *user.ListUsersResponse

func (p *ListUsersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListUsersResult) Unmarshal(in []byte) error {
	msg := new(user.ListUsersResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListUsersResult) GetSuccess() *user.ListUsersResponse {
	if !p.IsSetSuccess() {
		return ListUsersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.ListUsersResponse)
}

func (p *ListUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListUsersResult) GetResult() interface{} {
	return p.Success
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.LogoutRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).Logout(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LogoutArgs:
		success, err := handler.(user.UserService).Logout(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LogoutResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLogoutArgs() interface{} {
	return &LogoutArgs{}
}

func newLogoutResult() interface{} {
	return &LogoutResult{}
}

type LogoutArgs struct {
	Req *user.LogoutRequest
}

func (p *LogoutArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LogoutArgs) Unmarshal(in []byte) error {
	msg := new(user.LogoutRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LogoutArgs_Req_DEFAULT *user.LogoutRequest

func (p *LogoutArgs) GetReq() *user.LogoutRequest {
	if !p.IsSetReq() {
		return LogoutArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LogoutArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LogoutResult struct {
	Success *user.LogoutResponse
}

var LogoutResult_Success_DEFAULT *user.LogoutResponse

func (p *LogoutResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LogoutResult) Unmarshal(in []byte) error {
	msg := new(user.LogoutResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LogoutResult) GetSuccess() *user.LogoutResponse {
	if !p.IsSetSuccess() {
		return LogoutResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.LogoutResponse)
}

func (p *LogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LogoutResult) GetResult() interface{} {
	return p.Success
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.RefreshTokenRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).RefreshToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RefreshTokenArgs:
		success, err := handler.(user.UserService).RefreshToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RefreshTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRefreshTokenArgs() interface{} {
	return &RefreshTokenArgs{}
}

func newRefreshTokenResult() interface{} {
	return &RefreshTokenResult{}
}

type RefreshTokenArgs struct {
	Req *user.RefreshTokenRequest
}

func (p *RefreshTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RefreshTokenArgs) Unmarshal(in []byte) error {
	msg := new(user.RefreshTokenRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RefreshTokenArgs_Req_DEFAULT *user.RefreshTokenRequest

func (p *RefreshTokenArgs) GetReq() *user.RefreshTokenRequest {
	if !p.IsSetReq() {
		return RefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefreshTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RefreshTokenResult struct {
	Success *user.RefreshTokenResponse
}

var RefreshTokenResult_Success_DEFAULT *user.RefreshTokenResponse

func (p *RefreshTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RefreshTokenResult) Unmarshal(in []byte) error {
	msg := new(user.RefreshTokenResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RefreshTokenResult) GetSuccess() *user.RefreshTokenResponse {
	if !p.IsSetSuccess() {
		return RefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.RefreshTokenResponse)
}

func (p *RefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefreshTokenResult) GetResult() interface{} {
	return p.Success
}

func getUserSubscriptionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.UserIdRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).GetUserSubscription(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserSubscriptionArgs:
		success, err := handler.(user.UserService).GetUserSubscription(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserSubscriptionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserSubscriptionArgs() interface{} {
	return &GetUserSubscriptionArgs{}
}

func newGetUserSubscriptionResult() interface{} {
	return &GetUserSubscriptionResult{}
}

type GetUserSubscriptionArgs struct {
	Req *user.UserIdRequest
}

func (p *GetUserSubscriptionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserSubscriptionArgs) Unmarshal(in []byte) error {
	msg := new(user.UserIdRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserSubscriptionArgs_Req_DEFAULT *user.UserIdRequest

func (p *GetUserSubscriptionArgs) GetReq() *user.UserIdRequest {
	if !p.IsSetReq() {
		return GetUserSubscriptionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserSubscriptionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserSubscriptionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserSubscriptionResult struct {
	Success *user.GetUserSubscriptionResponse
}

var GetUserSubscriptionResult_Success_DEFAULT *user.GetUserSubscriptionResponse

func (p *GetUserSubscriptionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserSubscriptionResult) Unmarshal(in []byte) error {
	msg := new(user.GetUserSubscriptionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserSubscriptionResult) GetSuccess() *user.GetUserSubscriptionResponse {
	if !p.IsSetSuccess() {
		return GetUserSubscriptionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserSubscriptionResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.GetUserSubscriptionResponse)
}

func (p *GetUserSubscriptionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserSubscriptionResult) GetResult() interface{} {
	return p.Success
}

func updateUserSubscriptionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.UpdateUserSubscriptionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).UpdateUserSubscription(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateUserSubscriptionArgs:
		success, err := handler.(user.UserService).UpdateUserSubscription(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateUserSubscriptionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateUserSubscriptionArgs() interface{} {
	return &UpdateUserSubscriptionArgs{}
}

func newUpdateUserSubscriptionResult() interface{} {
	return &UpdateUserSubscriptionResult{}
}

type UpdateUserSubscriptionArgs struct {
	Req *user.UpdateUserSubscriptionRequest
}

func (p *UpdateUserSubscriptionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateUserSubscriptionArgs) Unmarshal(in []byte) error {
	msg := new(user.UpdateUserSubscriptionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateUserSubscriptionArgs_Req_DEFAULT *user.UpdateUserSubscriptionRequest

func (p *UpdateUserSubscriptionArgs) GetReq() *user.UpdateUserSubscriptionRequest {
	if !p.IsSetReq() {
		return UpdateUserSubscriptionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateUserSubscriptionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateUserSubscriptionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateUserSubscriptionResult struct {
	Success *user.UpdateUserSubscriptionResponse
}

var UpdateUserSubscriptionResult_Success_DEFAULT *user.UpdateUserSubscriptionResponse

func (p *UpdateUserSubscriptionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateUserSubscriptionResult) Unmarshal(in []byte) error {
	msg := new(user.UpdateUserSubscriptionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateUserSubscriptionResult) GetSuccess() *user.UpdateUserSubscriptionResponse {
	if !p.IsSetSuccess() {
		return UpdateUserSubscriptionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateUserSubscriptionResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.UpdateUserSubscriptionResponse)
}

func (p *UpdateUserSubscriptionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateUserSubscriptionResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, Req *user.RegisterRequest) (r *user.RegisterResponse, err error) {
	var _args RegisterArgs
	_args.Req = Req
	var _result RegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, Req *user.LoginRequest) (r *user.LoginResponse, err error) {
	var _args LoginArgs
	_args.Req = Req
	var _result LoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OAuthLogin(ctx context.Context, Req *user.OAuthLoginRequest) (r *user.LoginResponse, err error) {
	var _args OAuthLoginArgs
	_args.Req = Req
	var _result OAuthLoginResult
	if err = p.c.Call(ctx, "OAuthLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserProfile(ctx context.Context, Req *user.UserIdRequest) (r *user.GetUserProfileResponse, err error) {
	var _args GetUserProfileArgs
	_args.Req = Req
	var _result GetUserProfileResult
	if err = p.c.Call(ctx, "GetUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserProfile(ctx context.Context, Req *user.UpdateUserProfileRequest) (r *user.UpdateUserProfileResponse, err error) {
	var _args UpdateUserProfileArgs
	_args.Req = Req
	var _result UpdateUserProfileResult
	if err = p.c.Call(ctx, "UpdateUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePassword(ctx context.Context, Req *user.ChangePasswordRequest) (r *user.ChangePasswordResponse, err error) {
	var _args ChangePasswordArgs
	_args.Req = Req
	var _result ChangePasswordResult
	if err = p.c.Call(ctx, "ChangePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ForgotPassword(ctx context.Context, Req *user.ForgotPasswordRequest) (r *user.ForgotPasswordResponse, err error) {
	var _args ForgotPasswordArgs
	_args.Req = Req
	var _result ForgotPasswordResult
	if err = p.c.Call(ctx, "ForgotPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResetPassword(ctx context.Context, Req *user.ResetPasswordRequest) (r *user.ResetPasswordResponse, err error) {
	var _args ResetPasswordArgs
	_args.Req = Req
	var _result ResetPasswordResult
	if err = p.c.Call(ctx, "ResetPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAccount(ctx context.Context, Req *user.DeleteAccountRequest) (r *user.DeleteAccountResponse, err error) {
	var _args DeleteAccountArgs
	_args.Req = Req
	var _result DeleteAccountResult
	if err = p.c.Call(ctx, "DeleteAccount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListUsers(ctx context.Context, Req *user.ListUsersRequest) (r *user.ListUsersResponse, err error) {
	var _args ListUsersArgs
	_args.Req = Req
	var _result ListUsersResult
	if err = p.c.Call(ctx, "ListUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, Req *user.LogoutRequest) (r *user.LogoutResponse, err error) {
	var _args LogoutArgs
	_args.Req = Req
	var _result LogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, Req *user.RefreshTokenRequest) (r *user.RefreshTokenResponse, err error) {
	var _args RefreshTokenArgs
	_args.Req = Req
	var _result RefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserSubscription(ctx context.Context, Req *user.UserIdRequest) (r *user.GetUserSubscriptionResponse, err error) {
	var _args GetUserSubscriptionArgs
	_args.Req = Req
	var _result GetUserSubscriptionResult
	if err = p.c.Call(ctx, "GetUserSubscription", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserSubscription(ctx context.Context, Req *user.UpdateUserSubscriptionRequest) (r *user.UpdateUserSubscriptionResponse, err error) {
	var _args UpdateUserSubscriptionArgs
	_args.Req = Req
	var _result UpdateUserSubscriptionResult
	if err = p.c.Call(ctx, "UpdateUserSubscription", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
