// Code generated by Kitex v0.13.1. DO NOT EDIT.

package search

import (
	"context"
	"github.com/linkbox-group/linkbox-server/rpc-gen/common/error"
	"github.com/linkbox-group/linkbox-server/rpc-gen/common/pagination"
	"github.com/linkbox-group/linkbox-server/rpc-gen/common/types"
	"google.golang.org/protobuf/types/known/timestamppb"
	"strconv"

	"github.com/cloudwego/prutal"
)

// 搜索类型
type SearchType int32

const (
	SearchType_ALL         SearchType = 0
	SearchType_LINKS       SearchType = 1
	SearchType_NOTES       SearchType = 2
	SearchType_COLLECTIONS SearchType = 3
	SearchType_TAGS        SearchType = 4
)

// Enum value maps for SearchType.
var SearchType_name = map[int32]string{
	0: "ALL",
	1: "LINKS",
	2: "NOTES",
	3: "COLLECTIONS",
	4: "TAGS",
}

var SearchType_value = map[string]int32{
	"ALL":         0,
	"LINKS":       1,
	"NOTES":       2,
	"COLLECTIONS": 3,
	"TAGS":        4,
}

func (x SearchType) String() string {
	s, ok := SearchType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 搜索请求
type SearchRequest struct {
	UserId     string                        `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Query      string                        `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	Type       SearchType                    `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Pagination *pagination.PaginationRequest `protobuf:"bytes,4,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *SearchRequest) Reset() { *x = SearchRequest{} }

func (x *SearchRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetType() SearchType {
	if x != nil {
		return x.Type
	}
	return SearchType_ALL
}

func (x *SearchRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 高级搜索请求
type AdvancedSearchRequest struct {
	UserId          string                        `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Query           string                        `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	Type            SearchType                    `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Pagination      *pagination.PaginationRequest `protobuf:"bytes,4,opt,name=pagination" json:"pagination,omitempty"`
	Collections     []string                      `protobuf:"bytes,5,rep,name=collections" json:"collections,omitempty"`
	Tags            []string                      `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
	DateRange       *types.TimeRange              `protobuf:"bytes,7,opt,name=date_range" json:"date_range,omitempty"`
	IncludeArchived bool                          `protobuf:"varint,8,opt,name=include_archived" json:"include_archived,omitempty"`
	FavoritesOnly   bool                          `protobuf:"varint,9,opt,name=favorites_only" json:"favorites_only,omitempty"`
}

func (x *AdvancedSearchRequest) Reset() { *x = AdvancedSearchRequest{} }

func (x *AdvancedSearchRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *AdvancedSearchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AdvancedSearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdvancedSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AdvancedSearchRequest) GetType() SearchType {
	if x != nil {
		return x.Type
	}
	return SearchType_ALL
}

func (x *AdvancedSearchRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *AdvancedSearchRequest) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *AdvancedSearchRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AdvancedSearchRequest) GetDateRange() *types.TimeRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *AdvancedSearchRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *AdvancedSearchRequest) GetFavoritesOnly() bool {
	if x != nil {
		return x.FavoritesOnly
	}
	return false
}

// 搜索响应
type SearchResponse struct {
	// Types that are assignable to Result:
	//
	//	*SearchResponse_Data
	//	*SearchResponse_Error
	Result isSearchResponse_Result `protobuf_oneof:"result"`
}

func (x *SearchResponse) Reset() { *x = SearchResponse{} }

func (x *SearchResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchResponse) GetResult() isSearchResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *SearchResponse) GetData() *SearchResult {
	if p, ok := x.GetResult().(*SearchResponse_Data); ok {
		return p.Data
	}
	return nil
}

func (x *SearchResponse) GetError() *error.Error {
	if p, ok := x.GetResult().(*SearchResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*SearchResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SearchResponse_Data)(nil),
		(*SearchResponse_Error)(nil),
	}
}

type isSearchResponse_Result interface {
	isSearchResponse_Result()
}

type SearchResponse_Data struct {
	Data *SearchResult `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (*SearchResponse_Data) isSearchResponse_Result() {}

type SearchResponse_Error struct {
	Error *error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*SearchResponse_Error) isSearchResponse_Result() {}

// 搜索结果
type SearchResult struct {
	Items          []*SearchItem              `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Pagination     *pagination.PaginationMeta `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
	SuggestedTerms []string                   `protobuf:"bytes,3,rep,name=suggested_terms" json:"suggested_terms,omitempty"`
	SearchTimeMs   int64                      `protobuf:"varint,4,opt,name=search_time_ms" json:"search_time_ms,omitempty"`
}

func (x *SearchResult) Reset() { *x = SearchResult{} }

func (x *SearchResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchResult) GetItems() []*SearchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResult) GetPagination() *pagination.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchResult) GetSuggestedTerms() []string {
	if x != nil {
		return x.SuggestedTerms
	}
	return nil
}

func (x *SearchResult) GetSearchTimeMs() int64 {
	if x != nil {
		return x.SearchTimeMs
	}
	return 0
}

// 搜索项
type SearchItem struct {
	Id             string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"` // "link", "note", "collection", "tag"
	Title          string                 `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Url            string                 `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	ThumbnailUrl   string                 `protobuf:"bytes,6,opt,name=thumbnail_url" json:"thumbnail_url,omitempty"`
	Tags           []string               `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	CollectionIds  []string               `protobuf:"bytes,8,rep,name=collection_ids" json:"collection_ids,omitempty"`
	RelevanceScore float32                `protobuf:"fixed32,9,opt,name=relevance_score" json:"relevance_score,omitempty"`
	MatchedFields  []string               `protobuf:"bytes,10,rep,name=matched_fields" json:"matched_fields,omitempty"`
	Highlights     []*HighlightedText     `protobuf:"bytes,11,rep,name=highlights" json:"highlights,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at" json:"updated_at,omitempty"`
}

func (x *SearchItem) Reset() { *x = SearchItem{} }

func (x *SearchItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SearchItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SearchItem) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *SearchItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchItem) GetCollectionIds() []string {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

func (x *SearchItem) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *SearchItem) GetMatchedFields() []string {
	if x != nil {
		return x.MatchedFields
	}
	return nil
}

func (x *SearchItem) GetHighlights() []*HighlightedText {
	if x != nil {
		return x.Highlights
	}
	return nil
}

func (x *SearchItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SearchItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 高亮文本
type HighlightedText struct {
	Field string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (x *HighlightedText) Reset() { *x = HighlightedText{} }

func (x *HighlightedText) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HighlightedText) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *HighlightedText) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *HighlightedText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// 搜索建议请求
type SearchSuggestionRequest struct {
	UserId       string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	PartialQuery string `protobuf:"bytes,2,opt,name=partial_query" json:"partial_query,omitempty"`
	Limit        int32  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (x *SearchSuggestionRequest) Reset() { *x = SearchSuggestionRequest{} }

func (x *SearchSuggestionRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SearchSuggestionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchSuggestionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchSuggestionRequest) GetPartialQuery() string {
	if x != nil {
		return x.PartialQuery
	}
	return ""
}

func (x *SearchSuggestionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 搜索建议响应
type SearchSuggestionResponse struct {
	// Types that are assignable to Result:
	//
	//	*SearchSuggestionResponse_Suggestions
	//	*SearchSuggestionResponse_Error
	Result isSearchSuggestionResponse_Result `protobuf_oneof:"result"`
}

func (x *SearchSuggestionResponse) Reset() { *x = SearchSuggestionResponse{} }

func (x *SearchSuggestionResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SearchSuggestionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchSuggestionResponse) GetResult() isSearchSuggestionResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *SearchSuggestionResponse) GetSuggestions() *SuggestionResult {
	if p, ok := x.GetResult().(*SearchSuggestionResponse_Suggestions); ok {
		return p.Suggestions
	}
	return nil
}

func (x *SearchSuggestionResponse) GetError() *error.Error {
	if p, ok := x.GetResult().(*SearchSuggestionResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*SearchSuggestionResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SearchSuggestionResponse_Suggestions)(nil),
		(*SearchSuggestionResponse_Error)(nil),
	}
}

type isSearchSuggestionResponse_Result interface {
	isSearchSuggestionResponse_Result()
}

type SearchSuggestionResponse_Suggestions struct {
	Suggestions *SuggestionResult `protobuf:"bytes,1,opt,name=suggestions" json:"suggestions,omitempty"`
}

func (*SearchSuggestionResponse_Suggestions) isSearchSuggestionResponse_Result() {}

type SearchSuggestionResponse_Error struct {
	Error *error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*SearchSuggestionResponse_Error) isSearchSuggestionResponse_Result() {}

// 建议结果
type SuggestionResult struct {
	Terms      []string      `protobuf:"bytes,1,rep,name=terms" json:"terms,omitempty"`
	TopResults []*SearchItem `protobuf:"bytes,2,rep,name=top_results" json:"top_results,omitempty"`
}

func (x *SuggestionResult) Reset() { *x = SuggestionResult{} }

func (x *SuggestionResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SuggestionResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SuggestionResult) GetTerms() []string {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *SuggestionResult) GetTopResults() []*SearchItem {
	if x != nil {
		return x.TopResults
	}
	return nil
}

// 搜索历史请求
type SearchHistoryRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (x *SearchHistoryRequest) Reset() { *x = SearchHistoryRequest{} }

func (x *SearchHistoryRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchHistoryRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 搜索历史响应
type SearchHistoryResponse struct {
	// Types that are assignable to Result:
	//
	//	*SearchHistoryResponse_History
	//	*SearchHistoryResponse_Error
	Result isSearchHistoryResponse_Result `protobuf_oneof:"result"`
}

func (x *SearchHistoryResponse) Reset() { *x = SearchHistoryResponse{} }

func (x *SearchHistoryResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SearchHistoryResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchHistoryResponse) GetResult() isSearchHistoryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *SearchHistoryResponse) GetHistory() *SearchHistoryResult {
	if p, ok := x.GetResult().(*SearchHistoryResponse_History); ok {
		return p.History
	}
	return nil
}

func (x *SearchHistoryResponse) GetError() *error.Error {
	if p, ok := x.GetResult().(*SearchHistoryResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*SearchHistoryResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SearchHistoryResponse_History)(nil),
		(*SearchHistoryResponse_Error)(nil),
	}
}

type isSearchHistoryResponse_Result interface {
	isSearchHistoryResponse_Result()
}

type SearchHistoryResponse_History struct {
	History *SearchHistoryResult `protobuf:"bytes,1,opt,name=history" json:"history,omitempty"`
}

func (*SearchHistoryResponse_History) isSearchHistoryResponse_Result() {}

type SearchHistoryResponse_Error struct {
	Error *error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*SearchHistoryResponse_Error) isSearchHistoryResponse_Result() {}

// 搜索历史结果
type SearchHistoryResult struct {
	Items []*SearchHistoryItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (x *SearchHistoryResult) Reset() { *x = SearchHistoryResult{} }

func (x *SearchHistoryResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchHistoryResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchHistoryResult) GetItems() []*SearchHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 搜索历史项
type SearchHistoryItem struct {
	Id          string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Query       string                 `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	Type        SearchType             `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	ResultCount int32                  `protobuf:"varint,4,opt,name=result_count" json:"result_count,omitempty"`
	SearchedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=searched_at" json:"searched_at,omitempty"`
}

func (x *SearchHistoryItem) Reset() { *x = SearchHistoryItem{} }

func (x *SearchHistoryItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchHistoryItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchHistoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchHistoryItem) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchHistoryItem) GetType() SearchType {
	if x != nil {
		return x.Type
	}
	return SearchType_ALL
}

func (x *SearchHistoryItem) GetResultCount() int32 {
	if x != nil {
		return x.ResultCount
	}
	return 0
}

func (x *SearchHistoryItem) GetSearchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SearchedAt
	}
	return nil
}

// 清除搜索历史请求
type ClearSearchHistoryRequest struct {
	UserId   string  `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	SearchId *string `protobuf:"bytes,2,opt,name=search_id" json:"search_id,omitempty"` // 如果提供，则只清除特定搜索
}

func (x *ClearSearchHistoryRequest) Reset() { *x = ClearSearchHistoryRequest{} }

func (x *ClearSearchHistoryRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ClearSearchHistoryRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClearSearchHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClearSearchHistoryRequest) GetSearchId() string {
	if x != nil && x.SearchId != nil {
		return *x.SearchId
	}
	return ""
}

// 清除搜索历史响应
type ClearSearchHistoryResponse struct {
	// Types that are assignable to Result:
	//
	//	*ClearSearchHistoryResponse_Success
	//	*ClearSearchHistoryResponse_Error
	Result isClearSearchHistoryResponse_Result `protobuf_oneof:"result"`
}

func (x *ClearSearchHistoryResponse) Reset() { *x = ClearSearchHistoryResponse{} }

func (x *ClearSearchHistoryResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ClearSearchHistoryResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClearSearchHistoryResponse) GetResult() isClearSearchHistoryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *ClearSearchHistoryResponse) GetSuccess() bool {
	if p, ok := x.GetResult().(*ClearSearchHistoryResponse_Success); ok {
		return p.Success
	}
	return false
}

func (x *ClearSearchHistoryResponse) GetError() *error.Error {
	if p, ok := x.GetResult().(*ClearSearchHistoryResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*ClearSearchHistoryResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClearSearchHistoryResponse_Success)(nil),
		(*ClearSearchHistoryResponse_Error)(nil),
	}
}

type isClearSearchHistoryResponse_Result interface {
	isClearSearchHistoryResponse_Result()
}

type ClearSearchHistoryResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (*ClearSearchHistoryResponse_Success) isClearSearchHistoryResponse_Result() {}

type ClearSearchHistoryResponse_Error struct {
	Error *error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*ClearSearchHistoryResponse_Error) isClearSearchHistoryResponse_Result() {}

// 保存搜索请求
type SaveSearchRequest struct {
	UserId         string                `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Query          string                `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	Type           SearchType            `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Name           string                `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Description    *string               `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	AdvancedParams *AdvancedSearchParams `protobuf:"bytes,6,opt,name=advanced_params" json:"advanced_params,omitempty"`
}

func (x *SaveSearchRequest) Reset() { *x = SaveSearchRequest{} }

func (x *SaveSearchRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SaveSearchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SaveSearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SaveSearchRequest) GetType() SearchType {
	if x != nil {
		return x.Type
	}
	return SearchType_ALL
}

func (x *SaveSearchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveSearchRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *SaveSearchRequest) GetAdvancedParams() *AdvancedSearchParams {
	if x != nil {
		return x.AdvancedParams
	}
	return nil
}

// 高级搜索参数
type AdvancedSearchParams struct {
	Collections     []string         `protobuf:"bytes,1,rep,name=collections" json:"collections,omitempty"`
	Tags            []string         `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	DateRange       *types.TimeRange `protobuf:"bytes,3,opt,name=date_range" json:"date_range,omitempty"`
	IncludeArchived bool             `protobuf:"varint,4,opt,name=include_archived" json:"include_archived,omitempty"`
	FavoritesOnly   bool             `protobuf:"varint,5,opt,name=favorites_only" json:"favorites_only,omitempty"`
}

func (x *AdvancedSearchParams) Reset() { *x = AdvancedSearchParams{} }

func (x *AdvancedSearchParams) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AdvancedSearchParams) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AdvancedSearchParams) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *AdvancedSearchParams) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AdvancedSearchParams) GetDateRange() *types.TimeRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *AdvancedSearchParams) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *AdvancedSearchParams) GetFavoritesOnly() bool {
	if x != nil {
		return x.FavoritesOnly
	}
	return false
}

// 保存搜索响应
type SaveSearchResponse struct {
	// Types that are assignable to Result:
	//
	//	*SaveSearchResponse_SavedSearch
	//	*SaveSearchResponse_Error
	Result isSaveSearchResponse_Result `protobuf_oneof:"result"`
}

func (x *SaveSearchResponse) Reset() { *x = SaveSearchResponse{} }

func (x *SaveSearchResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SaveSearchResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SaveSearchResponse) GetResult() isSaveSearchResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *SaveSearchResponse) GetSavedSearch() *SavedSearch {
	if p, ok := x.GetResult().(*SaveSearchResponse_SavedSearch); ok {
		return p.SavedSearch
	}
	return nil
}

func (x *SaveSearchResponse) GetError() *error.Error {
	if p, ok := x.GetResult().(*SaveSearchResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*SaveSearchResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SaveSearchResponse_SavedSearch)(nil),
		(*SaveSearchResponse_Error)(nil),
	}
}

type isSaveSearchResponse_Result interface {
	isSaveSearchResponse_Result()
}

type SaveSearchResponse_SavedSearch struct {
	SavedSearch *SavedSearch `protobuf:"bytes,1,opt,name=saved_search" json:"saved_search,omitempty"`
}

func (*SaveSearchResponse_SavedSearch) isSaveSearchResponse_Result() {}

type SaveSearchResponse_Error struct {
	Error *error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*SaveSearchResponse_Error) isSaveSearchResponse_Result() {}

// 保存的搜索
type SavedSearch struct {
	Id             string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Query          string                 `protobuf:"bytes,5,opt,name=query" json:"query,omitempty"`
	Type           SearchType             `protobuf:"varint,6,opt,name=type" json:"type,omitempty"`
	AdvancedParams *AdvancedSearchParams  `protobuf:"bytes,7,opt,name=advanced_params" json:"advanced_params,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at" json:"updated_at,omitempty"`
}

func (x *SavedSearch) Reset() { *x = SavedSearch{} }

func (x *SavedSearch) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SavedSearch) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SavedSearch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SavedSearch) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SavedSearch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SavedSearch) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SavedSearch) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SavedSearch) GetType() SearchType {
	if x != nil {
		return x.Type
	}
	return SearchType_ALL
}

func (x *SavedSearch) GetAdvancedParams() *AdvancedSearchParams {
	if x != nil {
		return x.AdvancedParams
	}
	return nil
}

func (x *SavedSearch) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SavedSearch) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 获取保存的搜索请求
type GetSavedSearchesRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetSavedSearchesRequest) Reset() { *x = GetSavedSearchesRequest{} }

func (x *GetSavedSearchesRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetSavedSearchesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetSavedSearchesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取保存的搜索响应
type GetSavedSearchesResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetSavedSearchesResponse_SavedSearches
	//	*GetSavedSearchesResponse_Error
	Result isGetSavedSearchesResponse_Result `protobuf_oneof:"result"`
}

func (x *GetSavedSearchesResponse) Reset() { *x = GetSavedSearchesResponse{} }

func (x *GetSavedSearchesResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetSavedSearchesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetSavedSearchesResponse) GetResult() isGetSavedSearchesResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetSavedSearchesResponse) GetSavedSearches() *SavedSearchesResult {
	if p, ok := x.GetResult().(*GetSavedSearchesResponse_SavedSearches); ok {
		return p.SavedSearches
	}
	return nil
}

func (x *GetSavedSearchesResponse) GetError() *error.Error {
	if p, ok := x.GetResult().(*GetSavedSearchesResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetSavedSearchesResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetSavedSearchesResponse_SavedSearches)(nil),
		(*GetSavedSearchesResponse_Error)(nil),
	}
}

type isGetSavedSearchesResponse_Result interface {
	isGetSavedSearchesResponse_Result()
}

type GetSavedSearchesResponse_SavedSearches struct {
	SavedSearches *SavedSearchesResult `protobuf:"bytes,1,opt,name=saved_searches" json:"saved_searches,omitempty"`
}

func (*GetSavedSearchesResponse_SavedSearches) isGetSavedSearchesResponse_Result() {}

type GetSavedSearchesResponse_Error struct {
	Error *error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetSavedSearchesResponse_Error) isGetSavedSearchesResponse_Result() {}

// 保存的搜索结果
type SavedSearchesResult struct {
	Searches []*SavedSearch `protobuf:"bytes,1,rep,name=searches" json:"searches,omitempty"`
}

func (x *SavedSearchesResult) Reset() { *x = SavedSearchesResult{} }

func (x *SavedSearchesResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SavedSearchesResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SavedSearchesResult) GetSearches() []*SavedSearch {
	if x != nil {
		return x.Searches
	}
	return nil
}

// 删除保存的搜索请求
type DeleteSavedSearchRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *DeleteSavedSearchRequest) Reset() { *x = DeleteSavedSearchRequest{} }

func (x *DeleteSavedSearchRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeleteSavedSearchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteSavedSearchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteSavedSearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 删除保存的搜索响应
type DeleteSavedSearchResponse struct {
	// Types that are assignable to Result:
	//
	//	*DeleteSavedSearchResponse_Success
	//	*DeleteSavedSearchResponse_Error
	Result isDeleteSavedSearchResponse_Result `protobuf_oneof:"result"`
}

func (x *DeleteSavedSearchResponse) Reset() { *x = DeleteSavedSearchResponse{} }

func (x *DeleteSavedSearchResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeleteSavedSearchResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteSavedSearchResponse) GetResult() isDeleteSavedSearchResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *DeleteSavedSearchResponse) GetSuccess() bool {
	if p, ok := x.GetResult().(*DeleteSavedSearchResponse_Success); ok {
		return p.Success
	}
	return false
}

func (x *DeleteSavedSearchResponse) GetError() *error.Error {
	if p, ok := x.GetResult().(*DeleteSavedSearchResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*DeleteSavedSearchResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteSavedSearchResponse_Success)(nil),
		(*DeleteSavedSearchResponse_Error)(nil),
	}
}

type isDeleteSavedSearchResponse_Result interface {
	isDeleteSavedSearchResponse_Result()
}

type DeleteSavedSearchResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (*DeleteSavedSearchResponse_Success) isDeleteSavedSearchResponse_Result() {}

type DeleteSavedSearchResponse_Error struct {
	Error *error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*DeleteSavedSearchResponse_Error) isDeleteSavedSearchResponse_Result() {}

type SearchService interface {
	Search(ctx context.Context, req *SearchRequest) (res *SearchResponse, err error)
	AdvancedSearch(ctx context.Context, req *AdvancedSearchRequest) (res *SearchResponse, err error)
	GetSearchSuggestions(ctx context.Context, req *SearchSuggestionRequest) (res *SearchSuggestionResponse, err error)
	GetSearchHistory(ctx context.Context, req *SearchHistoryRequest) (res *SearchHistoryResponse, err error)
	ClearSearchHistory(ctx context.Context, req *ClearSearchHistoryRequest) (res *ClearSearchHistoryResponse, err error)
	SaveSearch(ctx context.Context, req *SaveSearchRequest) (res *SaveSearchResponse, err error)
	GetSavedSearches(ctx context.Context, req *GetSavedSearchesRequest) (res *GetSavedSearchesResponse, err error)
	DeleteSavedSearch(ctx context.Context, req *DeleteSavedSearchRequest) (res *DeleteSavedSearchResponse, err error)
}
