// Code generated by Kitex v0.13.1. DO NOT EDIT.

package aiservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	ai "github.com/linkbox-group/linkbox-server/rpc-gen/ai"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SuggestTags": kitex.NewMethodInfo(
		suggestTagsHandler,
		newSuggestTagsArgs,
		newSuggestTagsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SendMessage": kitex.NewMethodInfo(
		sendMessageHandler,
		newSendMessageArgs,
		newSendMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"ListMessages": kitex.NewMethodInfo(
		listMessagesHandler,
		newListMessagesArgs,
		newListMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteMessage": kitex.NewMethodInfo(
		deleteMessageHandler,
		newDeleteMessageArgs,
		newDeleteMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	aIServiceServiceInfo = NewServiceInfo()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aIServiceServiceInfo
}

// NewServiceInfo creates a new ServiceInfo
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo()
}

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "AIService"
	handlerType := (*ai.AIService)(nil)
	extra := map[string]interface{}{
		"PackageName": "ai",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         serviceMethods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func suggestTagsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	s := arg.(*SuggestTagsArgs)
	success, err := handler.(ai.AIService).SuggestTags(ctx, s.Req)
	if err != nil {
		return err
	}
	realResult := result.(*SuggestTagsResult)
	realResult.Success = success
	return nil
}

func newSuggestTagsArgs() interface{} {
	return &SuggestTagsArgs{}
}

func newSuggestTagsResult() interface{} {
	return &SuggestTagsResult{}
}

type SuggestTagsArgs struct {
	Req *ai.SuggestTagsRequest
}

func (p *SuggestTagsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SuggestTagsArgs) Unmarshal(in []byte) error {
	msg := new(ai.SuggestTagsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SuggestTagsArgs_Req_DEFAULT *ai.SuggestTagsRequest

func (p *SuggestTagsArgs) GetReq() *ai.SuggestTagsRequest {
	if !p.IsSetReq() {
		return SuggestTagsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SuggestTagsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SuggestTagsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SuggestTagsResult struct {
	Success *ai.SuggestTagsResponse
}

var SuggestTagsResult_Success_DEFAULT *ai.SuggestTagsResponse

func (p *SuggestTagsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SuggestTagsResult) Unmarshal(in []byte) error {
	msg := new(ai.SuggestTagsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SuggestTagsResult) GetSuccess() *ai.SuggestTagsResponse {
	if !p.IsSetSuccess() {
		return SuggestTagsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SuggestTagsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.SuggestTagsResponse)
}

func (p *SuggestTagsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SuggestTagsResult) GetResult() interface{} {
	return p.Success
}

func sendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st, err := streaming.GetServerStreamFromArg(arg)
	if err != nil {
		return err
	}
	stream := streaming.NewServerStreamingServer[ai.SendMessageResponse](st)
	req := new(ai.SendMessageRequest)
	if err := stream.RecvMsg(ctx, req); err != nil {
		return err
	}
	return handler.(ai.AIService).SendMessage(ctx, req, stream)
}

func newSendMessageArgs() interface{} {
	return &SendMessageArgs{}
}

func newSendMessageResult() interface{} {
	return &SendMessageResult{}
}

type SendMessageArgs struct {
	Req *ai.SendMessageRequest
}

func (p *SendMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SendMessageArgs) Unmarshal(in []byte) error {
	msg := new(ai.SendMessageRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SendMessageArgs_Req_DEFAULT *ai.SendMessageRequest

func (p *SendMessageArgs) GetReq() *ai.SendMessageRequest {
	if !p.IsSetReq() {
		return SendMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SendMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SendMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SendMessageResult struct {
	Success *ai.SendMessageResponse
}

var SendMessageResult_Success_DEFAULT *ai.SendMessageResponse

func (p *SendMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SendMessageResult) Unmarshal(in []byte) error {
	msg := new(ai.SendMessageResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SendMessageResult) GetSuccess() *ai.SendMessageResponse {
	if !p.IsSetSuccess() {
		return SendMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SendMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.SendMessageResponse)
}

func (p *SendMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SendMessageResult) GetResult() interface{} {
	return p.Success
}

func listMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	s := arg.(*ListMessagesArgs)
	success, err := handler.(ai.AIService).ListMessages(ctx, s.Req)
	if err != nil {
		return err
	}
	realResult := result.(*ListMessagesResult)
	realResult.Success = success
	return nil
}

func newListMessagesArgs() interface{} {
	return &ListMessagesArgs{}
}

func newListMessagesResult() interface{} {
	return &ListMessagesResult{}
}

type ListMessagesArgs struct {
	Req *ai.ListMessagesRequest
}

func (p *ListMessagesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListMessagesArgs) Unmarshal(in []byte) error {
	msg := new(ai.ListMessagesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListMessagesArgs_Req_DEFAULT *ai.ListMessagesRequest

func (p *ListMessagesArgs) GetReq() *ai.ListMessagesRequest {
	if !p.IsSetReq() {
		return ListMessagesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListMessagesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListMessagesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListMessagesResult struct {
	Success *ai.ListMessagesResponse
}

var ListMessagesResult_Success_DEFAULT *ai.ListMessagesResponse

func (p *ListMessagesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListMessagesResult) Unmarshal(in []byte) error {
	msg := new(ai.ListMessagesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListMessagesResult) GetSuccess() *ai.ListMessagesResponse {
	if !p.IsSetSuccess() {
		return ListMessagesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListMessagesResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.ListMessagesResponse)
}

func (p *ListMessagesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListMessagesResult) GetResult() interface{} {
	return p.Success
}

func deleteMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	s := arg.(*DeleteMessageArgs)
	success, err := handler.(ai.AIService).DeleteMessage(ctx, s.Req)
	if err != nil {
		return err
	}
	realResult := result.(*DeleteMessageResult)
	realResult.Success = success
	return nil
}

func newDeleteMessageArgs() interface{} {
	return &DeleteMessageArgs{}
}

func newDeleteMessageResult() interface{} {
	return &DeleteMessageResult{}
}

type DeleteMessageArgs struct {
	Req *ai.DeleteMessageRequest
}

func (p *DeleteMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteMessageArgs) Unmarshal(in []byte) error {
	msg := new(ai.DeleteMessageRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteMessageArgs_Req_DEFAULT *ai.DeleteMessageRequest

func (p *DeleteMessageArgs) GetReq() *ai.DeleteMessageRequest {
	if !p.IsSetReq() {
		return DeleteMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteMessageResult struct {
	Success *ai.DeleteMessageResponse
}

var DeleteMessageResult_Success_DEFAULT *ai.DeleteMessageResponse

func (p *DeleteMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteMessageResult) Unmarshal(in []byte) error {
	msg := new(ai.DeleteMessageResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteMessageResult) GetSuccess() *ai.DeleteMessageResponse {
	if !p.IsSetSuccess() {
		return DeleteMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.DeleteMessageResponse)
}

func (p *DeleteMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteMessageResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c  client.Client
	sc client.Streaming
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c:  c,
		sc: c.(client.Streaming),
	}
}

func (p *kClient) SuggestTags(ctx context.Context, Req *ai.SuggestTagsRequest) (r *ai.SuggestTagsResponse, err error) {
	var _args SuggestTagsArgs
	_args.Req = Req
	var _result SuggestTagsResult
	if err = p.c.Call(ctx, "SuggestTags", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendMessage(ctx context.Context, req *ai.SendMessageRequest) (AIService_SendMessageClient, error) {
	st, err := p.sc.StreamX(ctx, "SendMessage")
	if err != nil {
		return nil, err
	}
	stream := streaming.NewServerStreamingClient[ai.SendMessageResponse](st)
	if err := stream.SendMsg(ctx, req); err != nil {
		return nil, err
	}
	if err := stream.CloseSend(ctx); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) ListMessages(ctx context.Context, Req *ai.ListMessagesRequest) (r *ai.ListMessagesResponse, err error) {
	var _args ListMessagesArgs
	_args.Req = Req
	var _result ListMessagesResult
	if err = p.c.Call(ctx, "ListMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteMessage(ctx context.Context, Req *ai.DeleteMessageRequest) (r *ai.DeleteMessageResponse, err error) {
	var _args DeleteMessageArgs
	_args.Req = Req
	var _result DeleteMessageResult
	if err = p.c.Call(ctx, "DeleteMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
