// Code generated by Kitex v0.13.1. DO NOT EDIT.

package aiservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	ai "github.com/linkbox-group/linkbox-server/rpc-gen/ai"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SuggestTags(ctx context.Context, Req *ai.SuggestTagsRequest, callOptions ...callopt.Option) (r *ai.SuggestTagsResponse, err error)
	SendMessage(ctx context.Context, Req *ai.SendMessageRequest, callOptions ...streamcall.Option) (stream AIService_SendMessageClient, err error)
	ListMessages(ctx context.Context, Req *ai.ListMessagesRequest, callOptions ...callopt.Option) (r *ai.ListMessagesResponse, err error)
	DeleteMessage(ctx context.Context, Req *ai.DeleteMessageRequest, callOptions ...callopt.Option) (r *ai.DeleteMessageResponse, err error)
}

type AIService_SendMessageClient streaming.ServerStreamingClient[ai.SendMessageResponse]

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAIServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAIServiceClient struct {
	*kClient
}

func (p *kAIServiceClient) SuggestTags(ctx context.Context, Req *ai.SuggestTagsRequest, callOptions ...callopt.Option) (r *ai.SuggestTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SuggestTags(ctx, Req)
}

func (p *kAIServiceClient) SendMessage(ctx context.Context, Req *ai.SendMessageRequest, callOptions ...streamcall.Option) (stream AIService_SendMessageClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.SendMessage(ctx, Req)
}

func (p *kAIServiceClient) ListMessages(ctx context.Context, Req *ai.ListMessagesRequest, callOptions ...callopt.Option) (r *ai.ListMessagesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMessages(ctx, Req)
}

func (p *kAIServiceClient) DeleteMessage(ctx context.Context, Req *ai.DeleteMessageRequest, callOptions ...callopt.Option) (r *ai.DeleteMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMessage(ctx, Req)
}
