// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/linkbox-group/linkbox-server/tag/internal/delivery"
)

// Injectors from wire.go:

func NewTagHandler() *delivery.TagDelivery {
	tagDelivery := delivery.NewTagDelivery()
	return tagDelivery
}
