// Code generated by Kitex v0.13.1. DO NOT EDIT.

package tag

import (
	"context"
	"github.com/linkbox-group/linkbox-server/rpc-gen/common/cError"
	"github.com/linkbox-group/linkbox-server/rpc-gen/common/pagination"
	"google.golang.org/protobuf/types/known/timestamppb"

	"github.com/cloudwego/prutal"
)

// 标签
type Tag struct {
	Id          string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId      string                 `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Color       string                 `protobuf:"bytes,5,opt,name=color" json:"color,omitempty"`
	ItemCount   int32                  `protobuf:"varint,6,opt,name=item_count" json:"item_count,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at" json:"updated_at,omitempty"`
}

func (x *Tag) Reset() { *x = Tag{} }

func (x *Tag) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Tag) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Tag) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *Tag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tag) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 创建标签请求
type CreateTagRequest struct {
	UserId      string  `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description *string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Color       *string `protobuf:"bytes,4,opt,name=color" json:"color,omitempty"`
}

func (x *CreateTagRequest) Reset() { *x = CreateTagRequest{} }

func (x *CreateTagRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateTagRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateTagRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

// 创建标签响应
type CreateTagResponse struct {
	// Types that are assignable to Result:
	//
	//	*CreateTagResponse_Tag
	//	*CreateTagResponse_Error
	Result isCreateTagResponse_Result `protobuf_oneof:"result"`
}

func (x *CreateTagResponse) Reset() { *x = CreateTagResponse{} }

func (x *CreateTagResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateTagResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateTagResponse) GetResult() isCreateTagResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *CreateTagResponse) GetTag() *Tag {
	if p, ok := x.GetResult().(*CreateTagResponse_Tag); ok {
		return p.Tag
	}
	return nil
}

func (x *CreateTagResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*CreateTagResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*CreateTagResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateTagResponse_Tag)(nil),
		(*CreateTagResponse_Error)(nil),
	}
}

type isCreateTagResponse_Result interface {
	isCreateTagResponse_Result()
}

type CreateTagResponse_Tag struct {
	Tag *Tag `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
}

func (*CreateTagResponse_Tag) isCreateTagResponse_Result() {}

type CreateTagResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*CreateTagResponse_Error) isCreateTagResponse_Result() {}

// 获取标签请求
type GetTagRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetTagRequest) Reset() { *x = GetTagRequest{} }

func (x *GetTagRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetTagRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取标签响应
type GetTagResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetTagResponse_Tag
	//	*GetTagResponse_Error
	Result isGetTagResponse_Result `protobuf_oneof:"result"`
}

func (x *GetTagResponse) Reset() { *x = GetTagResponse{} }

func (x *GetTagResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetTagResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetTagResponse) GetResult() isGetTagResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetTagResponse) GetTag() *Tag {
	if p, ok := x.GetResult().(*GetTagResponse_Tag); ok {
		return p.Tag
	}
	return nil
}

func (x *GetTagResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetTagResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetTagResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetTagResponse_Tag)(nil),
		(*GetTagResponse_Error)(nil),
	}
}

type isGetTagResponse_Result interface {
	isGetTagResponse_Result()
}

type GetTagResponse_Tag struct {
	Tag *Tag `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
}

func (*GetTagResponse_Tag) isGetTagResponse_Result() {}

type GetTagResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetTagResponse_Error) isGetTagResponse_Result() {}

// 更新标签请求
type UpdateTagRequest struct {
	Id          string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId      string  `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	Name        *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description *string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Color       *string `protobuf:"bytes,5,opt,name=color" json:"color,omitempty"`
}

func (x *UpdateTagRequest) Reset() { *x = UpdateTagRequest{} }

func (x *UpdateTagRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateTagRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTagRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTagRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

// 更新标签响应
type UpdateTagResponse struct {
	// Types that are assignable to Result:
	//
	//	*UpdateTagResponse_Tag
	//	*UpdateTagResponse_Error
	Result isUpdateTagResponse_Result `protobuf_oneof:"result"`
}

func (x *UpdateTagResponse) Reset() { *x = UpdateTagResponse{} }

func (x *UpdateTagResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateTagResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateTagResponse) GetResult() isUpdateTagResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *UpdateTagResponse) GetTag() *Tag {
	if p, ok := x.GetResult().(*UpdateTagResponse_Tag); ok {
		return p.Tag
	}
	return nil
}

func (x *UpdateTagResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*UpdateTagResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*UpdateTagResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UpdateTagResponse_Tag)(nil),
		(*UpdateTagResponse_Error)(nil),
	}
}

type isUpdateTagResponse_Result interface {
	isUpdateTagResponse_Result()
}

type UpdateTagResponse_Tag struct {
	Tag *Tag `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
}

func (*UpdateTagResponse_Tag) isUpdateTagResponse_Result() {}

type UpdateTagResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*UpdateTagResponse_Error) isUpdateTagResponse_Result() {}

// 删除标签请求
type DeleteTagRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *DeleteTagRequest) Reset() { *x = DeleteTagRequest{} }

func (x *DeleteTagRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteTagRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 删除标签响应
type DeleteTagResponse struct {
	// Types that are assignable to Result:
	//
	//	*DeleteTagResponse_Success
	//	*DeleteTagResponse_Error
	Result isDeleteTagResponse_Result `protobuf_oneof:"result"`
}

func (x *DeleteTagResponse) Reset() { *x = DeleteTagResponse{} }

func (x *DeleteTagResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteTagResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteTagResponse) GetResult() isDeleteTagResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *DeleteTagResponse) GetSuccess() bool {
	if p, ok := x.GetResult().(*DeleteTagResponse_Success); ok {
		return p.Success
	}
	return false
}

func (x *DeleteTagResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*DeleteTagResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*DeleteTagResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteTagResponse_Success)(nil),
		(*DeleteTagResponse_Error)(nil),
	}
}

type isDeleteTagResponse_Result interface {
	isDeleteTagResponse_Result()
}

type DeleteTagResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (*DeleteTagResponse_Success) isDeleteTagResponse_Result() {}

type DeleteTagResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*DeleteTagResponse_Error) isDeleteTagResponse_Result() {}

// 获取用户标签请求
type GetUserTagsRequest struct {
	UserId      string                        `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Pagination  *pagination.PaginationRequest `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
	SearchQuery *string                       `protobuf:"bytes,3,opt,name=search_query" json:"search_query,omitempty"`
}

func (x *GetUserTagsRequest) Reset() { *x = GetUserTagsRequest{} }

func (x *GetUserTagsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserTagsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserTagsRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetUserTagsRequest) GetSearchQuery() string {
	if x != nil && x.SearchQuery != nil {
		return *x.SearchQuery
	}
	return ""
}

// 获取用户标签响应
type GetUserTagsResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetUserTagsResponse_Tags
	//	*GetUserTagsResponse_Error
	Result isGetUserTagsResponse_Result `protobuf_oneof:"result"`
}

func (x *GetUserTagsResponse) Reset() { *x = GetUserTagsResponse{} }

func (x *GetUserTagsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserTagsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserTagsResponse) GetResult() isGetUserTagsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetUserTagsResponse) GetTags() *TagsData {
	if p, ok := x.GetResult().(*GetUserTagsResponse_Tags); ok {
		return p.Tags
	}
	return nil
}

func (x *GetUserTagsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetUserTagsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetUserTagsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetUserTagsResponse_Tags)(nil),
		(*GetUserTagsResponse_Error)(nil),
	}
}

type isGetUserTagsResponse_Result interface {
	isGetUserTagsResponse_Result()
}

type GetUserTagsResponse_Tags struct {
	Tags *TagsData `protobuf:"bytes,1,opt,name=tags" json:"tags,omitempty"`
}

func (*GetUserTagsResponse_Tags) isGetUserTagsResponse_Result() {}

type GetUserTagsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetUserTagsResponse_Error) isGetUserTagsResponse_Result() {}

// 标签数据
type TagsData struct {
	Tags       []*Tag                     `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	Pagination *pagination.PaginationMeta `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *TagsData) Reset() { *x = TagsData{} }

func (x *TagsData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TagsData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TagsData) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TagsData) GetPagination() *pagination.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 添加标签到内容项请求
type AddTagsToItemsRequest struct {
	UserId  string   `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Tags    []string `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	ItemIds []string `protobuf:"bytes,3,rep,name=item_ids" json:"item_ids,omitempty"`
}

func (x *AddTagsToItemsRequest) Reset() { *x = AddTagsToItemsRequest{} }

func (x *AddTagsToItemsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *AddTagsToItemsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AddTagsToItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddTagsToItemsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddTagsToItemsRequest) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

// 添加标签到内容项响应
type AddTagsToItemsResponse struct {
	// Types that are assignable to Result:
	//
	//	*AddTagsToItemsResponse_Data
	//	*AddTagsToItemsResponse_Error
	Result isAddTagsToItemsResponse_Result `protobuf_oneof:"result"`
}

func (x *AddTagsToItemsResponse) Reset() { *x = AddTagsToItemsResponse{} }

func (x *AddTagsToItemsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *AddTagsToItemsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AddTagsToItemsResponse) GetResult() isAddTagsToItemsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *AddTagsToItemsResponse) GetData() *TagOperationResult {
	if p, ok := x.GetResult().(*AddTagsToItemsResponse_Data); ok {
		return p.Data
	}
	return nil
}

func (x *AddTagsToItemsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*AddTagsToItemsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*AddTagsToItemsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AddTagsToItemsResponse_Data)(nil),
		(*AddTagsToItemsResponse_Error)(nil),
	}
}

type isAddTagsToItemsResponse_Result interface {
	isAddTagsToItemsResponse_Result()
}

type AddTagsToItemsResponse_Data struct {
	Data *TagOperationResult `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (*AddTagsToItemsResponse_Data) isAddTagsToItemsResponse_Result() {}

type AddTagsToItemsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*AddTagsToItemsResponse_Error) isAddTagsToItemsResponse_Result() {}

// 标签操作结果
type TagOperationResult struct {
	SuccessCount  int32    `protobuf:"varint,1,opt,name=success_count" json:"success_count,omitempty"`
	FailureCount  int32    `protobuf:"varint,2,opt,name=failure_count" json:"failure_count,omitempty"`
	FailedItemIds []string `protobuf:"bytes,3,rep,name=failed_item_ids" json:"failed_item_ids,omitempty"`
}

func (x *TagOperationResult) Reset() { *x = TagOperationResult{} }

func (x *TagOperationResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TagOperationResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TagOperationResult) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *TagOperationResult) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *TagOperationResult) GetFailedItemIds() []string {
	if x != nil {
		return x.FailedItemIds
	}
	return nil
}

// 从内容项移除标签请求
type RemoveTagsFromItemsRequest struct {
	UserId  string   `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Tags    []string `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	ItemIds []string `protobuf:"bytes,3,rep,name=item_ids" json:"item_ids,omitempty"`
}

func (x *RemoveTagsFromItemsRequest) Reset() { *x = RemoveTagsFromItemsRequest{} }

func (x *RemoveTagsFromItemsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RemoveTagsFromItemsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RemoveTagsFromItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveTagsFromItemsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RemoveTagsFromItemsRequest) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

// 从内容项移除标签响应
type RemoveTagsFromItemsResponse struct {
	// Types that are assignable to Result:
	//
	//	*RemoveTagsFromItemsResponse_Data
	//	*RemoveTagsFromItemsResponse_Error
	Result isRemoveTagsFromItemsResponse_Result `protobuf_oneof:"result"`
}

func (x *RemoveTagsFromItemsResponse) Reset() { *x = RemoveTagsFromItemsResponse{} }

func (x *RemoveTagsFromItemsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RemoveTagsFromItemsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RemoveTagsFromItemsResponse) GetResult() isRemoveTagsFromItemsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *RemoveTagsFromItemsResponse) GetData() *TagOperationResult {
	if p, ok := x.GetResult().(*RemoveTagsFromItemsResponse_Data); ok {
		return p.Data
	}
	return nil
}

func (x *RemoveTagsFromItemsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*RemoveTagsFromItemsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*RemoveTagsFromItemsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RemoveTagsFromItemsResponse_Data)(nil),
		(*RemoveTagsFromItemsResponse_Error)(nil),
	}
}

type isRemoveTagsFromItemsResponse_Result interface {
	isRemoveTagsFromItemsResponse_Result()
}

type RemoveTagsFromItemsResponse_Data struct {
	Data *TagOperationResult `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (*RemoveTagsFromItemsResponse_Data) isRemoveTagsFromItemsResponse_Result() {}

type RemoveTagsFromItemsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*RemoveTagsFromItemsResponse_Error) isRemoveTagsFromItemsResponse_Result() {}

// 获取内容项标签请求
type GetItemTagsRequest struct {
	ItemId string `protobuf:"bytes,1,opt,name=item_id" json:"item_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetItemTagsRequest) Reset() { *x = GetItemTagsRequest{} }

func (x *GetItemTagsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemTagsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemTagsRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetItemTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取内容项标签响应
type GetItemTagsResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetItemTagsResponse_Tags
	//	*GetItemTagsResponse_Error
	Result isGetItemTagsResponse_Result `protobuf_oneof:"result"`
}

func (x *GetItemTagsResponse) Reset() { *x = GetItemTagsResponse{} }

func (x *GetItemTagsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemTagsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemTagsResponse) GetResult() isGetItemTagsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetItemTagsResponse) GetTags() *ItemTagsData {
	if p, ok := x.GetResult().(*GetItemTagsResponse_Tags); ok {
		return p.Tags
	}
	return nil
}

func (x *GetItemTagsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetItemTagsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetItemTagsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetItemTagsResponse_Tags)(nil),
		(*GetItemTagsResponse_Error)(nil),
	}
}

type isGetItemTagsResponse_Result interface {
	isGetItemTagsResponse_Result()
}

type GetItemTagsResponse_Tags struct {
	Tags *ItemTagsData `protobuf:"bytes,1,opt,name=tags" json:"tags,omitempty"`
}

func (*GetItemTagsResponse_Tags) isGetItemTagsResponse_Result() {}

type GetItemTagsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetItemTagsResponse_Error) isGetItemTagsResponse_Result() {}

// 内容项标签数据
type ItemTagsData struct {
	ItemId string `protobuf:"bytes,1,opt,name=item_id" json:"item_id,omitempty"`
	Tags   []*Tag `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
}

func (x *ItemTagsData) Reset() { *x = ItemTagsData{} }

func (x *ItemTagsData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ItemTagsData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ItemTagsData) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemTagsData) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 合并标签请求
type MergeTagsRequest struct {
	UserId           string   `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	SourceTagIds     []string `protobuf:"bytes,2,rep,name=source_tag_ids" json:"source_tag_ids,omitempty"`
	TargetTagId      string   `protobuf:"bytes,3,opt,name=target_tag_id" json:"target_tag_id,omitempty"`
	DeleteSourceTags *bool    `protobuf:"varint,4,opt,name=delete_source_tags" json:"delete_source_tags,omitempty"`
}

func (x *MergeTagsRequest) Reset() { *x = MergeTagsRequest{} }

func (x *MergeTagsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MergeTagsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MergeTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MergeTagsRequest) GetSourceTagIds() []string {
	if x != nil {
		return x.SourceTagIds
	}
	return nil
}

func (x *MergeTagsRequest) GetTargetTagId() string {
	if x != nil {
		return x.TargetTagId
	}
	return ""
}

func (x *MergeTagsRequest) GetDeleteSourceTags() bool {
	if x != nil && x.DeleteSourceTags != nil {
		return *x.DeleteSourceTags
	}
	return false
}

// 合并标签响应
type MergeTagsResponse struct {
	// Types that are assignable to Result:
	//
	//	*MergeTagsResponse_Data
	//	*MergeTagsResponse_Error
	Result isMergeTagsResponse_Result `protobuf_oneof:"result"`
}

func (x *MergeTagsResponse) Reset() { *x = MergeTagsResponse{} }

func (x *MergeTagsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MergeTagsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MergeTagsResponse) GetResult() isMergeTagsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *MergeTagsResponse) GetData() *MergeTagsResult {
	if p, ok := x.GetResult().(*MergeTagsResponse_Data); ok {
		return p.Data
	}
	return nil
}

func (x *MergeTagsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*MergeTagsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*MergeTagsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MergeTagsResponse_Data)(nil),
		(*MergeTagsResponse_Error)(nil),
	}
}

type isMergeTagsResponse_Result interface {
	isMergeTagsResponse_Result()
}

type MergeTagsResponse_Data struct {
	Data *MergeTagsResult `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (*MergeTagsResponse_Data) isMergeTagsResponse_Result() {}

type MergeTagsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*MergeTagsResponse_Error) isMergeTagsResponse_Result() {}

// 合并标签结果
type MergeTagsResult struct {
	AffectedItems int32 `protobuf:"varint,1,opt,name=affected_items" json:"affected_items,omitempty"`
	TargetTag     *Tag  `protobuf:"bytes,2,opt,name=target_tag" json:"target_tag,omitempty"`
}

func (x *MergeTagsResult) Reset() { *x = MergeTagsResult{} }

func (x *MergeTagsResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MergeTagsResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MergeTagsResult) GetAffectedItems() int32 {
	if x != nil {
		return x.AffectedItems
	}
	return 0
}

func (x *MergeTagsResult) GetTargetTag() *Tag {
	if x != nil {
		return x.TargetTag
	}
	return nil
}

// 获取标签统计请求
type GetTagStatsRequest struct {
	UserId        string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	TopCount      *int32 `protobuf:"varint,2,opt,name=top_count" json:"top_count,omitempty"`
	IncludeUnused *bool  `protobuf:"varint,3,opt,name=include_unused" json:"include_unused,omitempty"`
}

func (x *GetTagStatsRequest) Reset() { *x = GetTagStatsRequest{} }

func (x *GetTagStatsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetTagStatsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetTagStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTagStatsRequest) GetTopCount() int32 {
	if x != nil && x.TopCount != nil {
		return *x.TopCount
	}
	return 0
}

func (x *GetTagStatsRequest) GetIncludeUnused() bool {
	if x != nil && x.IncludeUnused != nil {
		return *x.IncludeUnused
	}
	return false
}

// 获取标签统计响应
type GetTagStatsResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetTagStatsResponse_Stats
	//	*GetTagStatsResponse_Error
	Result isGetTagStatsResponse_Result `protobuf_oneof:"result"`
}

func (x *GetTagStatsResponse) Reset() { *x = GetTagStatsResponse{} }

func (x *GetTagStatsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetTagStatsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetTagStatsResponse) GetResult() isGetTagStatsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetTagStatsResponse) GetStats() *TagStatsData {
	if p, ok := x.GetResult().(*GetTagStatsResponse_Stats); ok {
		return p.Stats
	}
	return nil
}

func (x *GetTagStatsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetTagStatsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetTagStatsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetTagStatsResponse_Stats)(nil),
		(*GetTagStatsResponse_Error)(nil),
	}
}

type isGetTagStatsResponse_Result interface {
	isGetTagStatsResponse_Result()
}

type GetTagStatsResponse_Stats struct {
	Stats *TagStatsData `protobuf:"bytes,1,opt,name=stats" json:"stats,omitempty"`
}

func (*GetTagStatsResponse_Stats) isGetTagStatsResponse_Result() {}

type GetTagStatsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetTagStatsResponse_Error) isGetTagStatsResponse_Result() {}

// 标签统计数据
type TagStatsData struct {
	TagStats   []*TagStats `protobuf:"bytes,1,rep,name=tag_stats" json:"tag_stats,omitempty"`
	TotalTags  int32       `protobuf:"varint,2,opt,name=total_tags" json:"total_tags,omitempty"`
	UnusedTags int32       `protobuf:"varint,3,opt,name=unused_tags" json:"unused_tags,omitempty"`
}

func (x *TagStatsData) Reset() { *x = TagStatsData{} }

func (x *TagStatsData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TagStatsData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TagStatsData) GetTagStats() []*TagStats {
	if x != nil {
		return x.TagStats
	}
	return nil
}

func (x *TagStatsData) GetTotalTags() int32 {
	if x != nil {
		return x.TotalTags
	}
	return 0
}

func (x *TagStatsData) GetUnusedTags() int32 {
	if x != nil {
		return x.UnusedTags
	}
	return 0
}

// 标签统计
type TagStats struct {
	Tag             *Tag               `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	ItemCount       int32              `protobuf:"varint,2,opt,name=item_count" json:"item_count,omitempty"`
	CollectionUsage []*CollectionUsage `protobuf:"bytes,3,rep,name=collection_usage" json:"collection_usage,omitempty"`
}

func (x *TagStats) Reset() { *x = TagStats{} }

func (x *TagStats) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TagStats) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TagStats) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *TagStats) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *TagStats) GetCollectionUsage() []*CollectionUsage {
	if x != nil {
		return x.CollectionUsage
	}
	return nil
}

// 收藏夹使用情况
type CollectionUsage struct {
	CollectionId   string `protobuf:"bytes,1,opt,name=collection_id" json:"collection_id,omitempty"`
	CollectionName string `protobuf:"bytes,2,opt,name=collection_name" json:"collection_name,omitempty"`
	Count          int32  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (x *CollectionUsage) Reset() { *x = CollectionUsage{} }

func (x *CollectionUsage) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CollectionUsage) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CollectionUsage) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CollectionUsage) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CollectionUsage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取相关标签请求
type GetRelatedTagsRequest struct {
	TagId  string `protobuf:"bytes,1,opt,name=tag_id" json:"tag_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	Limit  *int32 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (x *GetRelatedTagsRequest) Reset() { *x = GetRelatedTagsRequest{} }

func (x *GetRelatedTagsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetRelatedTagsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetRelatedTagsRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *GetRelatedTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRelatedTagsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

// 获取相关标签响应
type GetRelatedTagsResponse struct {
	// Types that are assignable to Result:
	//
	//	*GetRelatedTagsResponse_RelatedTags
	//	*GetRelatedTagsResponse_Error
	Result isGetRelatedTagsResponse_Result `protobuf_oneof:"result"`
}

func (x *GetRelatedTagsResponse) Reset() { *x = GetRelatedTagsResponse{} }

func (x *GetRelatedTagsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetRelatedTagsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetRelatedTagsResponse) GetResult() isGetRelatedTagsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *GetRelatedTagsResponse) GetRelatedTags() *RelatedTagsData {
	if p, ok := x.GetResult().(*GetRelatedTagsResponse_RelatedTags); ok {
		return p.RelatedTags
	}
	return nil
}

func (x *GetRelatedTagsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*GetRelatedTagsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*GetRelatedTagsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetRelatedTagsResponse_RelatedTags)(nil),
		(*GetRelatedTagsResponse_Error)(nil),
	}
}

type isGetRelatedTagsResponse_Result interface {
	isGetRelatedTagsResponse_Result()
}

type GetRelatedTagsResponse_RelatedTags struct {
	RelatedTags *RelatedTagsData `protobuf:"bytes,1,opt,name=related_tags" json:"related_tags,omitempty"`
}

func (*GetRelatedTagsResponse_RelatedTags) isGetRelatedTagsResponse_Result() {}

type GetRelatedTagsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*GetRelatedTagsResponse_Error) isGetRelatedTagsResponse_Result() {}

// 相关标签数据
type RelatedTagsData struct {
	TagId       string         `protobuf:"bytes,1,opt,name=tag_id" json:"tag_id,omitempty"`
	RelatedTags []*TagRelation `protobuf:"bytes,2,rep,name=related_tags" json:"related_tags,omitempty"`
}

func (x *RelatedTagsData) Reset() { *x = RelatedTagsData{} }

func (x *RelatedTagsData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RelatedTagsData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RelatedTagsData) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *RelatedTagsData) GetRelatedTags() []*TagRelation {
	if x != nil {
		return x.RelatedTags
	}
	return nil
}

// 标签关系
type TagRelation struct {
	Tag          *Tag    `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Correlation  float32 `protobuf:"fixed32,2,opt,name=correlation" json:"correlation,omitempty"`
	CoOccurrence int32   `protobuf:"varint,3,opt,name=co_occurrence" json:"co_occurrence,omitempty"`
}

func (x *TagRelation) Reset() { *x = TagRelation{} }

func (x *TagRelation) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TagRelation) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TagRelation) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *TagRelation) GetCorrelation() float32 {
	if x != nil {
		return x.Correlation
	}
	return 0
}

func (x *TagRelation) GetCoOccurrence() int32 {
	if x != nil {
		return x.CoOccurrence
	}
	return 0
}

// 自动建议标签请求
type SuggestTagsRequest struct {
	UserId  string  `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	Url     string  `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Title   *string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Content *string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	Limit   *int32  `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
}

func (x *SuggestTagsRequest) Reset() { *x = SuggestTagsRequest{} }

func (x *SuggestTagsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SuggestTagsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SuggestTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SuggestTagsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SuggestTagsRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *SuggestTagsRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *SuggestTagsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

// 自动建议标签响应
type SuggestTagsResponse struct {
	// Types that are assignable to Result:
	//
	//	*SuggestTagsResponse_SuggestedTags
	//	*SuggestTagsResponse_Error
	Result isSuggestTagsResponse_Result `protobuf_oneof:"result"`
}

func (x *SuggestTagsResponse) Reset() { *x = SuggestTagsResponse{} }

func (x *SuggestTagsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SuggestTagsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SuggestTagsResponse) GetResult() isSuggestTagsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}
func (x *SuggestTagsResponse) GetSuggestedTags() *SuggestedTagsData {
	if p, ok := x.GetResult().(*SuggestTagsResponse_SuggestedTags); ok {
		return p.SuggestedTags
	}
	return nil
}

func (x *SuggestTagsResponse) GetError() *cError.Error {
	if p, ok := x.GetResult().(*SuggestTagsResponse_Error); ok {
		return p.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*SuggestTagsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SuggestTagsResponse_SuggestedTags)(nil),
		(*SuggestTagsResponse_Error)(nil),
	}
}

type isSuggestTagsResponse_Result interface {
	isSuggestTagsResponse_Result()
}

type SuggestTagsResponse_SuggestedTags struct {
	SuggestedTags *SuggestedTagsData `protobuf:"bytes,1,opt,name=suggested_tags" json:"suggested_tags,omitempty"`
}

func (*SuggestTagsResponse_SuggestedTags) isSuggestTagsResponse_Result() {}

type SuggestTagsResponse_Error struct {
	Error *cError.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (*SuggestTagsResponse_Error) isSuggestTagsResponse_Result() {}

// 建议标签数据
type SuggestedTagsData struct {
	TagSuggestions []*TagSuggestion `protobuf:"bytes,1,rep,name=tag_suggestions" json:"tag_suggestions,omitempty"`
}

func (x *SuggestedTagsData) Reset() { *x = SuggestedTagsData{} }

func (x *SuggestedTagsData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SuggestedTagsData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SuggestedTagsData) GetTagSuggestions() []*TagSuggestion {
	if x != nil {
		return x.TagSuggestions
	}
	return nil
}

// 标签建议
type TagSuggestion struct {
	Tag        string  `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence" json:"confidence,omitempty"`
	Source     string  `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"` // "content", "history", "popular"
}

func (x *TagSuggestion) Reset() { *x = TagSuggestion{} }

func (x *TagSuggestion) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TagSuggestion) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TagSuggestion) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagSuggestion) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TagSuggestion) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type TagService interface {
	CreateTag(ctx context.Context, req *CreateTagRequest) (res *CreateTagResponse, err error)
	GetTag(ctx context.Context, req *GetTagRequest) (res *GetTagResponse, err error)
	UpdateTag(ctx context.Context, req *UpdateTagRequest) (res *UpdateTagResponse, err error)
	DeleteTag(ctx context.Context, req *DeleteTagRequest) (res *DeleteTagResponse, err error)
	GetUserTags(ctx context.Context, req *GetUserTagsRequest) (res *GetUserTagsResponse, err error)
	AddTagsToItems(ctx context.Context, req *AddTagsToItemsRequest) (res *AddTagsToItemsResponse, err error)
	RemoveTagsFromItems(ctx context.Context, req *RemoveTagsFromItemsRequest) (res *RemoveTagsFromItemsResponse, err error)
	GetItemTags(ctx context.Context, req *GetItemTagsRequest) (res *GetItemTagsResponse, err error)
	MergeTags(ctx context.Context, req *MergeTagsRequest) (res *MergeTagsResponse, err error)
	GetTagStats(ctx context.Context, req *GetTagStatsRequest) (res *GetTagStatsResponse, err error)
	GetRelatedTags(ctx context.Context, req *GetRelatedTagsRequest) (res *GetRelatedTagsResponse, err error)
	SuggestTags(ctx context.Context, req *SuggestTagsRequest) (res *SuggestTagsResponse, err error)
}
