// Code generated by Kitex v0.13.1. DO NOT EDIT.

package error

import (
	"strconv"

	"github.com/cloudwego/prutal"
)

// 系统错误码定义
type ErrorCode int32

const (
	// 成功
	ErrorCode_SUCCESS ErrorCode = 0

	// 系统级错误: 10000-19999
	ErrorCode_SYSTEM_ERROR        ErrorCode = 10000
	ErrorCode_SERVICE_UNAVAILABLE ErrorCode = 10001
	ErrorCode_PARAMETER_ERROR     ErrorCode = 10002
	ErrorCode_TIMEOUT_ERROR       ErrorCode = 10003

	// 用户相关错误: 30000-39999
	ErrorCode_UNAUTHORIZED        ErrorCode = 30000
	ErrorCode_PERMISSION_DENIED   ErrorCode = 30001
	ErrorCode_INVALID_CREDENTIALS ErrorCode = 30002
	ErrorCode_ACCOUNT_DISABLED    ErrorCode = 30003

	// 业务逻辑错误: 40000-49999
	ErrorCode_NOT_FOUND                      ErrorCode = 40000
	ErrorCode_EMAIL_ALREADY_EXISTS           ErrorCode = 40001
	ErrorCode_PHONE_ALREADY_EXISTS           ErrorCode = 40002
	ErrorCode_USERNAME_ALREADY_EXISTS        ErrorCode = 40003
	ErrorCode_DEFAULT_COLLECTION_UNDELETABLE ErrorCode = 40004
	ErrorCode_COLLECTION_NOT_EMPTY           ErrorCode = 40005
	ErrorCode_INVALID_SHARE_LINK             ErrorCode = 40006

	// 第三方服务错误: 50000-59999
	ErrorCode_THIRD_PARTY_SERVICE_ERROR ErrorCode = 50000
	ErrorCode_THIRD_PARTY_AUTH_FAILED   ErrorCode = 50001
)

// Enum value maps for ErrorCode.
var ErrorCode_name = map[int32]string{
	0:     "SUCCESS",
	10000: "SYSTEM_ERROR",
	10001: "SERVICE_UNAVAILABLE",
	10002: "PARAMETER_ERROR",
	10003: "TIMEOUT_ERROR",
	30000: "UNAUTHORIZED",
	30001: "PERMISSION_DENIED",
	30002: "INVALID_CREDENTIALS",
	30003: "ACCOUNT_DISABLED",
	40000: "NOT_FOUND",
	40001: "EMAIL_ALREADY_EXISTS",
	40002: "PHONE_ALREADY_EXISTS",
	40003: "USERNAME_ALREADY_EXISTS",
	40004: "DEFAULT_COLLECTION_UNDELETABLE",
	40005: "COLLECTION_NOT_EMPTY",
	40006: "INVALID_SHARE_LINK",
	50000: "THIRD_PARTY_SERVICE_ERROR",
	50001: "THIRD_PARTY_AUTH_FAILED",
}

var ErrorCode_value = map[string]int32{
	"SUCCESS":                        0,
	"SYSTEM_ERROR":                   10000,
	"SERVICE_UNAVAILABLE":            10001,
	"PARAMETER_ERROR":                10002,
	"TIMEOUT_ERROR":                  10003,
	"UNAUTHORIZED":                   30000,
	"PERMISSION_DENIED":              30001,
	"INVALID_CREDENTIALS":            30002,
	"ACCOUNT_DISABLED":               30003,
	"NOT_FOUND":                      40000,
	"EMAIL_ALREADY_EXISTS":           40001,
	"PHONE_ALREADY_EXISTS":           40002,
	"USERNAME_ALREADY_EXISTS":        40003,
	"DEFAULT_COLLECTION_UNDELETABLE": 40004,
	"COLLECTION_NOT_EMPTY":           40005,
	"INVALID_SHARE_LINK":             40006,
	"THIRD_PARTY_SERVICE_ERROR":      50000,
	"THIRD_PARTY_AUTH_FAILED":        50001,
}

func (x ErrorCode) String() string {
	s, ok := ErrorCode_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 标准错误消息
type Error struct {
	Code      ErrorCode `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`            // 错误码
	Message   string    `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`       // 错误消息
	Details   string    `protobuf:"bytes,3,opt,name=details" json:"details,omitempty"`       // 详细信息(仅用于日志和调试)
	RequestId string    `protobuf:"bytes,4,opt,name=request_id" json:"request_id,omitempty"` // 请求跟踪ID
}

func (x *Error) Reset() { *x = Error{} }

func (x *Error) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Error) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_SUCCESS
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Error) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}
