// Code generated by Kitex v0.13.1. DO NOT EDIT.

package pagination

import "github.com/cloudwego/prutal"

// 分页请求
type PaginationRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`           // 页码，从1开始
	PageSize int32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"` // 每页大小，默认20
}

func (x *PaginationRequest) Reset() { *x = PaginationRequest{} }

func (x *PaginationRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PaginationRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 分页元数据
type PaginationMeta struct {
	Page       int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`               // 当前页码
	PageSize   int32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`     // 每页大小
	TotalPages int32 `protobuf:"varint,3,opt,name=total_pages" json:"total_pages,omitempty"` // 总页数
	TotalItems int32 `protobuf:"varint,4,opt,name=total_items" json:"total_items,omitempty"` // 总条目数
}

func (x *PaginationMeta) Reset() { *x = PaginationMeta{} }

func (x *PaginationMeta) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PaginationMeta) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PaginationMeta) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationMeta) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationMeta) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationMeta) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

// 排序请求
type SortRequest struct {
	Field     string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`          // 排序字段
	Ascending bool   `protobuf:"varint,2,opt,name=ascending" json:"ascending,omitempty"` // 是否升序
}

func (x *SortRequest) Reset() { *x = SortRequest{} }

func (x *SortRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SortRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SortRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortRequest) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}
