// Code generated by Kitex v0.13.1. DO NOT EDIT.

package model

import (
	"google.golang.org/protobuf/types/known/timestamppb"
	"strconv"

	"github.com/cloudwego/prutal"
)

// 内容类型枚举
type ItemType int32

const (
	ItemType_UNKNOWN_TYPE ItemType = 0
	ItemType_LINK         ItemType = 1
	ItemType_NOTE         ItemType = 2
)

// Enum value maps for ItemType.
var ItemType_name = map[int32]string{
	0: "UNKNOWN_TYPE",
	1: "LINK",
	2: "NOTE",
}

var ItemType_value = map[string]int32{
	"UNKNOWN_TYPE": 0,
	"LINK":         1,
	"NOTE":         2,
}

func (x ItemType) String() string {
	s, ok := ItemType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type Item struct {
	Id               string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	Type             ItemType               `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Url              string                 `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Title            string                 `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	ThumbnailUrl     string                 `protobuf:"bytes,7,opt,name=thumbnail_url" json:"thumbnail_url,omitempty"`
	TagNames         []string               `protobuf:"bytes,10,rep,name=tag_names" json:"tag_names,omitempty"`
	OrganizationPath string                 `protobuf:"bytes,11,opt,name=organization_path" json:"organization_path,omitempty"`
	Tags             []string               `protobuf:"bytes,8,rep,name=tags" json:"tags,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,9,opt,name=organization_id" json:"organization_id,omitempty"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=deleted_at" json:"deleted_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at" json:"updated_at,omitempty"`
	Note             string                 `protobuf:"bytes,15,opt,name=note" json:"note,omitempty"`
	ReadCount        int32                  `protobuf:"varint,16,opt,name=read_count" json:"read_count,omitempty"`
}

func (x *Item) Reset() { *x = Item{} }

func (x *Item) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Item) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Item) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_UNKNOWN_TYPE
}

func (x *Item) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Item) GetTagNames() []string {
	if x != nil {
		return x.TagNames
	}
	return nil
}

func (x *Item) GetOrganizationPath() string {
	if x != nil {
		return x.OrganizationPath
	}
	return ""
}

func (x *Item) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Item) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Item) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Item) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Item) GetReadCount() int32 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

type TrashItem struct {
	Id        string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	Title     string                 `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at" json:"deleted_at,omitempty"`
	ExpiredAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expired_at" json:"expired_at,omitempty"`
}

func (x *TrashItem) Reset() { *x = TrashItem{} }

func (x *TrashItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TrashItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TrashItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrashItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrashItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrashItem) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *TrashItem) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}
