// Code generated by Kitex v0.13.1. DO NOT EDIT.

package searchservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	search "github.com/linkbox-group/linkbox-server/rpc-gen/search"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Search(ctx context.Context, Req *search.SearchRequest, callOptions ...callopt.Option) (r *search.SearchResponse, err error)
	AdvancedSearch(ctx context.Context, Req *search.AdvancedSearchRequest, callOptions ...callopt.Option) (r *search.SearchResponse, err error)
	GetSearchSuggestions(ctx context.Context, Req *search.SearchSuggestionRequest, callOptions ...callopt.Option) (r *search.SearchSuggestionResponse, err error)
	GetSearchHistory(ctx context.Context, Req *search.SearchHistoryRequest, callOptions ...callopt.Option) (r *search.SearchHistoryResponse, err error)
	ClearSearchHistory(ctx context.Context, Req *search.ClearSearchHistoryRequest, callOptions ...callopt.Option) (r *search.ClearSearchHistoryResponse, err error)
	SaveSearch(ctx context.Context, Req *search.SaveSearchRequest, callOptions ...callopt.Option) (r *search.SaveSearchResponse, err error)
	GetSavedSearches(ctx context.Context, Req *search.GetSavedSearchesRequest, callOptions ...callopt.Option) (r *search.GetSavedSearchesResponse, err error)
	DeleteSavedSearch(ctx context.Context, Req *search.DeleteSavedSearchRequest, callOptions ...callopt.Option) (r *search.DeleteSavedSearchResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSearchServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSearchServiceClient struct {
	*kClient
}

func (p *kSearchServiceClient) Search(ctx context.Context, Req *search.SearchRequest, callOptions ...callopt.Option) (r *search.SearchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Search(ctx, Req)
}

func (p *kSearchServiceClient) AdvancedSearch(ctx context.Context, Req *search.AdvancedSearchRequest, callOptions ...callopt.Option) (r *search.SearchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdvancedSearch(ctx, Req)
}

func (p *kSearchServiceClient) GetSearchSuggestions(ctx context.Context, Req *search.SearchSuggestionRequest, callOptions ...callopt.Option) (r *search.SearchSuggestionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSearchSuggestions(ctx, Req)
}

func (p *kSearchServiceClient) GetSearchHistory(ctx context.Context, Req *search.SearchHistoryRequest, callOptions ...callopt.Option) (r *search.SearchHistoryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSearchHistory(ctx, Req)
}

func (p *kSearchServiceClient) ClearSearchHistory(ctx context.Context, Req *search.ClearSearchHistoryRequest, callOptions ...callopt.Option) (r *search.ClearSearchHistoryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ClearSearchHistory(ctx, Req)
}

func (p *kSearchServiceClient) SaveSearch(ctx context.Context, Req *search.SaveSearchRequest, callOptions ...callopt.Option) (r *search.SaveSearchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveSearch(ctx, Req)
}

func (p *kSearchServiceClient) GetSavedSearches(ctx context.Context, Req *search.GetSavedSearchesRequest, callOptions ...callopt.Option) (r *search.GetSavedSearchesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSavedSearches(ctx, Req)
}

func (p *kSearchServiceClient) DeleteSavedSearch(ctx context.Context, Req *search.DeleteSavedSearchRequest, callOptions ...callopt.Option) (r *search.DeleteSavedSearchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteSavedSearch(ctx, Req)
}
