// Code generated by Kitex v0.13.1. DO NOT EDIT.

package analyticsservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	analytics "github.com/linkbox-group/linkbox-server/rpc-gen/analytics"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetUserActivityStats": kitex.NewMethodInfo(
		getUserActivityStatsHandler,
		newGetUserActivityStatsArgs,
		newGetUserActivityStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetItemStats": kitex.NewMethodInfo(
		getItemStatsHandler,
		newGetItemStatsArgs,
		newGetItemStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetCollectionStats": kitex.NewMethodInfo(
		getCollectionStatsHandler,
		newGetCollectionStatsArgs,
		newGetCollectionStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetTagStats": kitex.NewMethodInfo(
		getTagStatsHandler,
		newGetTagStatsArgs,
		newGetTagStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetDomainStats": kitex.NewMethodInfo(
		getDomainStatsHandler,
		newGetDomainStatsArgs,
		newGetDomainStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUsageTrends": kitex.NewMethodInfo(
		getUsageTrendsHandler,
		newGetUsageTrendsArgs,
		newGetUsageTrendsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetItemAccessHistory": kitex.NewMethodInfo(
		getItemAccessHistoryHandler,
		newGetItemAccessHistoryArgs,
		newGetItemAccessHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RecordItemAccess": kitex.NewMethodInfo(
		recordItemAccessHandler,
		newRecordItemAccessArgs,
		newRecordItemAccessResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetRecommendedItems": kitex.NewMethodInfo(
		getRecommendedItemsHandler,
		newGetRecommendedItemsArgs,
		newGetRecommendedItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetRelatedItems": kitex.NewMethodInfo(
		getRelatedItemsHandler,
		newGetRelatedItemsArgs,
		newGetRelatedItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	analyticsServiceServiceInfo                = NewServiceInfo()
	analyticsServiceServiceInfoForClient       = NewServiceInfoForClient()
	analyticsServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return analyticsServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return analyticsServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return analyticsServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AnalyticsService"
	handlerType := (*analytics.AnalyticsService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "analytics",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func getUserActivityStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.GetUserActivityStatsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).GetUserActivityStats(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserActivityStatsArgs:
		success, err := handler.(analytics.AnalyticsService).GetUserActivityStats(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserActivityStatsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserActivityStatsArgs() interface{} {
	return &GetUserActivityStatsArgs{}
}

func newGetUserActivityStatsResult() interface{} {
	return &GetUserActivityStatsResult{}
}

type GetUserActivityStatsArgs struct {
	Req *analytics.GetUserActivityStatsRequest
}

func (p *GetUserActivityStatsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserActivityStatsArgs) Unmarshal(in []byte) error {
	msg := new(analytics.GetUserActivityStatsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserActivityStatsArgs_Req_DEFAULT *analytics.GetUserActivityStatsRequest

func (p *GetUserActivityStatsArgs) GetReq() *analytics.GetUserActivityStatsRequest {
	if !p.IsSetReq() {
		return GetUserActivityStatsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserActivityStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserActivityStatsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserActivityStatsResult struct {
	Success *analytics.GetUserActivityStatsResponse
}

var GetUserActivityStatsResult_Success_DEFAULT *analytics.GetUserActivityStatsResponse

func (p *GetUserActivityStatsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserActivityStatsResult) Unmarshal(in []byte) error {
	msg := new(analytics.GetUserActivityStatsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserActivityStatsResult) GetSuccess() *analytics.GetUserActivityStatsResponse {
	if !p.IsSetSuccess() {
		return GetUserActivityStatsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserActivityStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.GetUserActivityStatsResponse)
}

func (p *GetUserActivityStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserActivityStatsResult) GetResult() interface{} {
	return p.Success
}

func getItemStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.GetItemStatsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).GetItemStats(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetItemStatsArgs:
		success, err := handler.(analytics.AnalyticsService).GetItemStats(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetItemStatsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetItemStatsArgs() interface{} {
	return &GetItemStatsArgs{}
}

func newGetItemStatsResult() interface{} {
	return &GetItemStatsResult{}
}

type GetItemStatsArgs struct {
	Req *analytics.GetItemStatsRequest
}

func (p *GetItemStatsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetItemStatsArgs) Unmarshal(in []byte) error {
	msg := new(analytics.GetItemStatsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetItemStatsArgs_Req_DEFAULT *analytics.GetItemStatsRequest

func (p *GetItemStatsArgs) GetReq() *analytics.GetItemStatsRequest {
	if !p.IsSetReq() {
		return GetItemStatsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetItemStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetItemStatsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetItemStatsResult struct {
	Success *analytics.GetItemStatsResponse
}

var GetItemStatsResult_Success_DEFAULT *analytics.GetItemStatsResponse

func (p *GetItemStatsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetItemStatsResult) Unmarshal(in []byte) error {
	msg := new(analytics.GetItemStatsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetItemStatsResult) GetSuccess() *analytics.GetItemStatsResponse {
	if !p.IsSetSuccess() {
		return GetItemStatsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetItemStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.GetItemStatsResponse)
}

func (p *GetItemStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetItemStatsResult) GetResult() interface{} {
	return p.Success
}

func getCollectionStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.GetCollectionStatsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).GetCollectionStats(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetCollectionStatsArgs:
		success, err := handler.(analytics.AnalyticsService).GetCollectionStats(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCollectionStatsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetCollectionStatsArgs() interface{} {
	return &GetCollectionStatsArgs{}
}

func newGetCollectionStatsResult() interface{} {
	return &GetCollectionStatsResult{}
}

type GetCollectionStatsArgs struct {
	Req *analytics.GetCollectionStatsRequest
}

func (p *GetCollectionStatsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetCollectionStatsArgs) Unmarshal(in []byte) error {
	msg := new(analytics.GetCollectionStatsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCollectionStatsArgs_Req_DEFAULT *analytics.GetCollectionStatsRequest

func (p *GetCollectionStatsArgs) GetReq() *analytics.GetCollectionStatsRequest {
	if !p.IsSetReq() {
		return GetCollectionStatsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCollectionStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCollectionStatsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCollectionStatsResult struct {
	Success *analytics.GetCollectionStatsResponse
}

var GetCollectionStatsResult_Success_DEFAULT *analytics.GetCollectionStatsResponse

func (p *GetCollectionStatsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetCollectionStatsResult) Unmarshal(in []byte) error {
	msg := new(analytics.GetCollectionStatsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCollectionStatsResult) GetSuccess() *analytics.GetCollectionStatsResponse {
	if !p.IsSetSuccess() {
		return GetCollectionStatsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCollectionStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.GetCollectionStatsResponse)
}

func (p *GetCollectionStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCollectionStatsResult) GetResult() interface{} {
	return p.Success
}

func getTagStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.GetTagStatsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).GetTagStats(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetTagStatsArgs:
		success, err := handler.(analytics.AnalyticsService).GetTagStats(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetTagStatsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetTagStatsArgs() interface{} {
	return &GetTagStatsArgs{}
}

func newGetTagStatsResult() interface{} {
	return &GetTagStatsResult{}
}

type GetTagStatsArgs struct {
	Req *analytics.GetTagStatsRequest
}

func (p *GetTagStatsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetTagStatsArgs) Unmarshal(in []byte) error {
	msg := new(analytics.GetTagStatsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetTagStatsArgs_Req_DEFAULT *analytics.GetTagStatsRequest

func (p *GetTagStatsArgs) GetReq() *analytics.GetTagStatsRequest {
	if !p.IsSetReq() {
		return GetTagStatsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetTagStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetTagStatsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetTagStatsResult struct {
	Success *analytics.GetTagStatsResponse
}

var GetTagStatsResult_Success_DEFAULT *analytics.GetTagStatsResponse

func (p *GetTagStatsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetTagStatsResult) Unmarshal(in []byte) error {
	msg := new(analytics.GetTagStatsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetTagStatsResult) GetSuccess() *analytics.GetTagStatsResponse {
	if !p.IsSetSuccess() {
		return GetTagStatsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetTagStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.GetTagStatsResponse)
}

func (p *GetTagStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetTagStatsResult) GetResult() interface{} {
	return p.Success
}

func getDomainStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.GetDomainStatsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).GetDomainStats(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetDomainStatsArgs:
		success, err := handler.(analytics.AnalyticsService).GetDomainStats(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetDomainStatsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetDomainStatsArgs() interface{} {
	return &GetDomainStatsArgs{}
}

func newGetDomainStatsResult() interface{} {
	return &GetDomainStatsResult{}
}

type GetDomainStatsArgs struct {
	Req *analytics.GetDomainStatsRequest
}

func (p *GetDomainStatsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetDomainStatsArgs) Unmarshal(in []byte) error {
	msg := new(analytics.GetDomainStatsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetDomainStatsArgs_Req_DEFAULT *analytics.GetDomainStatsRequest

func (p *GetDomainStatsArgs) GetReq() *analytics.GetDomainStatsRequest {
	if !p.IsSetReq() {
		return GetDomainStatsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetDomainStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetDomainStatsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetDomainStatsResult struct {
	Success *analytics.GetDomainStatsResponse
}

var GetDomainStatsResult_Success_DEFAULT *analytics.GetDomainStatsResponse

func (p *GetDomainStatsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetDomainStatsResult) Unmarshal(in []byte) error {
	msg := new(analytics.GetDomainStatsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetDomainStatsResult) GetSuccess() *analytics.GetDomainStatsResponse {
	if !p.IsSetSuccess() {
		return GetDomainStatsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetDomainStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.GetDomainStatsResponse)
}

func (p *GetDomainStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetDomainStatsResult) GetResult() interface{} {
	return p.Success
}

func getUsageTrendsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.GetUsageTrendsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).GetUsageTrends(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUsageTrendsArgs:
		success, err := handler.(analytics.AnalyticsService).GetUsageTrends(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUsageTrendsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUsageTrendsArgs() interface{} {
	return &GetUsageTrendsArgs{}
}

func newGetUsageTrendsResult() interface{} {
	return &GetUsageTrendsResult{}
}

type GetUsageTrendsArgs struct {
	Req *analytics.GetUsageTrendsRequest
}

func (p *GetUsageTrendsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUsageTrendsArgs) Unmarshal(in []byte) error {
	msg := new(analytics.GetUsageTrendsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUsageTrendsArgs_Req_DEFAULT *analytics.GetUsageTrendsRequest

func (p *GetUsageTrendsArgs) GetReq() *analytics.GetUsageTrendsRequest {
	if !p.IsSetReq() {
		return GetUsageTrendsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUsageTrendsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUsageTrendsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUsageTrendsResult struct {
	Success *analytics.GetUsageTrendsResponse
}

var GetUsageTrendsResult_Success_DEFAULT *analytics.GetUsageTrendsResponse

func (p *GetUsageTrendsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUsageTrendsResult) Unmarshal(in []byte) error {
	msg := new(analytics.GetUsageTrendsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUsageTrendsResult) GetSuccess() *analytics.GetUsageTrendsResponse {
	if !p.IsSetSuccess() {
		return GetUsageTrendsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUsageTrendsResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.GetUsageTrendsResponse)
}

func (p *GetUsageTrendsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUsageTrendsResult) GetResult() interface{} {
	return p.Success
}

func getItemAccessHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.GetItemAccessHistoryRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).GetItemAccessHistory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetItemAccessHistoryArgs:
		success, err := handler.(analytics.AnalyticsService).GetItemAccessHistory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetItemAccessHistoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetItemAccessHistoryArgs() interface{} {
	return &GetItemAccessHistoryArgs{}
}

func newGetItemAccessHistoryResult() interface{} {
	return &GetItemAccessHistoryResult{}
}

type GetItemAccessHistoryArgs struct {
	Req *analytics.GetItemAccessHistoryRequest
}

func (p *GetItemAccessHistoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetItemAccessHistoryArgs) Unmarshal(in []byte) error {
	msg := new(analytics.GetItemAccessHistoryRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetItemAccessHistoryArgs_Req_DEFAULT *analytics.GetItemAccessHistoryRequest

func (p *GetItemAccessHistoryArgs) GetReq() *analytics.GetItemAccessHistoryRequest {
	if !p.IsSetReq() {
		return GetItemAccessHistoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetItemAccessHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetItemAccessHistoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetItemAccessHistoryResult struct {
	Success *analytics.GetItemAccessHistoryResponse
}

var GetItemAccessHistoryResult_Success_DEFAULT *analytics.GetItemAccessHistoryResponse

func (p *GetItemAccessHistoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetItemAccessHistoryResult) Unmarshal(in []byte) error {
	msg := new(analytics.GetItemAccessHistoryResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetItemAccessHistoryResult) GetSuccess() *analytics.GetItemAccessHistoryResponse {
	if !p.IsSetSuccess() {
		return GetItemAccessHistoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetItemAccessHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.GetItemAccessHistoryResponse)
}

func (p *GetItemAccessHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetItemAccessHistoryResult) GetResult() interface{} {
	return p.Success
}

func recordItemAccessHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.RecordItemAccessRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).RecordItemAccess(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RecordItemAccessArgs:
		success, err := handler.(analytics.AnalyticsService).RecordItemAccess(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RecordItemAccessResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRecordItemAccessArgs() interface{} {
	return &RecordItemAccessArgs{}
}

func newRecordItemAccessResult() interface{} {
	return &RecordItemAccessResult{}
}

type RecordItemAccessArgs struct {
	Req *analytics.RecordItemAccessRequest
}

func (p *RecordItemAccessArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RecordItemAccessArgs) Unmarshal(in []byte) error {
	msg := new(analytics.RecordItemAccessRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RecordItemAccessArgs_Req_DEFAULT *analytics.RecordItemAccessRequest

func (p *RecordItemAccessArgs) GetReq() *analytics.RecordItemAccessRequest {
	if !p.IsSetReq() {
		return RecordItemAccessArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RecordItemAccessArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecordItemAccessArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RecordItemAccessResult struct {
	Success *analytics.RecordItemAccessResponse
}

var RecordItemAccessResult_Success_DEFAULT *analytics.RecordItemAccessResponse

func (p *RecordItemAccessResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RecordItemAccessResult) Unmarshal(in []byte) error {
	msg := new(analytics.RecordItemAccessResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RecordItemAccessResult) GetSuccess() *analytics.RecordItemAccessResponse {
	if !p.IsSetSuccess() {
		return RecordItemAccessResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RecordItemAccessResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.RecordItemAccessResponse)
}

func (p *RecordItemAccessResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecordItemAccessResult) GetResult() interface{} {
	return p.Success
}

func getRecommendedItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.GetRecommendedItemsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).GetRecommendedItems(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetRecommendedItemsArgs:
		success, err := handler.(analytics.AnalyticsService).GetRecommendedItems(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetRecommendedItemsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetRecommendedItemsArgs() interface{} {
	return &GetRecommendedItemsArgs{}
}

func newGetRecommendedItemsResult() interface{} {
	return &GetRecommendedItemsResult{}
}

type GetRecommendedItemsArgs struct {
	Req *analytics.GetRecommendedItemsRequest
}

func (p *GetRecommendedItemsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetRecommendedItemsArgs) Unmarshal(in []byte) error {
	msg := new(analytics.GetRecommendedItemsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetRecommendedItemsArgs_Req_DEFAULT *analytics.GetRecommendedItemsRequest

func (p *GetRecommendedItemsArgs) GetReq() *analytics.GetRecommendedItemsRequest {
	if !p.IsSetReq() {
		return GetRecommendedItemsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetRecommendedItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetRecommendedItemsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetRecommendedItemsResult struct {
	Success *analytics.GetRecommendedItemsResponse
}

var GetRecommendedItemsResult_Success_DEFAULT *analytics.GetRecommendedItemsResponse

func (p *GetRecommendedItemsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetRecommendedItemsResult) Unmarshal(in []byte) error {
	msg := new(analytics.GetRecommendedItemsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetRecommendedItemsResult) GetSuccess() *analytics.GetRecommendedItemsResponse {
	if !p.IsSetSuccess() {
		return GetRecommendedItemsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetRecommendedItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.GetRecommendedItemsResponse)
}

func (p *GetRecommendedItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetRecommendedItemsResult) GetResult() interface{} {
	return p.Success
}

func getRelatedItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(analytics.GetRelatedItemsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(analytics.AnalyticsService).GetRelatedItems(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetRelatedItemsArgs:
		success, err := handler.(analytics.AnalyticsService).GetRelatedItems(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetRelatedItemsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetRelatedItemsArgs() interface{} {
	return &GetRelatedItemsArgs{}
}

func newGetRelatedItemsResult() interface{} {
	return &GetRelatedItemsResult{}
}

type GetRelatedItemsArgs struct {
	Req *analytics.GetRelatedItemsRequest
}

func (p *GetRelatedItemsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetRelatedItemsArgs) Unmarshal(in []byte) error {
	msg := new(analytics.GetRelatedItemsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetRelatedItemsArgs_Req_DEFAULT *analytics.GetRelatedItemsRequest

func (p *GetRelatedItemsArgs) GetReq() *analytics.GetRelatedItemsRequest {
	if !p.IsSetReq() {
		return GetRelatedItemsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetRelatedItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetRelatedItemsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetRelatedItemsResult struct {
	Success *analytics.GetRelatedItemsResponse
}

var GetRelatedItemsResult_Success_DEFAULT *analytics.GetRelatedItemsResponse

func (p *GetRelatedItemsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetRelatedItemsResult) Unmarshal(in []byte) error {
	msg := new(analytics.GetRelatedItemsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetRelatedItemsResult) GetSuccess() *analytics.GetRelatedItemsResponse {
	if !p.IsSetSuccess() {
		return GetRelatedItemsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetRelatedItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*analytics.GetRelatedItemsResponse)
}

func (p *GetRelatedItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetRelatedItemsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetUserActivityStats(ctx context.Context, Req *analytics.GetUserActivityStatsRequest) (r *analytics.GetUserActivityStatsResponse, err error) {
	var _args GetUserActivityStatsArgs
	_args.Req = Req
	var _result GetUserActivityStatsResult
	if err = p.c.Call(ctx, "GetUserActivityStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetItemStats(ctx context.Context, Req *analytics.GetItemStatsRequest) (r *analytics.GetItemStatsResponse, err error) {
	var _args GetItemStatsArgs
	_args.Req = Req
	var _result GetItemStatsResult
	if err = p.c.Call(ctx, "GetItemStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCollectionStats(ctx context.Context, Req *analytics.GetCollectionStatsRequest) (r *analytics.GetCollectionStatsResponse, err error) {
	var _args GetCollectionStatsArgs
	_args.Req = Req
	var _result GetCollectionStatsResult
	if err = p.c.Call(ctx, "GetCollectionStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTagStats(ctx context.Context, Req *analytics.GetTagStatsRequest) (r *analytics.GetTagStatsResponse, err error) {
	var _args GetTagStatsArgs
	_args.Req = Req
	var _result GetTagStatsResult
	if err = p.c.Call(ctx, "GetTagStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDomainStats(ctx context.Context, Req *analytics.GetDomainStatsRequest) (r *analytics.GetDomainStatsResponse, err error) {
	var _args GetDomainStatsArgs
	_args.Req = Req
	var _result GetDomainStatsResult
	if err = p.c.Call(ctx, "GetDomainStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUsageTrends(ctx context.Context, Req *analytics.GetUsageTrendsRequest) (r *analytics.GetUsageTrendsResponse, err error) {
	var _args GetUsageTrendsArgs
	_args.Req = Req
	var _result GetUsageTrendsResult
	if err = p.c.Call(ctx, "GetUsageTrends", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetItemAccessHistory(ctx context.Context, Req *analytics.GetItemAccessHistoryRequest) (r *analytics.GetItemAccessHistoryResponse, err error) {
	var _args GetItemAccessHistoryArgs
	_args.Req = Req
	var _result GetItemAccessHistoryResult
	if err = p.c.Call(ctx, "GetItemAccessHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RecordItemAccess(ctx context.Context, Req *analytics.RecordItemAccessRequest) (r *analytics.RecordItemAccessResponse, err error) {
	var _args RecordItemAccessArgs
	_args.Req = Req
	var _result RecordItemAccessResult
	if err = p.c.Call(ctx, "RecordItemAccess", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRecommendedItems(ctx context.Context, Req *analytics.GetRecommendedItemsRequest) (r *analytics.GetRecommendedItemsResponse, err error) {
	var _args GetRecommendedItemsArgs
	_args.Req = Req
	var _result GetRecommendedItemsResult
	if err = p.c.Call(ctx, "GetRecommendedItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRelatedItems(ctx context.Context, Req *analytics.GetRelatedItemsRequest) (r *analytics.GetRelatedItemsResponse, err error) {
	var _args GetRelatedItemsArgs
	_args.Req = Req
	var _result GetRelatedItemsResult
	if err = p.c.Call(ctx, "GetRelatedItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
