// Code generated by Kitex v0.13.1. DO NOT EDIT.

package itemservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	item "github.com/linkbox-group/linkbox-server/rpc-gen/item"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateItem(ctx context.Context, Req *item.CreateItemRequest, callOptions ...callopt.Option) (r *item.CreateItemResponse, err error)
	GetItem(ctx context.Context, Req *item.GetItemRequest, callOptions ...callopt.Option) (r *item.GetItemResponse, err error)
	UpdateItem(ctx context.Context, Req *item.UpdateItemRequest, callOptions ...callopt.Option) (r *item.UpdateItemResponse, err error)
	GetItems(ctx context.Context, Req *item.GetItemsRequest, callOptions ...callopt.Option) (r *item.GetItemsResponse, err error)
	GetItemsByTags(ctx context.Context, Req *item.GetItemsByTagsRequest, callOptions ...callopt.Option) (r *item.GetItemsByTagsResponse, err error)
	GetItemsByOrganization(ctx context.Context, Req *item.GetItemsByOrganizationRequest, callOptions ...callopt.Option) (r *item.GetItemsByOrganizationResponse, err error)
	GetRecentItems(ctx context.Context, Req *item.GetRecentItemsRequest, callOptions ...callopt.Option) (r *item.GetRecentItemsResponse, err error)
	ImportFromFile(ctx context.Context, Req *item.ImportFromFileRequest, callOptions ...callopt.Option) (r *item.ImportFromFileResponse, err error)
	ExportToFile(ctx context.Context, Req *item.ExportToFileRequest, callOptions ...callopt.Option) (r *item.ExportToFileResponse, err error)
	SearchItems(ctx context.Context, Req *item.SearchItemsRequest, callOptions ...callopt.Option) (r *item.SearchItemsResponse, err error)
	DeleteItem(ctx context.Context, Req *item.DeleteItemRequest, callOptions ...callopt.Option) (r *item.DeleteItemResponse, err error)
	RecoverItem(ctx context.Context, Req *item.RecoverItemRequest, callOptions ...callopt.Option) (r *item.RecoverItemREsponse, err error)
	GetDeletedItems(ctx context.Context, Req *item.GetDeletedItemsRequest, callOptions ...callopt.Option) (r *item.GetDeletedItemsResponse, err error)
	RecoverItemsBatch(ctx context.Context, Req *item.RecoverItemsBatchRequest, callOptions ...callopt.Option) (r *item.RecoverItemsBatchResponse, err error)
	DeleteItemsBatch(ctx context.Context, Req *item.DeleteItemsBatchRequest, callOptions ...callopt.Option) (r *item.DeleteItemsBatchResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kItemServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kItemServiceClient struct {
	*kClient
}

func (p *kItemServiceClient) CreateItem(ctx context.Context, Req *item.CreateItemRequest, callOptions ...callopt.Option) (r *item.CreateItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateItem(ctx, Req)
}

func (p *kItemServiceClient) GetItem(ctx context.Context, Req *item.GetItemRequest, callOptions ...callopt.Option) (r *item.GetItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItem(ctx, Req)
}

func (p *kItemServiceClient) UpdateItem(ctx context.Context, Req *item.UpdateItemRequest, callOptions ...callopt.Option) (r *item.UpdateItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateItem(ctx, Req)
}

func (p *kItemServiceClient) GetItems(ctx context.Context, Req *item.GetItemsRequest, callOptions ...callopt.Option) (r *item.GetItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItems(ctx, Req)
}

func (p *kItemServiceClient) GetItemsByTags(ctx context.Context, Req *item.GetItemsByTagsRequest, callOptions ...callopt.Option) (r *item.GetItemsByTagsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItemsByTags(ctx, Req)
}

func (p *kItemServiceClient) GetItemsByOrganization(ctx context.Context, Req *item.GetItemsByOrganizationRequest, callOptions ...callopt.Option) (r *item.GetItemsByOrganizationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItemsByOrganization(ctx, Req)
}

func (p *kItemServiceClient) GetRecentItems(ctx context.Context, Req *item.GetRecentItemsRequest, callOptions ...callopt.Option) (r *item.GetRecentItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecentItems(ctx, Req)
}

func (p *kItemServiceClient) ImportFromFile(ctx context.Context, Req *item.ImportFromFileRequest, callOptions ...callopt.Option) (r *item.ImportFromFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ImportFromFile(ctx, Req)
}

func (p *kItemServiceClient) ExportToFile(ctx context.Context, Req *item.ExportToFileRequest, callOptions ...callopt.Option) (r *item.ExportToFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ExportToFile(ctx, Req)
}

func (p *kItemServiceClient) SearchItems(ctx context.Context, Req *item.SearchItemsRequest, callOptions ...callopt.Option) (r *item.SearchItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchItems(ctx, Req)
}

func (p *kItemServiceClient) DeleteItem(ctx context.Context, Req *item.DeleteItemRequest, callOptions ...callopt.Option) (r *item.DeleteItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteItem(ctx, Req)
}

func (p *kItemServiceClient) RecoverItem(ctx context.Context, Req *item.RecoverItemRequest, callOptions ...callopt.Option) (r *item.RecoverItemREsponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RecoverItem(ctx, Req)
}

func (p *kItemServiceClient) GetDeletedItems(ctx context.Context, Req *item.GetDeletedItemsRequest, callOptions ...callopt.Option) (r *item.GetDeletedItemsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDeletedItems(ctx, Req)
}

func (p *kItemServiceClient) RecoverItemsBatch(ctx context.Context, Req *item.RecoverItemsBatchRequest, callOptions ...callopt.Option) (r *item.RecoverItemsBatchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RecoverItemsBatch(ctx, Req)
}

func (p *kItemServiceClient) DeleteItemsBatch(ctx context.Context, Req *item.DeleteItemsBatchRequest, callOptions ...callopt.Option) (r *item.DeleteItemsBatchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteItemsBatch(ctx, Req)
}
