// Code generated by Kitex v0.13.1. DO NOT EDIT.

package authservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	auth "github.com/linkbox-group/linkbox-server/rpc-gen/auth"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenerateRefreshToken": kitex.NewMethodInfo(
		generateRefreshTokenHandler,
		newGenerateRefreshTokenArgs,
		newGenerateRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GenerateAccessToken": kitex.NewMethodInfo(
		generateAccessTokenHandler,
		newGenerateAccessTokenArgs,
		newGenerateAccessTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newRefreshTokenArgs,
		newRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DestroyRefreshToken": kitex.NewMethodInfo(
		destroyRefreshTokenHandler,
		newDestroyRefreshTokenArgs,
		newDestroyRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"VerifyAccessToken": kitex.NewMethodInfo(
		verifyAccessTokenHandler,
		newVerifyAccessTokenArgs,
		newVerifyAccessTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	authServiceServiceInfo                = NewServiceInfo()
	authServiceServiceInfoForClient       = NewServiceInfoForClient()
	authServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return authServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "authService"
	handlerType := (*auth.AuthService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "auth",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func generateRefreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.GenerateTokenReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).GenerateRefreshToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GenerateRefreshTokenArgs:
		success, err := handler.(auth.AuthService).GenerateRefreshToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GenerateRefreshTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGenerateRefreshTokenArgs() interface{} {
	return &GenerateRefreshTokenArgs{}
}

func newGenerateRefreshTokenResult() interface{} {
	return &GenerateRefreshTokenResult{}
}

type GenerateRefreshTokenArgs struct {
	Req *auth.GenerateTokenReq
}

func (p *GenerateRefreshTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenerateRefreshTokenArgs) Unmarshal(in []byte) error {
	msg := new(auth.GenerateTokenReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenerateRefreshTokenArgs_Req_DEFAULT *auth.GenerateTokenReq

func (p *GenerateRefreshTokenArgs) GetReq() *auth.GenerateTokenReq {
	if !p.IsSetReq() {
		return GenerateRefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenerateRefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenerateRefreshTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenerateRefreshTokenResult struct {
	Success *auth.TokenString
}

var GenerateRefreshTokenResult_Success_DEFAULT *auth.TokenString

func (p *GenerateRefreshTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenerateRefreshTokenResult) Unmarshal(in []byte) error {
	msg := new(auth.TokenString)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenerateRefreshTokenResult) GetSuccess() *auth.TokenString {
	if !p.IsSetSuccess() {
		return GenerateRefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenerateRefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.TokenString)
}

func (p *GenerateRefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenerateRefreshTokenResult) GetResult() interface{} {
	return p.Success
}

func generateAccessTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.GenerateTokenReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).GenerateAccessToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GenerateAccessTokenArgs:
		success, err := handler.(auth.AuthService).GenerateAccessToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GenerateAccessTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGenerateAccessTokenArgs() interface{} {
	return &GenerateAccessTokenArgs{}
}

func newGenerateAccessTokenResult() interface{} {
	return &GenerateAccessTokenResult{}
}

type GenerateAccessTokenArgs struct {
	Req *auth.GenerateTokenReq
}

func (p *GenerateAccessTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenerateAccessTokenArgs) Unmarshal(in []byte) error {
	msg := new(auth.GenerateTokenReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenerateAccessTokenArgs_Req_DEFAULT *auth.GenerateTokenReq

func (p *GenerateAccessTokenArgs) GetReq() *auth.GenerateTokenReq {
	if !p.IsSetReq() {
		return GenerateAccessTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenerateAccessTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenerateAccessTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenerateAccessTokenResult struct {
	Success *auth.TokenString
}

var GenerateAccessTokenResult_Success_DEFAULT *auth.TokenString

func (p *GenerateAccessTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenerateAccessTokenResult) Unmarshal(in []byte) error {
	msg := new(auth.TokenString)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenerateAccessTokenResult) GetSuccess() *auth.TokenString {
	if !p.IsSetSuccess() {
		return GenerateAccessTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenerateAccessTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.TokenString)
}

func (p *GenerateAccessTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenerateAccessTokenResult) GetResult() interface{} {
	return p.Success
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.TokenRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).RefreshToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RefreshTokenArgs:
		success, err := handler.(auth.AuthService).RefreshToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RefreshTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRefreshTokenArgs() interface{} {
	return &RefreshTokenArgs{}
}

func newRefreshTokenResult() interface{} {
	return &RefreshTokenResult{}
}

type RefreshTokenArgs struct {
	Req *auth.TokenRequest
}

func (p *RefreshTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RefreshTokenArgs) Unmarshal(in []byte) error {
	msg := new(auth.TokenRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RefreshTokenArgs_Req_DEFAULT *auth.TokenRequest

func (p *RefreshTokenArgs) GetReq() *auth.TokenRequest {
	if !p.IsSetReq() {
		return RefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefreshTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RefreshTokenResult struct {
	Success *auth.TokenString
}

var RefreshTokenResult_Success_DEFAULT *auth.TokenString

func (p *RefreshTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RefreshTokenResult) Unmarshal(in []byte) error {
	msg := new(auth.TokenString)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RefreshTokenResult) GetSuccess() *auth.TokenString {
	if !p.IsSetSuccess() {
		return RefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.TokenString)
}

func (p *RefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefreshTokenResult) GetResult() interface{} {
	return p.Success
}

func destroyRefreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.TokenRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).DestroyRefreshToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DestroyRefreshTokenArgs:
		success, err := handler.(auth.AuthService).DestroyRefreshToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DestroyRefreshTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDestroyRefreshTokenArgs() interface{} {
	return &DestroyRefreshTokenArgs{}
}

func newDestroyRefreshTokenResult() interface{} {
	return &DestroyRefreshTokenResult{}
}

type DestroyRefreshTokenArgs struct {
	Req *auth.TokenRequest
}

func (p *DestroyRefreshTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DestroyRefreshTokenArgs) Unmarshal(in []byte) error {
	msg := new(auth.TokenRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DestroyRefreshTokenArgs_Req_DEFAULT *auth.TokenRequest

func (p *DestroyRefreshTokenArgs) GetReq() *auth.TokenRequest {
	if !p.IsSetReq() {
		return DestroyRefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DestroyRefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DestroyRefreshTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DestroyRefreshTokenResult struct {
	Success *emptypb.Empty
}

var DestroyRefreshTokenResult_Success_DEFAULT *emptypb.Empty

func (p *DestroyRefreshTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DestroyRefreshTokenResult) Unmarshal(in []byte) error {
	msg := new(emptypb.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DestroyRefreshTokenResult) GetSuccess() *emptypb.Empty {
	if !p.IsSetSuccess() {
		return DestroyRefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DestroyRefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*emptypb.Empty)
}

func (p *DestroyRefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DestroyRefreshTokenResult) GetResult() interface{} {
	return p.Success
}

func verifyAccessTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.TokenRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).VerifyAccessToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *VerifyAccessTokenArgs:
		success, err := handler.(auth.AuthService).VerifyAccessToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VerifyAccessTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newVerifyAccessTokenArgs() interface{} {
	return &VerifyAccessTokenArgs{}
}

func newVerifyAccessTokenResult() interface{} {
	return &VerifyAccessTokenResult{}
}

type VerifyAccessTokenArgs struct {
	Req *auth.TokenRequest
}

func (p *VerifyAccessTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *VerifyAccessTokenArgs) Unmarshal(in []byte) error {
	msg := new(auth.TokenRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VerifyAccessTokenArgs_Req_DEFAULT *auth.TokenRequest

func (p *VerifyAccessTokenArgs) GetReq() *auth.TokenRequest {
	if !p.IsSetReq() {
		return VerifyAccessTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VerifyAccessTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerifyAccessTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type VerifyAccessTokenResult struct {
	Success *auth.AccessTokenInfo
}

var VerifyAccessTokenResult_Success_DEFAULT *auth.AccessTokenInfo

func (p *VerifyAccessTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *VerifyAccessTokenResult) Unmarshal(in []byte) error {
	msg := new(auth.AccessTokenInfo)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VerifyAccessTokenResult) GetSuccess() *auth.AccessTokenInfo {
	if !p.IsSetSuccess() {
		return VerifyAccessTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VerifyAccessTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.AccessTokenInfo)
}

func (p *VerifyAccessTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerifyAccessTokenResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenerateRefreshToken(ctx context.Context, Req *auth.GenerateTokenReq) (r *auth.TokenString, err error) {
	var _args GenerateRefreshTokenArgs
	_args.Req = Req
	var _result GenerateRefreshTokenResult
	if err = p.c.Call(ctx, "GenerateRefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GenerateAccessToken(ctx context.Context, Req *auth.GenerateTokenReq) (r *auth.TokenString, err error) {
	var _args GenerateAccessTokenArgs
	_args.Req = Req
	var _result GenerateAccessTokenResult
	if err = p.c.Call(ctx, "GenerateAccessToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, Req *auth.TokenRequest) (r *auth.TokenString, err error) {
	var _args RefreshTokenArgs
	_args.Req = Req
	var _result RefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DestroyRefreshToken(ctx context.Context, Req *auth.TokenRequest) (r *emptypb.Empty, err error) {
	var _args DestroyRefreshTokenArgs
	_args.Req = Req
	var _result DestroyRefreshTokenResult
	if err = p.c.Call(ctx, "DestroyRefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyAccessToken(ctx context.Context, Req *auth.TokenRequest) (r *auth.AccessTokenInfo, err error) {
	var _args VerifyAccessTokenArgs
	_args.Req = Req
	var _result VerifyAccessTokenResult
	if err = p.c.Call(ctx, "VerifyAccessToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
