// Code generated by Kitex v0.13.1. DO NOT EDIT.

package types

import (
	"google.golang.org/protobuf/types/known/timestamppb"

	"github.com/cloudwego/prutal"
)

// 空响应
type EmptyResponse struct {
}

func (x *EmptyResponse) Reset() { *x = EmptyResponse{} }

func (x *EmptyResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *EmptyResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

// ID请求
type IdRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (x *IdRequest) Reset() { *x = IdRequest{} }

func (x *IdRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IdRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 时间区间
type TimeRange struct {
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time" json:"end_time,omitempty"`
}

func (x *TimeRange) Reset() { *x = TimeRange{} }

func (x *TimeRange) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *TimeRange) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *TimeRange) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TimeRange) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// 地理位置
type GeoLocation struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (x *GeoLocation) Reset() { *x = GeoLocation{} }

func (x *GeoLocation) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GeoLocation) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GeoLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}
