name: ai_workflow.yml
on:
  push:
    tags:
      - ai_v**
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./app/ai
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Docker Image Url
        id: image
        env:
          URL: xyq777/linkbox-ai
        run: |
          echo LATEST=${URL}:latest >> $GITHUB_OUTPUT
          echo VERSION=${URL}:${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
        run: |
          go build -o runner ./cmd/linkbox_ai
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
          --tag ${{ steps.image.outputs.VERSION }} \
          --tag ${{ steps.image.outputs.LATEST }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: |
          docker push ${{ steps.image.outputs.VERSION }}
          docker push ${{ steps.image.outputs.LATEST }}

      - name: Update Deployment
        uses: MultiMx/K8sSetImageAction@v0.2
        with:
          backend: "https://rancher.xyq777.com"
          token: ${{ secrets.RANCHER_TOKEN }}
          namespace: "linkbox"
          image: ${{ steps.image.outputs.VERSION }}
          deployment: "linkbox-ai"
